// =============================================================================
// TRADEREFER CONTENT — BATCH 08
// Suburbs 71–80
// Research-backed, AU-specific content
// =============================================================================

"altona-north": {
    housing: "Altona North has always been the working suburb that Altona proper wasn't — 10km south-west of the CBD in Hobsons Bay, and defined by the industrial precinct that occupies most of its western half. The ExxonMobil refinery and the Altona North Industrial Precinct have been neighbours to the residential streets since the post-war years. The housing is predominantly 1950s–1970s brick and weatherboard on modest blocks, built for the manufacturing and refinery workforce and never especially gentrified. That's changing now — the industrial land is being rezoned for a 3,000-home mixed-use redevelopment, which is the biggest land-use shift Hobsons Bay has seen in a generation. What you have today is established working-class suburban Melbourne alongside the beginning of something quite different.",
    climate: "Western Melbourne / Port Phillip Bay foreshore — the bay is close and the south-westerly sea breeze moderates the summer heat noticeably compared to the flat western fringe suburbs further inland. Altona North is cooler in summer than Sunshine or Footscray by a meaningful margin. Winters are cool with southerly influence off the bay. The industrial areas do create some local air quality variability.",
    council: "City of Hobsons Bay",
    region: "Western Melbourne / Hobsons Bay",
    tradeNotes: {
        "Building": "The industrial-to-residential transition happening in Altona North's western precinct will generate sustained development activity over the coming decade — builders with experience in brownfield remediation and high-density residential construction will find a growing market here as the Altona North Strategic Site development progresses. The existing residential streets are also seeing renovation activity as the suburb's desirability increases alongside the redevelopment.",
        "Concreting": "The Hobsons Bay reactive clay soils underlie most of Altona North's residential area — the grey heavy clay that causes driveway and path movement across the western bay suburbs. Original 1950s–1960s concrete paths are now 60–70 years old and typically need full replacement rather than patch repair. Concrete specifications for new work here need proper sub-base compaction and control joints to manage the shrink-swell cycle.",
    },
},

"claremont": {
    housing: "Claremont TAS sits about 15km north of Hobart along the Derwent, and it has two distinct periods in its residential history. Before the war, it was mostly farms and a handful of houses. Then, from the late 1950s through the 1980s, the City of Glenorchy built significant public housing here — weatherboard and fibrous cement homes in estates that housed the industrial workforce from the nearby Cadbury's Claremont factory and the broader Glenorchy manufacturing precinct. Private residential development filled in the gaps through the 1970s and 1980s. It's not a glamorous suburb by any measure, but the river views from the higher streets and the proximity to Cadbury's are genuine Hobart points of difference.",
    climate: "Derwent River valley, north of Hobart — sheltered from the worst of the Antarctic-sourced southwesterlies by the ranges to the south, but still cold. Frosts from May through August are common on the flat valley land. The river creates some humidity and the valley floor is noticeably colder on still winter nights than the hill properties. Summer is mild and pleasant. The Cadbury's factory was famous for releasing chocolate smell across the valley on certain wind directions, for what it's worth.",
    council: "City of Glenorchy",
    region: "Northern Hobart / Glenorchy",
    tradeNotes: {
        "Insulation": "Like much of the Glenorchy area, Claremont's older public housing and 1960s–1980s private stock is poorly insulated — Zone 7 NCC energy ratings apply to Hobart and the original homes here have ceiling insulation that's either absent, damaged, or far below current standards. The Tasmanian government's home energy upgrade programs have targeted exactly this type of housing stock and the payback period on ceiling plus sub-floor insulation upgrades is consistently measured in a few heating seasons.",
        "Building": "The fibrous cement construction that characterises much of Claremont's older housing stock contains asbestos in a significant proportion of pre-1987 homes — cladding, eaves lining, internal linings, and floor backing. Safe Work Tasmania regulations require an asbestos survey and management plan before any renovation work on these homes, and the handling of asbestos-containing materials must comply with the applicable Code of Practice.",
        "Roofing": "The older corrugated iron roofing on Claremont's 1960s–1980s homes is common and ageing — the Derwent valley wind and the cold wet winters accelerate moss growth and ridge capping mortar failure on south and east facing aspects. Many roofs here are at or past the point where replacement is more cost-effective than ongoing repair.",
    },
},

"deer-park": {
    housing: "Deer Park is classic western Melbourne — 17km from the CBD, Brimbank Council, and a suburb defined by its industrial history. The Nobel chemicals factory that established here in the 1920s built worker housing around the factory site, giving the suburb its unusual combination of industrial and residential uses on the same streets from the outset. The bulk of the housing is post-war brick veneer from the 1950s through the 1980s, the standard western Melbourne suburban type. More recently, the southern fringe paddocks have been developed into new residential estates — Brimbank Gardens and similar — that bring a newer housing demographic alongside the established post-war streets.",
    climate: "Western Melbourne — inland and exposed. Deer Park gets the full western suburbs summer heat with none of the coastal moderating influence that helps Altona and Williamstown. Summer days above 40°C happen here. The Western Ring Road and the freight rail corridor through the suburb creates some wind channelling. Winters are cold and the flat, open western plains give nothing to shelter the suburb from westerly fronts.",
    council: "City of Brimbank",
    region: "Western Melbourne / Brimbank",
    tradeNotes: {
        "Electrical": "Deer Park's 1950s–1980s housing stock has the standard western Melbourne electrical profile — ceramic fuse boards and original TPS wiring are common in the pre-1980s homes, and the high proportion of post-war Housing Commission stock in Brimbank means there's a consistent safety upgrade market. RCD installations, switchboard replacements, and solar retrofits are the dominant workload categories.",
        "Landscaping": "The volcanic basalt clay soils of western Melbourne underlie much of Deer Park — dense, cracking clay that's poorly draining in winter and rock-hard in summer. Garden establishment on the clay soils here requires serious soil amendment and thoughtful plant selection for drought tolerance; the 40°C summer days kill plants that would survive the same heat in the sandy eastern suburbs with their better moisture retention.",
        "Air Conditioning & Heating": "The western Melbourne heat extremes that Deer Park experiences make cooling a genuine necessity rather than a comfort — split system and ducted reverse-cycle replacements in the 1970s–1990s housing stock are a consistent demand. Original evaporative coolers, which were common in the post-war western suburbs, struggle in the high-humidity periods that accompany Melbourne's summer thunderstorm season.",
    },
},

"ocean-grove": {
    housing: "Ocean Grove is the Bellarine Peninsula's largest town and the one that got the most of the sea-change demographic of the last 25 years. The original settlement — gazetted as a Temperance resort town in the 1880s, hence the longstanding absence of a pub — has a scatter of older holiday cottages and post-war fibro weekenders from the era when it was Geelong's beach getaway. The major residential buildout happened from the 1990s through the 2010s as Melbourne retirees and Geelong commuters discovered the Bellarine, and that wave of 1990s–2010s brick veneer sits alongside the older stock in a way that makes the suburb feel generationally diverse. Newer masterplanned estates are still developing on the north-western edge.",
    climate: "Bass Strait coastal — the open ocean is right there and Ocean Grove gets full southern ocean swell and the coastal conditions that come with it. The Barwon Heads channel to the south creates some local wind funnel effects. South-westerly swells and winds are the dominant coastal force. Summer is warm and typically reliable for the sea breeze that defines the Bellarine experience. Winter is noticeably cooler than Geelong and exposed fronts from Antarctica come through the Bass Strait without much moderation.",
    council: "City of Greater Geelong",
    region: "Bellarine Peninsula / Greater Geelong",
    tradeNotes: {
        "Roofing": "Ocean Grove's coastal position creates the same corrosion-accelerating salt air environment as any Bass Strait-facing town — standard Colorbond and galvanised iron deteriorates faster here than inland, particularly for properties within a couple of hundred metres of the beach or the Barwon heads channel. BlueScope's coastal-rated product is the correct specification for these locations.",
        "Building": "Ocean Grove has been one of Victoria's most active growth towns over the last decade, which means the City of Greater Geelong's planning requirements and the Bellarine Peninsula planning overlay provisions are live considerations for any new construction — coastal setbacks, vegetation protection along the foreshore, and BAL ratings for properties near the Barwon Heads scrub all add complexity to building work here.",
        "Landscaping": "The coastal scrub vegetation along Ocean Grove's foreshore is protected under the Greater Geelong planning scheme and the Parks Victoria management plan for the Barwon Heads coastal reserve — landscaping near these areas has to comply with coastal vegetation management requirements. The sandy coastal soils drain quickly and need organic amendment for garden establishment, and the salt air exposure demands plant selection that can handle direct coastal conditions.",
    },
},

"carnegie": {
    housing: "Carnegie is inner south-east Melbourne in the genuinely established sense — 10km from the CBD, part of the City of Glen Eira, and with a housing stock that is predominantly Federation and inter-war from the 1890s through the 1940s. The suburb developed around the Carnegie railway station and the residential streetscapes closest to the station have some of Melbourne's better Edwardian bungalows on generous allotments. The later streets going south toward Murrumbeena have more standard 1950s–1960s brick veneer filling in the gaps. The Carnegie residential precinct is recognised in the Glen Eira Heritage Study and the heritage overlay covers many of the pre-1940 streets. Significantly different to its neighbour Bentleigh East in terms of housing era and character.",
    climate: "Inner south-east Melbourne — Port Phillip Bay sea breeze arrives reasonably reliably in the afternoon on hot days, which moderates the worst summer temperatures. The bay influence keeps winters somewhat milder than the northern suburbs. The Caulfield Racecourse Reserve a suburb away provides a notable green open space influence on the local microclimate.",
    council: "City of Glen Eira",
    region: "Inner South-East Melbourne / Glen Eira",
    tradeNotes: {
        "Building": "The Carnegie residential precinct's Heritage Overlay under the Glen Eira planning scheme means external works on pre-1940 homes need heritage permit consideration — Glen Eira's heritage team is active and the HO applies to the Federation and inter-war streetscapes that define Carnegie's character. Builders working on period renovations here need familiarity with permitted works and the relevant heritage controls.",
        "Roofing": "Carnegie's Federation and Edwardian housing stock carries original Marseille terracotta tiles on most of the period homes — many are now 80–100+ years old and the tiles themselves are often sound but the bedding mortar, pointing, and valley flashings have failed completely. The ridge repointing and valley flashing replacement market on Carnegie's period homes is substantial and ongoing.",
        "Painting": "The pre-1940 housing stock in Carnegie has multiple historical paint layers, with lead-based coatings likely in the earlier applications on properties built before 1970. Painters working on exterior and interior work in the Federation and Edwardian homes should follow AS 4361.2 lead paint procedures and carry out the appropriate surface assessment before work begins.",
    },
},

"eight-mile-plains": {
    housing: "Eight Mile Plains sits in Brisbane's southern fringe around the intersection of the Pacific Motorway and Beaudesert Road, and the housing reflects the suburban expansion wave that pushed south from Brisbane in the 1970s and 1980s. Brick and Hardiplank homes from that era dominate, on the standard 600–700 sqm south-east Queensland suburban block. The suburb has a significant commercial and light industrial component along the motorway corridor. It's not a beach suburb or a heritage suburb — it's the working southern Brisbane fringe, practical and unpretentious, with reasonable transport access to the city via the freeway and the rail at nearby Eight Mile Plains station.",
    climate: "Southern Brisbane — subtropical, warm and humid in summer with the daily storm season running November through March. The South East Freeway corridor can create some local traffic-driven heat and pollution but the broader climate is the standard greater Brisbane subtropical experience. Winters are mild and dry, genuinely pleasant. The inland position means it's a few degrees warmer on summer days than the bayside suburbs.",
    council: "Brisbane City Council",
    region: "Southern Brisbane / Logan Interface",
    tradeNotes: {
        "Air Conditioning & Heating": "Brisbane's subtropical climate and the suburban heat that comes with it makes reverse-cycle split systems the dominant HVAC type in Eight Mile Plains' 1970s–1980s housing stock — a lot of the original installations from the 1990s and early 2000s are now reaching end of life, and the replacement market is active. The newer units are substantially more efficient than the older R22 refrigerant machines they're replacing.",
        "Building": "Eight Mile Plains has a higher proportion of commercial and light industrial buildings along its road corridors than the purely residential suburbs around it — builders here work across a mix of residential renovation and commercial fit-out that requires breadth rather than the depth of specialist residential or commercial expertise.",
        "Landscaping": "The red volcanic clay soils and the sandy alluvial soils that coexist in south-east Queensland create variable drainage conditions across the suburb — some blocks drain freely while others retain water during the storm season. Proper grading and drainage design is important for garden establishment in the lower-lying areas around the flood-prone creek corridors.",
    },
},

"cronulla": {
    housing: "Cronulla is Sydney's only directly beach-accessible suburb by train, and the peninsula geography — framed by Botany Bay, the Pacific, Port Hacking, and Gunnamatta Bay — creates a very specific real estate character. The original 1920s–1940s fibro and weatherboard beach houses survive in smaller numbers, with the dominant stock being 1950s–1970s brick homes and three-storey walk-up apartment blocks on the streets back from the beach, reflecting the post-war coastal apartment building wave. Closer to the main shopping strip the density increases with 2000s and 2010s apartment towers. The foreshore itself has seen some of Sydney's more dramatic price appreciation as the surfside lifestyle premium has compounded. Median house prices over $3 million make it among the most expensive in the Sutherland Shire.",
    climate: "Full ocean coastal exposure — the Pacific on the east side, the Bay on the west and north, and Port Hacking on the south. Cronulla gets proper ocean conditions: consistent onshore sea breezes, significant salt air, and humidity that's higher than inland suburbs. Summer is warm and the sea breeze usually arrives by mid-morning thanks to the peninsula's narrow width. South-easterly swells can push spray well inland on the exposed eastern foreshore. The bay and inlet positions on the western sides are more sheltered.",
    council: "Sutherland Shire Council",
    region: "Sutherland Shire / Sydney's South",
    tradeNotes: {
        "Roofing": "Cronulla's ocean beach exposure makes coastal product specification not optional — salt spray from the Pacific is measurable throughout the suburb and standard galvanised iron guttering and roofing deteriorates at a rate that surprises homeowners and tradies who come from inland suburbs. BlueScope Colorbond Ultra or equivalent coastal-rated product is the correct standard for any roofing work within 500m of the beach or bay foreshore.",
        "Building": "The foreshore properties along Cronulla's Pacific and bay frontages are subject to Sutherland Shire Council's coastal hazard overlay provisions and some areas have setback requirements from coastal erosion zones — any development or substantial renovation near the waterfront requires a coastal engineering assessment under the NSW Coastal Management SEPP before a DA is lodged.",
        "Landscaping": "The peninsula geography means virtually the entire suburb has meaningful coastal salt air exposure — garden species selection should favour salt-tolerant coastal natives and hardy exotics over the full ornamental palette that works in sheltered inner Sydney gardens. The coastal banksia scrub that historically covered the Cronulla sand barrier is the ecological reference point for what genuinely thrives here.",
    },
},

"albert-park": {
    housing: "Albert Park is inner Melbourne at its most photogenic — 4km south of the CBD, and the suburb has one of the most intact Victorian and Edwardian streetscapes in the whole of Melbourne. The housing stock is predominantly 1870s–1910s: double-fronted Victorian terraces with iron lacework, Edwardian timber bungalows on generous lots, and the occasional rendered villa. The Albert Park Lake precinct and the street grid laid out before 1880 give the suburb a geometry and a grandeur that later development didn't touch. The heritage overlay covers essentially the entire suburb. Port Phillip Council takes the protection seriously. Prices reflect it — Albert Park is consistently among Melbourne's most expensive inner-south suburbs.",
    climate: "Inner south Melbourne, Port Phillip Bay foreshore — the bay is close and the southerly sea breeze that drives up from the bay makes Albert Park genuinely cooler on summer afternoons than the northern or western suburbs at equivalent distances from the CBD. The Albert Park Lake itself creates a local microclimate benefit. Winters are cool and overcast with the characteristic Melbourne southerly influence from the bay.",
    council: "City of Port Phillip",
    region: "Inner South Melbourne / Port Phillip",
    tradeNotes: {
        "Building": "The Heritage Overlay in Albert Park covers almost the entire suburb — virtually every Victorian and Edwardian property in the suburb is subject to heritage permit requirements for external alterations, demolition, or significant additions. Port Phillip City Council's heritage team is well-resourced and active, and building work on period properties here requires detailed heritage design assessment and often pre-application meetings with council heritage officers.",
        "Painting": "Albert Park's Victorian and Edwardian terrace stock has extensive historical paint layers, with lead in the earlier applications on buildings pre-dating the 1960s essentially guaranteed. The rendered masonry facades common on Victorian villas require lime-based or breathable acrylic systems to prevent moisture trapping — using standard exterior acrylic on Victorian lime render without surface preparation assessment is a recipe for paint failure and moisture damage.",
        "Landscaping": "The predominantly period housing stock in Albert Park has established gardens on moderate allotments with heritage trees that are covered by Port Phillip's significant tree register. Any significant tree removal or work within the root protection zone requires council assessment, and the rear lane network that serves many Albert Park terrace properties creates specific access constraints for landscaping equipment.",
    },
},

"burleigh-heads": {
    housing: "Burleigh Heads is the Gold Coast suburb that every other Gold Coast suburb wants to be right now — it has the beach, the headland, the café strip, and proximity to both the Gold Coast and Brisbane that has made it the number one destination for interstate migration buyers. The housing stock is genuinely mixed: 1960s–1970s lowset brick and Hardiplank homes on the inland streets, mid-century holiday houses closer to the headland that are now being knocked over for prestige builds, and a growing overlay of high-rise apartment towers along the esplanade. The headland park and the surf break off Burleigh Point define the suburb's physical character and its appeal.",
    climate: "South-east Queensland coastal — subtropical, reliable sea breeze off the Pacific, and genuinely consistent all year. Summer brings humidity and the daily afternoon storm pattern of the Gold Coast hinterland. Winter is one of the best climates in the country. The south coast position means Burleigh Heads gets the southerly swell that defines the Burleigh surf break, and the south-facing aspects of the headland properties get the most wind exposure.",
    council: "City of Gold Coast",
    region: "Gold Coast South / Burleigh",
    tradeNotes: {
        "Roofing": "The Coral Sea and Pacific coastal environment demands coastal-grade roofing materials in Burleigh Heads — the salt air from the beachfront is measureable throughout the suburb and products not rated for C3 or C4 marine environments deteriorate faster than they would even 5km inland. The older 1960s–1970s roofing on the inland streets is at or past service life and the replacement market here is active and price-insensitive given the suburb's premium residential market.",
        "Building": "Burleigh Heads' rapid transformation from mid-century beach suburb to prestige destination has created significant development tension — demolition of original homes to build prestige knockdown-rebuilds is common, and the City of Gold Coast's planning requirements for the foreshore and headland precincts include specific setback and height provisions that vary from standard residential zones. The headland parkland's proximity also imposes vegetation and fire management considerations on adjacent properties.",
        "Air Conditioning & Heating": "Subtropical Gold Coast conditions mean cooling is year-round rather than seasonal — the older 1970s–1980s homes in Burleigh typically have the original split systems or ducted systems from the 1990s–2000s that are well past their optimum efficiency point. The premium renovation market here also drives demand for ducted reverse-cycle with zoning and smart controls that older split system installations can't provide.",
    },
},

"burwood": {
    housing: "Burwood is inner west Sydney — 10km from the CBD, under Burwood Council, and with a housing history that reflects the suburb's position as one of Sydney's early tram-serviced residential expansions. The older streets have Federation bungalows and inter-war homes from the 1890s–1930s, and these survive in good numbers around the park precinct and the tree-lined residential streets. Post-war, the suburb went multi-storey faster than most: medium-rise flats from the 1950s–1970s replaced many of the original cottages near the commercial centre, which is why the suburb has a denser feel than you'd expect at 10km from the CBD. More recent apartment development has continued that densification around Burwood station.",
    climate: "Inner west Sydney — maritime temperate. The coastal sea breeze arrives from the north-east in summer and moderates the heat, but Burwood is far enough from the beach that it's warmer than the eastern suburbs on the worst summer days. Winters are mild with the standard Sydney experience. No significant topographic features to create local climate variation.",
    council: "Burwood Council",
    region: "Inner West Sydney",
    tradeNotes: {
        "Building": "The mix of Federation period homes and 1950s–1970s medium-rise flats in Burwood creates a two-speed building market — renovation of period homes in the heritage-listed streets of the residential precinct, and strata maintenance work in the aging apartment blocks near the commercial centre. The Burwood Heritage DCP covers the Federation streetscapes and applies specific external works requirements to HO properties.",
        "Plumbing": "Burwood's older flat stock from the 1950s–1970s has a significant proportion of galvanised iron hot water supply lines that have reached the end of their serviceable life — reduced hot water pressure at upper-floor taps is the typical symptom, and a whole-building copper or PEX re-pipe is standard remediation. The strata management structure means these works require owners corporation approval and coordination across multiple units.",
        "Electrical": "The 1950s–1970s apartment buildings in Burwood regularly have outdated common-area electrical systems and individual unit switchboards with insufficient RCD protection — safety switch compliance in older strata buildings has been a compliance focus in NSW, and the volume of older flat stock in Burwood makes this a consistent electrical workload in the area.",
    },
},
