// =============================================================================
// TRADEREFER CONTENT — BATCH 11
// Suburbs 101–110
// Research-backed, AU-specific content
// =============================================================================

"fadden": {
    housing: "Fadden is one of the quieter Tuggeranong district suburbs — gazetted 1975, built out through the late 1970s and 1980s, and named for Prime Minister Arthur Fadden. The housing is the standard Canberra Tuggeranong era type: ACT Government-built double-brick homes on 600–750 sqm blocks, with the consistent street-naming after Queensland politicians that gives the suburb its particular theme. The suburb population sits around 3,000 — compact, settled, and dominated by owner-occupiers. The Tuggeranong Valley's slopes create some variation in aspect between the hill and valley streets, and the nearby Fadden Hills nature reserve provides bushland adjacency that the flat northern Canberra suburbs lack.",
    climate: "Tuggeranong Valley, southern Canberra — cold in winter by any Australian measure. Frosts from April through October are not unusual; some years Fadden gets snow. The valley topography creates cold air pooling in the lower-lying streets on still winter nights, and the ridge properties are noticeably warmer than the valley floor. Summer is warm and dry with the low humidity that makes Canberra's summer heat actually more comfortable than Sydney's equivalent temperatures.",
    council: "ACT Government",
    region: "Tuggeranong District / Southern Canberra",
    tradeNotes: {
        "Insulation": "Fadden's late 1970s–1980s housing stock was built with the insulation standards of that era — which means essentially no wall insulation and ceiling batts well below current Zone 7 best practice. The ACT Government's Sustainable Household Scheme has driven significant insulation retrofit activity in the Tuggeranong district, and the payback period on ceiling insulation upgrades to R6.0 in Canberra's cold climate is measured in a few heating seasons.",
        "Landscaping": "The combination of cold winters, hot dry summers, and the Canberra water restrictions that periodically apply to the ACT creates demanding conditions for garden establishment. Plant selection in Fadden needs to combine frost hardiness with drought tolerance — the range of plants that tick both boxes is narrower than in coastal cities. The native species of the ACT tablelands are the reliable reference for what will genuinely thrive.",
    },
},

"nerang": {
    housing: "Nerang is the hinterland administrative centre of the Gold Coast — the City of Gold Coast's own headquarters are here, which tells you something about its functional role. The suburb has a long history as a service town for the surrounding dairy and agricultural land, with a proper old township core that predates the Gold Coast's tourist development by decades. The housing stock reflects this layered history: older fibro and timber homes in the original town area, 1970s–1980s brick homes from the suburban expansion phase, and more recent development in the outer residential estates. The Nerang River runs through and creates some valued waterfront properties on its lower reaches.",
    climate: "Gold Coast hinterland — subtropical but more inland than the beachside suburbs. The ocean sea breeze arrives somewhat attenuated here and the summer heat and humidity can be more intense than on the coast. The Nerang River valley creates some local topographic variation. Winters are mild and dry. The hinterland position means storm activity from the Scenic Rim ranges affects Nerang more directly than the coastal strip.",
    council: "City of Gold Coast",
    region: "Gold Coast Hinterland / Inner West Gold Coast",
    tradeNotes: {
        "Building": "Nerang's older housing stock from the 1950s–1980s includes both timber and fibro construction that may contain asbestos in pre-1987 materials — renovations on the original town area homes need asbestos assessment before any work that disturbs wall linings, eaves, or roofing. The waterfront properties on the Nerang River are also subject to the Queensland Development Code's coastal flooding and waterway setback provisions.",
        "Air Conditioning & Heating": "The subtropical Gold Coast climate makes air conditioning a year-round necessity in Nerang's inland position, where the sea breeze relief is less reliable than on the coastal strip. The replacement cycle on the 1990s–2000s split systems in the existing housing stock is active, and the relative affordability of Nerang compared to coastal Gold Coast means a demographic that's price-conscious about running costs.",
        "Landscaping": "The Nerang River corridor has significant riparian vegetation managed by Seqwater and the City of Gold Coast — landscaping near the river reserve requires compliance with the waterway setback requirements, and vegetation near the riverbank should use endemic south-east Queensland species rather than exotics that create weed risk in the river corridor.",
    },
},

"nerrina": {
    housing: "Nerrina is one of the more unusual entries in any outer-suburb list — it's a small, genuinely semi-rural village on the north-eastern fringe of Ballarat, sitting on the slopes of the Brown Hill range. Population just under 1,000 at the 2021 census. The housing here is not suburban in any usual sense: large rural and semi-rural residential blocks with older farmhouses and character homes, some Federation and inter-war cottages in the original settlement area near the pub, and a scatter of contemporary rural residential builds. It straddles the Western Freeway and the residential character on the western side is quite different from the open rural properties to the east. Almost entirely owner-occupied.",
    climate: "Eastern Ballarat fringe — the Brown Hill range elevation creates marginally cooler and wetter conditions than the Ballarat CBD, and the aspect variation between the hillside and valley floor properties is significant. The same cold Ballarat winters apply: frosts from April through September, occasional snow. Summer is warm and clear with good solar exposure on the elevated blocks. The bushland character creates real fire risk on the appropriate wind and humidity combinations.",
    council: "City of Ballarat",
    region: "Eastern Ballarat Fringe",
    tradeNotes: {
        "Building": "The semi-rural residential blocks in Nerrina's eastern fringe have BAL (Bushfire Attack Level) ratings that apply to new construction and significant renovation — the City of Ballarat's bushfire overlay provisions cover the forested and semi-rural areas of the Brown Hill range foothills, and any new build or substantial extension in the rated zone requires compliant materials and setback design.",
        "Landscaping": "The rural character of Nerrina's larger blocks and the adjacent bushland reserves creates real fire risk considerations for landscaping — the Ballarat bushfire planning provisions recommend low-fuel-accumulating species within the asset protection zone adjacent to buildings. The native grassy woodland vegetation of the Ballarat uplands is the ecological reference point for plant selection that's both appropriate and low-risk.",
        "Pest Control": "The bushland adjacency in Nerrina creates subterranean termite pressure that's higher than flat suburban Ballarat — established native eucalyptus in the reserve areas provide ongoing colony habitat, and the Coptotermes species that are common in the Ballarat district are active in the rural residential properties here. Annual inspections on any timber-framed home in this suburb are the appropriate standard.",
    },
},

"fairfield": {
    housing: "Fairfield is south-west Sydney in its most genuinely multicultural form — 30km from the CBD, the administrative centre of Fairfield City Council, and a suburb where over half the residents were born overseas and more than 130 nationalities are represented in the community. The housing stock is 1950s–1980s brick veneer on 550–700 sqm blocks, built for the migrant families who came to work in the manufacturing and services industries of western Sydney in the post-war decades. Vietnamese, Cambodian, and Southeast Asian communities have been dominant since the 1980s and have layered successive waves of modification and adaptation onto the original suburban fabric. It's a working suburb with all the trades work that comes from that.",
    climate: "Western Sydney — the Cumberland Plain suburban climate. Summer is hot and more extreme than coastal Sydney, with the heat island effect from the density and the flat plains amplifying the temperature on heatwave days. The western Sydney heat that's been making news is real: 40°C+ days happen here when the coastal suburbs are at 30°C. The Prospect Reservoir to the north provides a small green buffer. Winters are cooler and drier than the coast.",
    council: "Fairfield City Council",
    region: "South-West Sydney / Fairfield City",
    tradeNotes: {
        "Air Conditioning & Heating": "Western Sydney's heat extremes make cooling a genuine health and safety necessity in Fairfield, not a comfort item. The 1950s–1980s brick homes in the suburb have thermal mass which helps with night cooling if the windows are managed, but reverse-cycle split systems are the dominant demand here. The replacement cycle on the 1990s–2000s systems is active and price sensitivity in this market is real.",
        "Building": "Fairfield's housing stock has been modified extensively by successive owner generations — additions, conversions, granny flats, and expanded kitchens are common on the original three-bedroom brick homes. The NSW Government's low-income housing grants and the affordable housing programs that target western Sydney create some specific procurement requirements for renovation work in parts of the suburb.",
        "Electrical": "The 1950s–1970s housing stock in Fairfield has the standard south-western Sydney electrical profile — ceramic fuse boards and original wiring in the least-modified homes, with piecemeal additions that have created compliance gaps. RCD installation requirements under the NSW electrical safety regulations are a consistent workload in the older stock.",
    },
},

"helensvale": {
    housing: "Helensvale is northern Gold Coast at its most characteristic — a suburb designed in the 1970s around a curving park and the golf course, 8km inland from the coast on the Coomera River plain. The original residential development from 1974 built standard brick and Hardiplank homes through the 1970s and 1980s; the school infrastructure (primary 1984, secondary 1990, shopping centre 1991) then cemented it as a genuine community. The canal estate in the north of the suburb, with boat access to the Coomera River and Saltwater Creek, adds a premium waterfront tier. Theme Park Drive runs through the western edge — Sea World, Dreamworld, and Movie World are all in the vicinity, which defines Helensvale's geographic context as much as anything.",
    climate: "Northern Gold Coast, inland — subtropical, warm and humid in the summer storm season, mild and dry in winter. The proximity to the Coomera River and its tributaries creates some local humidity variation, and the canal estate properties have genuine water proximity that moderates summer temperatures slightly. The open plains between Helensvale and the northern Gold Coast hinterland allow for significant wind events during Queensland's summer storm season.",
    council: "City of Gold Coast",
    region: "Northern Gold Coast",
    tradeNotes: {
        "Roofing": "The canal estate properties in Helensvale's northern precinct have direct water exposure and the salt air from the Coomera estuary and Broadwater complex affects roofing material longevity — standard Colorbond performs adequately on the inland streets, but the waterfront canal properties should be specified to coastal-rated product. The 1970s–1980s Hardiplank and fibro homes in the original estate areas require asbestos assessment before any roof work that disturbs the eave or fascia materials.",
        "Air Conditioning & Heating": "The subtropical Gold Coast climate means air conditioning runs for nine months of the year in Helensvale — the 1980s–1990s systems in the original housing stock are well past their efficient operating life and the replacement market here is active. The canal estate properties with water views and north-east orientation get better natural cross-ventilation than the inland streets, but still require mechanical cooling for the wet season months.",
        "Building": "The canal estate properties in northern Helensvale are subject to the City of Gold Coast's waterway and canal setback provisions — any building works, jetty extensions, or significant modifications near the waterfront require the relevant QDA assessment and compliance with the Queensland Development Code's waterway building requirements.",
    },
},

"balaclava": {
    housing: "Balaclava is a small, distinctive inner-south Melbourne suburb — 7km from the CBD, in the City of Port Phillip, and bounded by St Kilda, Elwood, and St Kilda East. The housing is overwhelmingly Victorian and Edwardian: dense terrace rows from the 1870s–1900s, single-fronted cottages, and the occasional grander Victorian villa on the wider streets. The suburb has a well-known Jewish community history that goes back to the early 20th century. Gentrification here was complete a long time ago — the terrace houses and cottages that were cheap rental stock in the 1980s are now million-dollar-plus homes. The Carlisle Street commercial strip cuts through the centre.",
    climate: "Inner south Melbourne, bay proximity — Port Phillip Bay sea breeze arrives reliably in summer, keeping the suburb noticeably cooler than the northern and western suburbs on the worst heat days. The built density of the terrace housing keeps the street-level temperatures slightly elevated compared to the more garden-oriented suburbs. Winters are cool with the characteristic Melbourne south-westerly dominance off the bay.",
    council: "City of Port Phillip",
    region: "Inner South Melbourne / Port Phillip",
    tradeNotes: {
        "Building": "Balaclava's Victorian and Edwardian terrace stock sits inside Port Phillip City Council's Heritage Overlay in the majority of the residential streets — external works on the terrace rows and cottages require heritage permit assessment, and Port Phillip's heritage team is active. The heritage-sensitive renovation market here is mature and well-served by builders who specialise in period terrace work.",
        "Plumbing": "The very old terrace housing in Balaclava — some 120+ years old — carries the plumbing legacy of that age: lead service pipes are found in the oldest and least-renovated homes, original cast iron drainage is common, and the narrow terrace footprints create access challenges that don't exist in freestanding homes. A scoped plumbing replacement in a Balaclava terrace is a materially different scope from the same work in a 1960s brick veneer.",
        "Painting": "The rendered masonry facades on Balaclava's Victorian terrace rows require breathable coating systems to prevent moisture trapping in the lime render — the use of impermeable modern acrylic on Victorian lime render without proper surface preparation assessment is a regular cause of paint failure and moisture damage in these properties. Lead-based paint assessment is standard pre-renovation procedure on any pre-1960 terrace.",
    },
},

"delacombe": {
    housing: "Delacombe is the south-west Ballarat growth suburb — on the rural-urban fringe, fast-growing, and part of the Ballarat West Growth Area where the City of Ballarat and State Government have been directing residential development. The suburb's population grew 85% in the decade to 2021 and development is still running. The housing is essentially all 2000s–2020s: brick and lightweight steel frame homes on 350–500 sqm lots, standard format growth area residential with a consistent age profile. The Big Housing Build program is adding 181 homes including social and affordable housing to the mix. A genuine suburb-in-formation.",
    climate: "Western Ballarat — the same genuinely cold continental climate that makes Ballarat distinctive. Winter frosts are consistent, occasional snow events happen, and the heating demand is real. The south-west position on the open plains west of the Ballarat urban core means exposure to the western plains wind on the worst winter days. Summer is warm and the new estates with minimal tree canopy experience the same sun exposure issues as any new greenfield development.",
    council: "City of Ballarat",
    region: "Western Ballarat Growth Area",
    tradeNotes: {
        "Insulation": "Delacombe's new housing stock, while built to more recent NCC energy standards than the older Ballarat suburbs, benefits from ceiling insulation upgrades to best-practice R6.0 levels given the genuinely cold Zone 7 climate. The affordable end of the new housing market in Delacombe is often built to the minimum code requirements, and the heating bills in Ballarat winters make the cost-benefit of insulation upgrades very clear.",
        "Landscaping": "Brand-new Delacombe estates are in the same raw soil condition as any greenfield growth area — construction-stripped and compacted, low organic matter, and dominated by reactive Ballarat clay on much of the development area. Garden establishment requires soil remediation, and the cold Ballarat winters with their frost cycle create specific challenges for plant establishment timing and species selection.",
        "Building": "Delacombe is one of Ballarat's most active new construction markets — the City of Ballarat's Ballarat West Growth Area PSP governs the development sequencing, and builders here need to be familiar with the infrastructure contribution requirements and the lot-specific covenant conditions that apply to the estate developments. The social and affordable housing component of the Big Housing Build program also creates public housing procurement pathways that differ from standard residential.",
    },
},

"leopold": {
    housing: "Leopold is on the east side of Geelong, 10km from the city centre, and has been filling out steadily for two decades as the Bellarine Peninsula's affordability has attracted Geelong workers and Melbourne commuters who can't afford the western side of the bay. The housing stock is predominantly 1990s–2010s brick veneer on 500–650 sqm blocks, with newer development in the current estate areas. The Gateway Plaza shopping centre, opened in the early 2000s, anchored the suburb as a genuine community rather than just a residential overspill. Lake Connewarre's southern edge and the Bellarine Rail Trail provide natural amenity that makes Leopold genuinely pleasant rather than just cheap.",
    climate: "Eastern Greater Geelong, Lake Connewarre proximity — the lake and the Barwon River mouth nearby create some local humidity and moderate the summer heat. The south-eastern aspect towards the Bass Strait means some southerly exposure in the colder months. Summer is warm and the prevailing afternoon sea breeze off the bay arrives reliably. The Bellarine Peninsula position generally means more moderate conditions than the open western plains of Greater Geelong.",
    council: "City of Greater Geelong",
    region: "Eastern Greater Geelong / Bellarine",
    tradeNotes: {
        "Solar & Energy": "Leopold's demographic profile — young families, affordability-driven buyers — creates strong solar demand, and the east Geelong sunshine hours and roof orientations are well-suited to rooftop generation. The 1990s–2000s homes are good candidates for solar and insulation retrofit given their original energy standards, and the growing awareness of energy costs in the Geelong region makes the economics straightforward.",
        "Landscaping": "The basalt plains clay soils of the eastern Geelong corridor underlie most of Leopold's residential area — reactive, slow-draining in wet weather, and creating the shrink-swell cycle that challenges driveways, paths, and garden beds. Plant selection needs to account for the seasonal waterlogging in winter and the dry clay cracking in summer. The Lake Connewarre conservation zone to the south creates biodiversity obligations for properties on the lake edge.",
        "Roofing": "Leopold's 1990s–2000s concrete tile roofs are reaching the 25–35 year age range where sealer coat loss and minor ridge pointing issues are becoming widespread — this is the standard maintenance cycle for that era's housing stock, and the volume of same-age roofs in Leopold makes it a consistent demand market.",
    },
},

"mudgeeraba": {
    housing: "Mudgeeraba is the Gold Coast hinterland at its most genuinely village-like — a 19th century settlement 8km west of Burleigh Heads that's managed to retain real rural character despite being fully within the Gold Coast municipality. The original village core has older timber and fibro homes from the early-mid 20th century. Out from the centre, the residential character shifts to large semi-rural blocks from 2,000 sqm to multi-hectare rural residential, with older-style Queenslander homes and contemporary rural builds sharing the landscape. The Mudgeeraba Creek runs through and the Hinterland scenic backdrop is the selling point. It's not a suburb for apartment living.",
    climate: "Gold Coast hinterland — subtropical but at elevation and inland, with more weather variability than the coastal strip. The Scenic Rim ranges to the west create orographic rainfall and the summer storm season here can be dramatic. The Mudgeeraba Creek valley can experience significant rainfall events. Summer is warm and humid; winter is mild. The inland elevation provides slightly cooler nights than coastal Gold Coast, which is part of the rural lifestyle appeal.",
    council: "City of Gold Coast",
    region: "Gold Coast Hinterland",
    tradeNotes: {
        "Building": "The rural residential properties in Mudgeeraba on larger blocks within the Scenic Rim interface have BAL ratings in some zones — fire management in the rural hinterland is a genuine requirement, and the City of Gold Coast's bushfire planning provisions apply to the forested and semi-rural areas adjacent to the hinterland conservation zones. Any new construction or significant extension in these areas requires a bushfire management overlay assessment.",
        "Landscaping": "Mudgeeraba's semi-rural blocks and the Mudgeeraba Creek corridor create genuine biodiversity value — the subtropical hinterland ecology here includes significant remnant rainforest and open forest that the City of Gold Coast's vegetation management overlays protect. Large-scale earthworks or vegetation clearing on rural blocks requires council assessment under the relevant biodiversity policies.",
        "Pest Control": "The tropical/subtropical climate of the Gold Coast hinterland and Mudgeeraba's semi-rural character with abundant native timber and lush creek vegetation creates termite conditions that are among the more demanding in south-east Queensland. Both Coptotermes and Nasutitermes species are active in this area, and the large older timber homes on the rural blocks have significant exposure. Annual inspections and physical or chemical barrier maintenance are the appropriate standard.",
    },
},

"surry-hills": {
    housing: "Surry Hills is inner Sydney's most complete Victorian terrace suburb — immediately south-east of the CBD, in the City of Sydney, and with a housing stock that was built almost entirely between 1850 and 1910 to house the workers employed in the nearby factories and warehouses. The single-fronted terrace rows are the defining character type: two-storey brick terraces with iron lacework, tight to the footpath, dense and urban. There are also workers' cottages, and along the southern edges some grander double-fronted Victorian villas. Gentrification turned this formerly working-class area into one of Sydney's most expensive inner suburbs over a period from about 1985 to 2010. Now it's the creative industries suburb of choice — agencies, studios, studios above agencies — and the terraces are worth more than most regional Australian towns.",
    climate: "Inner east Sydney — the Botany Bay sea breeze and the easterly off the Pacific keep summer temperatures significantly cooler than western Sydney, and the CBD density creates some urban heat effect but nothing like the western suburbs. Winter is mild, much milder than Melbourne's equivalent distance from the CBD. The density of terrace housing creates interesting microclimates — the north-facing back gardens are warm and sheltered; the south-facing street frontages can be in shade for most of winter.",
    council: "City of Sydney",
    region: "Inner East Sydney / City of Sydney",
    tradeNotes: {
        "Building": "Surry Hills' Victorian terrace rows are in the City of Sydney's heritage conservation areas — almost every pre-war building in the suburb is covered by some level of heritage protection, and external alterations require council assessment under the City of Sydney Heritage DCP. The Council's heritage team is thorough and the approval process for terrace renovations is more detailed than standard DA processes. Federation, Victorian, and Edwardian character elements on street-facing facades are specifically protected.",
        "Plumbing": "The 1850s–1910s terrace stock in Surry Hills carries the expected plumbing history: lead supply pipes in the earliest homes, galvanised iron hot water lines in the mid-century renovations, and cast iron drainage that's well past its engineering life in many instances. The narrow terrace footprints make access challenging and re-pipe works are time-consuming projects here compared to freestanding homes.",
        "Electrical": "The very old terrace housing in Surry Hills creates a consistent electrical upgrade market — original wiring from 1960s–1970s renovations that updated pre-war fabric is now itself outdated, and the combination of high rental proportions and heritage overlay requirements creates a specific compliance and restoration challenge for electricians working in this suburb.",
    },
},
