// =============================================================================
// TRADEREFER CONTENT — BATCH 09
// Suburbs 81–90
// Research-backed, AU-specific content
// =============================================================================

"clarkson": {
    housing: "Clarkson is Perth's northern corridor doing what the northern corridor does — fast, flat, and consistent. The suburb sits 34km north of the Perth CBD in the City of Wanneroo, and the residential buildout here happened primarily in the 1990s and 2000s as the Mitchell Freeway extended north and the Clarkson railway station opened in 2004. That transport infrastructure unlocked the suburb and the housing that went up in response is almost entirely from that era: brick veneer and rendered double-brick on 400–500 sqm blocks in the Somerly estate and the surrounding streets. The Catalina development on the northern edge is still adding 2,500 homes. It's a suburb that grew quickly and is still growing.",
    climate: "Northern Perth coastal — the Indian Ocean is about 2km west and the coastal sea breeze moderates the summer heat noticeably compared to the flat eastern suburbs at equivalent latitude. Perth summers are hot but the afternoon Fremantle Doctor usually arrives by mid-afternoon and drops the temperature. The northern coastal location means the salt air influence from the ocean is measurable on the more exposed western streets.",
    council: "City of Wanneroo",
    region: "Northern Coastal Perth / Wanneroo",
    tradeNotes: {
        "Solar & Energy": "Perth has Australia's highest rooftop solar saturation rate and Clarkson's single-storey brick veneer homes on good north-facing lots are well-suited to rooftop generation. The hot dry summer climate and the relatively high electricity costs in WA make the economics clear. Battery storage uptake in the outer northern suburbs has been growing quickly as the grid curtailment policies around midday solar export have made storage more attractive.",
        "Landscaping": "The sandy coastal plain soils that underlie most of Perth's northern corridor drain very quickly — Clarkson gardens need irrigation design that accounts for the low water-holding capacity of the native sand, and organic amendment is essential before garden establishment. The City of Wanneroo's water-wise garden guidelines are more than just good practice here; the Water Corporation's restrictions are real and the sandy soils make water efficiency genuinely critical.",
        "Roofing": "The proximity to the Indian Ocean creates a moderately corrosive coastal environment for roofing — the 1990s–2000s homes on the more exposed western streets are at the age where re-coating or re-roofing is becoming relevant, and the coastal exposure accelerates weathering compared to inland Perth suburbs at the same age.",
    },
},

"holden-hill": {
    housing: "Holden Hill is north-east inner Adelaide — named for the landholder Halden, confusingly spelt Holden — and the suburb sits partly in the City of Tea Tree Gully and partly in Port Adelaide Enfield, which creates a slightly split administrative character. The housing stock built up primarily in the 1960s and 1970s, when the north-east Adelaide corridor was expanding rapidly. What you get is largely 1960s–1970s brick veneer on 600–700 sqm blocks, honest suburban Adelaide from that era, three bedroom home on a flat block with a decent backyard. Some earlier post-war homes exist on the streets closest to the original road alignments. It's the kind of suburb where successive generations of maintenance and renovation have been layering onto the original 1960s fabric.",
    climate: "Inner north-east Adelaide — the full SA Mediterranean experience, but the inland position means it runs a couple of degrees hotter than coastal suburbs on the worst summer days. The northern plains wind in heatwave conditions (the 'burner' from the north) is unimpeded out here. Winter is mild and mostly dry with the reliable August rainfall that characterises Adelaide. The slightly elevated position of the north-east suburbs provides some relief on summer nights.",
    council: "City of Tea Tree Gully",
    region: "Inner North-East Adelaide",
    tradeNotes: {
        "Building": "The 1960s–1970s brick homes in Holden Hill are the standard South Australian cavity brick or double brick of that era — solid but creating specific challenges for renovation, including limited routing options for services and the need to detail extensions carefully to avoid differential movement at the junction of old and new. Cavity brick insulation retrofit is a relevant upgrade category here given the hot Adelaide summers.",
        "Air Conditioning & Heating": "Adelaide's hot summers and the north-east Adelaide's slightly elevated heat exposure compared to coastal suburbs make reverse-cycle split systems the dominant demand in Holden Hill's older housing stock. The 1980s and early 1990s ducted systems that were common upgrades in this era are now reaching end of life and the replacement market is active.",
        "Roofing": "The 1960s–1970s concrete tile roofs across most of Holden Hill are in the 50–60 year zone where sealer coat loss, minor cracking, and failed ridge pointing is widespread. The north-east facing slopes get significant UV loading in the Adelaide summer and deterioration is faster than in sheltered or coastal locations.",
    },
},

"blackwood": {
    housing: "Blackwood is Adelaide Hills commuter country done properly — 13km south-east of the CBD, in the City of Mitcham, and the suburb has a character that's quite different from the flat inner Adelaide grid. The first railway station in the Adelaide Hills was built at Blackwood in 1883, and the suburb grew from that point with a genuinely diverse housing stock: Victorian-era bungalows and modest cottages from the 1880s–1900s, Federation and inter-war development in the 1910s–1930s, post-war brick further out, and 1960s–1980s suburban infill on the remaining blocks. The tree canopy is mature and substantial. Proximity to Flinders University has added a renter demographic in the past few decades.",
    climate: "Adelaide Hills foothills — meaningfully cooler, wetter, and more variable than the flat city below. Summer days in Blackwood are several degrees cooler than the CBD on hot northerlies, and the bush canopy moderates the temperature further. But the proximity to the Adelaide Hills also means fire weather is a serious seasonal consideration — the Blackwood area sits within the High fire risk zone and northerly wind plus low humidity creates BAL-relevant conditions. Winter is cooler and wetter than Adelaide city.",
    council: "City of Mitcham",
    region: "Adelaide Hills Foothills / Mitcham",
    tradeNotes: {
        "Building": "Blackwood's position in the Adelaide Hills fire zone means BAL assessments are required for new construction and significant extensions on many properties — the Mitcham Hills planning zone has specific bushfire provisions and the AS 3959 material requirements for BAL-rated buildings affect window glazing, decking materials, and cladding specifications in ways that add meaningful cost to builds that would be straightforward on flat suburban Adelaide blocks.",
        "Landscaping": "Blackwood's mature tree canopy and the City of Mitcham's vegetation protection policies are actively applied in the hills area — significant tree removal near protected species and within the urban forest overlay requires council approval. The fire risk zoning also means that low-fuel-accumulating species in the landscape near the house are not just aesthetic preference but a genuine risk management measure.",
        "Roofing": "The older housing stock in Blackwood from the 1880s through the 1930s includes genuine historic construction — corrugated galvanised iron on timber framing in many cases, and some of the original Federation homes have roofing details that require conservation-aware repair rather than replacement. The Mitcham heritage provisions are relevant for any work on listed properties.",
    },
},

"coorparoo": {
    housing: "Coorparoo is inner south-east Brisbane — about 4km from the CBD — and one of Brisbane's more characterful established suburbs. The defining housing type is the Queenslander: elevated timber homes with corrugated iron roofs, wrap-around verandahs, and the cross-ventilation design that made subtropical living bearable before air conditioning. The original Queenslanders from the 1900s–1930s fill the older streets, with post-war brick homes from the 1940s–1960s on the later subdivisions. The suburb has been gentrifying steadily for twenty years and a significant apartment overlay has developed around the shopping strip and along the main road corridors. The heritage Queenslanders on the better streets have been renovated and extended by successive waves of homeowners.",
    climate: "Subtropical Brisbane inner south-east — warm and humid year-round, with the classic Brisbane summer of daily afternoon storms from November through March. The slightly elevated topography of Coorparoo catches the afternoon sea breeze off Moreton Bay reliably, which historically made the elevated Queenslanders noticeably cooler than valley floor properties. Winter is genuinely mild — night minimums around 10–12°C — which is the specific selling point of the Brisbane lifestyle.",
    council: "Brisbane City Council",
    region: "Inner South-East Brisbane",
    tradeNotes: {
        "Building": "Coorparoo's heritage Queenslanders require builders with specific timber frame renovation skills — the construction principles of raised timber homes on stumps, with a reliance on cross-ventilation rather than insulation, creates different engineering and construction demands than the brick veneer suburban houses that dominate most Australian city renovation markets. House restumping, underpinning, subfloor framing repair, and the detailing of additions to period Queenslanders are specialist skills.",
        "Pest Control": "Raised timber Queenslanders are among the most termite-vulnerable building types in Australia — the combination of exposed subfloor timber, Brisbane's warm humid climate, and the garden soils around the Queenslander gardens creates excellent habitat for Coptotermes species. Annual inspections and AS 3660.1-compliant subfloor barriers (chemical reapplication or physical barrier maintenance) are essential in this suburb.",
        "Roofing": "Coorparoo's original Queenslander corrugated iron roofing on the 1900s–1930s homes is often being replaced in the current renovation wave — the older corrugated iron has typically lasted well but restoration-quality re-roofing requires matching the profile and pitch of the original to maintain heritage character, and Coorparoo's Brisbane City Council heritage overlay provisions apply to the streetscape-significant homes.",
    },
},

"ascot-vale": {
    housing: "Ascot Vale is inner Melbourne on the western fringe of the CBD's orbit — 6km out, in Moonee Valley, and with a housing stock that mixes genuine Victorian and Edwardian working class history with later infill. The suburb developed primarily from the 1880s through the 1920s, built for the workers employed in the nearby abbatoirs, the quarry, and the rail infrastructure of the western suburbs. Single-fronted Victorian cottages and Edwardian bungalows are the character-defining types on the older streets. Post-war, the Ascot Vale public housing estate off Chelsworth Park was built by the Housing Commission — now being renewed through a major redevelopment — and this has added a distinct social housing precinct to what's otherwise a market housing suburb.",
    climate: "Western inner Melbourne — the Maribyrnong River to the west and Moonee Ponds Creek to the east create riparian corridors that provide some local cooling, but this is still western Melbourne and the summer heat when the northerly comes in is real. The sea breeze from Port Phillip Bay takes longer to arrive here than in the inner south-east suburbs. Winters are cool with the classic Melbourne overcast.",
    council: "City of Moonee Valley",
    region: "Inner North-West Melbourne / Moonee Valley",
    tradeNotes: {
        "Building": "The Victorian and Edwardian housing stock in Ascot Vale's older streets sits inside Moonee Valley's Heritage Overlay provisions — external works on listed properties require permit assessment, and the single-fronted terrace and cottage character is particularly well preserved in the streets closest to the Maribyrnong. The Ascot Vale Public Housing Estate renewal is also driving significant building activity in the social housing precinct.",
        "Electrical": "The older terrace and cottage stock in Ascot Vale's pre-1940 streets frequently has early-generation wiring — TPS or even older cloth-insulated wiring is encountered in the least-touched properties. The high rental proportion in the area means safety upgrade work on switchboards and RCD installations is a consistent electrical trade demand.",
        "Landscaping": "The Maribyrnong River corridor and the Moonee Ponds Creek provide ecological context for the suburb's tree canopy, and Moonee Valley's significant tree protections apply to the established river red gum and river corridor vegetation. Garden renovation near the creek banks requires care around the riparian management zones.",
    },
},

"bulleen": {
    housing: "Bulleen occupies a bend in the Yarra River in Melbourne's inner north-east — 12km from the CBD, in the City of Manningham, and the suburb built out primarily through the 1950s to 1970s on land that had been dairy farms until the war. The dominant housing type is 1960s–1970s brick veneer on 600–800 sqm blocks, decent quality for the era, with generous gardens on the Yarra-adjacent streets. The Banyule Flats and Yarra corridor run along the northern edge and give the suburb genuine river access. More recently, the suburb has seen townhouse infill development as Manningham's densification strategy targets the shopping and activity centre areas.",
    climate: "Inner north-east Melbourne — the Yarra valley creates a slight temperature moderation compared to the flat northern suburbs. Summers are warm but the river corridor provides measurable cooling on the adjacent properties. Winters are cold and the valley topography can pool cold air in the lower streets on still nights. The Koonung Creek tributary adds an additional green corridor through the southern part of the suburb.",
    council: "City of Manningham",
    region: "Inner North-East Melbourne / Manningham",
    tradeNotes: {
        "Landscaping": "Bulleen's position on the Yarra River bend creates significant biodiversity obligations — the Banyule Flats are managed by Parks Victoria and the riparian vegetation along the Yarra corridor is subject to Melbourne Water's waterway management requirements. Landscaping near the river reserve must use indigenous species and comply with the relevant riparian vegetation management plan. The established river red gum canopy is protected.",
        "Building": "Manningham has been actively pursuing medium-density development along Bulleen Road and the neighbourhood activity centres, which means builders here work in the transition zone between 1960s–1970s single residential blocks and the newer medium-density provisions. The Manningham planning scheme's Design and Development Overlay applies to sensitive areas and heritage property assessments are relevant for the older streetscapes.",
        "Concreting": "The dark basalt clay soils that characterise the Yarra's east bank in Bulleen are reactive — the shrink-swell cycle creates driveway and path movement that's a consistent complaint in the 1960s–1970s housing stock where original concrete is now 50–60 years old. Replacement work requires proper joint design and sub-base compaction to avoid repeating the same cracking in ten years.",
    },
},

"chifley": {
    housing: "Chifley is one of Canberra's Woden Valley suburbs, gazetted in 1966 and built out in the late 1960s and 1970s as part of the ACT Government's planned suburban expansion south of the Molonglo River. The housing stock is almost entirely from that era: ACT Government-built double brick homes on 600–800 sqm blocks, the standard Canberra suburban pattern, with a significant proportion of the original stock still in first or second ownership. There's a public housing component in the older estate streets that reflects the era's approach to providing worker housing near the Woden commercial centre. Chifley is a quiet, settled suburb that hasn't been significantly redeveloped.",
    climate: "Woden Valley, southern Canberra — the ACT continental climate applies in full. Cold winters with consistent frosts from April through September, occasional snow. Warm to hot and dry summers. The Woden Valley position is somewhat sheltered from the Monaro wind channel that affects the more exposed outer suburbs, but winter temperatures are still genuinely cold. The nearby Tuggeranong Parkway corridor creates some wind channelling.",
    council: "ACT Government",
    region: "Woden Valley / Southern Canberra",
    tradeNotes: {
        "Insulation": "Chifley's late 1960s–1970s double brick homes were built with minimal insulation by current standards — the ACT's cold winters and the age profile of this suburb mean insulation upgrades are one of the highest-ROI improvements available. The ACT Sustainable Household Scheme has specifically targeted Woden Valley suburbs with insulation rebates, and the combination of ceiling insulation upgrade and secondary glazing on the original timber-framed windows is the standard package.",
        "Building": "The ACT Government's medium-density housing targets have flagged Chifley's proximity to the Woden Town Centre as a future densification opportunity — while the suburb remains predominantly low-density residential, builders here should be aware that the planning context is changing and that any significant renovation needs to consider the emerging medium-density provisions that apply around the Woden precinct.",
        "Electrical": "The late 1960s–1970s housing stock in Chifley has the standard older ACT switchboard profile — fusewire boards or early circuit breakers without RCD protection are common in the least-renovated homes. The ACT Energy Efficiency Improvement Scheme has driven safety switch installation uptake, but there are still older properties that haven't had a switchboard update.",
    },
},

"moonah": {
    housing: "Moonah is Hobart's most immediate working-class northern suburb — 5km from the CBD, part of the City of Glenorchy, and the housing reflects the industrial history that defined the area for most of the 20th century. Weatherboard homes from the 1900s through the 1940s are the character stock on the older streets — solid timber construction, modest in scale, and honest in their origins as workers' housing for the nearby industrial zone along Charles Street. Post-war brick homes filled in the gaps through the 1950s–1970s. The suburb has been gentrifying slowly as proximity to the CBD makes the affordable Moonah weatherboards attractive to a new demographic, and some renovation activity is visible on the streets closest to the Newtown Road corridor.",
    climate: "Northern Hobart, Derwent valley — the river is nearby but not immediately adjacent here. Moonah gets the standard Glenorchy climate: cold winters with frosts in the valley floor areas, mild summers, and the general Hobart pattern of frequent westerly cloud cover in winter. The sheltering effect of Mount Wellington to the south moderates the worst of the southwesterlies compared to the more exposed southern Hobart suburbs.",
    council: "City of Glenorchy",
    region: "Northern Hobart / Glenorchy",
    tradeNotes: {
        "Building": "The weatherboard housing stock in Moonah's older streets has a significant asbestos-containing materials exposure risk — pre-1987 fibrous cement lining, eaves, and sub-floor work contains asbestos in many homes that haven't been fully renovated. Safe Work Tasmania regulations require identification and management of asbestos before any renovation scope that disturbs these materials. The weatherboard cladding itself may also be asbestos-cement on the post-1930s homes.",
        "Insulation": "Moonah's working-class housing stock is among the least well-insulated in Hobart — Zone 7 conditions apply and the original weatherboard and fibro homes have essentially no meaningful ceiling or wall insulation in their original state. Ceiling insulation upgrades to R5.0 and sub-floor batts on the elevated timber frame homes provide the most significant thermal improvement, and the Tasmanian government's Energy Saver program has specifically targeted this type of housing.",
        "Roofing": "The older corrugated iron and Marseille tile roofing on Moonah's pre-1960s housing stock is often well past its service life — the combination of cold wet Hobart winters and the valley humidity creates ideal conditions for roof deterioration. Re-roofing demand in Moonah is consistent and the heritage character homes near the Newtown Road precinct have specific material requirements for conservation-aware replacement work.",
    },
},

"ashburton": {
    housing: "Ashburton is inner south-east Melbourne's quieter and perhaps more genuinely suburban counterpart to the prestige suburbs around it — 12km from the CBD in the City of Boroondara, and with a housing stock that's predominantly inter-war. The Tower Hill Estate precinct, a highly intact collection of inter-war California bungalows and English cottage-style homes from the 1920s–1940s, is a genuine heritage asset and is recognised in the Boroondara Heritage Overlay. The rest of the suburb fills in with post-war brick veneer from the 1950s–1960s, and the more recent infill townhouses that have been appearing as older blocks are subdivided. The Gardiners Creek corridor runs through the northern edge.",
    climate: "Inner south-east Melbourne — Port Phillip Bay sea breeze moderating influence is felt here in summer, though Ashburton is far enough from the bay that the worst heat events are still quite hot. The Gardiners Creek provides a linear cool green corridor. The established tree canopy in the Tower Hill Estate precinct and the surrounding residential streets provides meaningful temperature moderation on summer days.",
    council: "City of Boroondara",
    region: "Inner South-East Melbourne / Boroondara",
    tradeNotes: {
        "Building": "The Tower Hill Estate Precinct in Ashburton is covered by Boroondara's Heritage Overlay and the City of Boroondara's heritage guidelines apply to external alterations on the inter-war homes in the precinct. Boroondara is one of Melbourne's most heritage-active councils and the HO assessment process for period homes here requires heritage design expertise. The precinct's significance is at a citywide level, not just local.",
        "Landscaping": "Ashburton's established garden suburbs have mature tree coverage that's protected under Boroondara's Significant Tree Register — tree removal applications are carefully assessed and the council's vegetation protection is actively applied. The Gardiners Creek corridor is managed by Melbourne Water and riparian landscaping near the creek requires consultation with the waterway management requirements.",
        "Roofing": "The inter-war housing stock in the Tower Hill Estate has in many cases original terracotta or concrete Marseille tile roofing from the 1920s–1940s — now 80–100 years old, the tiles themselves are often still structurally sound but the bedding and pointing has failed comprehensively, and valley flashings have typically corroded through. Conservation-appropriate re-bedding and re-pointing rather than replacement is the preferred approach on heritage-listed properties.",
    },
},

"darwin-cbd": {
    housing: "Darwin CBD is the tropical Australian city centre that Cyclone Tracy remade — the Category 4 cyclone on Christmas Day 1974 destroyed the majority of the built fabric of central Darwin and what exists today is almost entirely post-1975. The waterfront precinct at Darwin Harbour has been developed over the last 20 years with high-rise apartment towers and the convention centre, and the Smith Street Mall area has residential apartments above commercial ground floors. Residential in the strict CBD sense exists primarily in the waterfront towers and the scattered mixed-use buildings on the fringe streets. Government housing was the dominant residential form in the 1970s–1980s rebuild; now it's the premium waterfront apartments and short-stay stock.",
    climate: "Tropical monsoon — the most demanding climate for buildings and trade work in Australia. The wet season November through April brings extraordinary humidity, torrential monsoonal rain, and cyclone risk. The dry season May through October is magnificent but the UV intensity is extreme year-round. The harbour location and the sea breeze moderate the heat in the CBD somewhat compared to the flat inland areas, but make no mistake — this is genuinely tropical and every building material is tested by the environment.",
    council: "City of Darwin",
    region: "Darwin CBD / Waterfront Precinct",
    tradeNotes: {
        "Building": "All construction in Darwin CBD must comply with the NCC's cyclone wind loading provisions, which require significantly more robust structural connections, roof tie-down design, and window glazing specifications than southern Australian builds. The NT Building Act's cyclone compliance pathway requires engineering certification of structural adequacy, and the premium waterfront tower developments require high-rise specific builder licensing. The post-Tracy building standards are genuine and enforced.",
        "Air Conditioning & Heating": "Darwin CBD apartments are fully dependent on air conditioning from approximately October through May — the wet season's humidity makes natural ventilation inadequate and the cooling load on these buildings is year-round rather than seasonal. Centralised HVAC systems in the waterfront towers require specialist maintenance, and individual split system maintenance in the smaller residential buildings sees the same accelerated corrosion of condenser units from the salt-laden marine air that affects all coastal Darwin properties.",
        "Electrical": "The Darwin CBD's high-rise apartment and commercial building mix creates a demand for commercial electrical contractors with high-rise building systems experience — BMS maintenance, emergency lighting compliance under AS 2293, and the specific requirements of Buildings in Tropical Zone 1 create compliance obligations that differ from the standard residential electrical work that dominates the southern states.",
    },
},
