// SUBURB_CONTEXT entries — Batch 14 (suburbs 131–140)
// Suburbs: miranda, mount-barker, north-sydney, robina, ryde,
//          balwyn-north, blackburn-south, carindale, carlisle, millner

export const SUBURB_CONTEXT_BATCH_14 = {

  "miranda": {
    housing: "Miranda is the commercial and residential hub of Sydney's Sutherland Shire, about 22km south of the CBD. The housing stock is a mix — some 1960s-70s brick veneer family homes surviving in the quieter residential streets, but increasingly overtaken by medium-density apartment development as the Westfield Miranda precinct drives infill. The Low-to-Mid Rise policy has identified capacity for nearly 5,000 new apartments within 800m of the Miranda centre, which means the suburb is in the middle of a significant character transition.",
    climate: "Southern Sydney climate with some coastal moderation. Warm humid summers, rarely the extreme heat of the western suburbs — days in the mid-to-high 20s are the norm, occasionally pushing to 33-35°C on westerly wind days. Winters mild and comfortable, overnight lows around 8-10°C. Annual rainfall around 1300mm. The Shire's topography can concentrate heavy rainfall into localised flooding in some sections.",
    council: "Sutherland Shire Council",
    region: "Sutherland Shire Sydney",
    tradeNotes: {
      "Electricians": "The combination of ageing 1960s-70s housing stock and the new apartment development wave around Miranda Centre keeps electricians busy on two very different types of work. Switchboard upgrades and safety switch compliance on older homes, and new multi-dwelling fit-outs and common property electrical systems in the newer apartment buildings. It's genuinely two separate markets in close proximity.",
      "Plumbers": "Older Miranda housing has the predictable galvanised and early copper pipe issues as it pushes 50-60 years. The apartment development around Westfield creates demand for hydraulic consultants and licensed plumbers for commercial and residential mixed-use fit-outs. The Shire's drainage infrastructure near the low-lying sections of the suburb has an ongoing maintenance load.",
      "Builders": "Sutherland Shire Council's DCP provisions are being actively tested by the NSW Government's Low-to-Mid Rise housing reforms around the Miranda Town Centre. Builders experienced in the transition zone between existing single-dwelling character and new medium-density types will find strong demand here through the late 2020s.",
      "Painters": "Asbestos-containing fibro and cement sheeting are common in the 1960s-70s housing stock that still survives in Miranda's residential streets. Lead paint management under AS 4361.2 is standard practice before any surface preparation work. The newer apartment buildings entering repaint cycles need swing-stage or BMU access programs.",
      "Pest Control": "The Shire's bushland interface creates genuine termite pressure in the Miranda area, particularly on the properties backing onto reserve land. Pre-purchase inspections on older homes are strongly advisable, and annual AS 3660.2 inspections are the practical approach for maintaining protection on established properties.",
      "Landscapers": "Miranda's garden character ranges from the generous 1960s-70s allotments with established tree canopy to the compact common property plantings of newer apartment buildings. Sutherland Shire Council's tree preservation provisions apply broadly, and properties near the Woronora and Georges River catchments have riparian vegetation considerations.",
    },
  },

  "mount-barker": {
    housing: "Mount Barker is one of South Australia's fastest-growing towns, sitting 33km from Adelaide in the Adelaide Hills. The housing reflects that growth — a substantial base of historic town-centre homes from the late 1800s and early 1900s, surrounded by wave after wave of master-planned residential estates from the 1990s to today. Over 1,300 hectares were rezoned for urban expansion as part of the Mount Barker Growth Area, and the suburb now looks like what happens when a historic Hills town gets absorbed into Greater Adelaide's edge. 2000s and 2010s brick veneer and rendered homes on staged lots dominate the newer sections.",
    climate: "Adelaide Hills climate — cooler, wetter, and greener than the Adelaide plains below. Summers are warm but significantly more comfortable than the city, with temperatures averaging 3-5°C lower than Adelaide CBD. Winters are proper — cold mornings, occasional frosts, and rainfall around 750-850mm annually (well above the 560mm of the plains). The combination of hills topography and higher rainfall creates a different maintenance context from flat suburban Adelaide.",
    council: "District Council of Mount Barker",
    region: "Adelaide Hills",
    tradeNotes: {
      "Electricians": "Mount Barker's fast growth has created a large volume of new construction electrical work through the estate developments. But the historic town centre has its share of older Federation and inter-war homes with pre-war wiring, ceramic fuses, and undersized switchboards that generate steady upgrade work. Solar PV installations are popular across both old and new housing given SA's generous export tariffs historically.",
      "Plumbers": "The Hills' cooler climate means cold water supply pipes and hot water systems work harder through winter than the metro suburbs. Historic homes have lead and galvanised pipe that's being replaced progressively. The fast-growth new estates create ongoing plumber demand for new connections, rainwater tank plumbing (very common in the Hills), and gas fitting as many homes use LPG where reticulated gas isn't available.",
      "Builders": "The District Council of Mount Barker manages a complex planning landscape — heritage conservation areas around the historic town centre, flood mapping near the rivers, and the Growth Area rezoning for new estates. Bushfire risk is significant across the Hills; BAL ratings apply broadly and affect construction specifications substantially. Builders in the area need current bushfire management plan experience.",
      "Painters": "Mount Barker's winter damp and the higher rainfall than Adelaide mean surface preparation matters more here than in the drier plains suburbs. Mould and moisture-related paint failure on south and west-facing walls is more common. Heritage colour and material requirements apply in the historic town centre conservation area, and any external works on significant heritage buildings need to be carefully considered.",
      "Pest Control": "Adelaide Hills subterranean termite pressure is significant, and the native vegetation surrounds of many Mount Barker properties bring that pressure right to the building perimeter. The historic timber-framed homes in the town centre are particularly vulnerable — many haven't had barrier treatment updates since original construction. Annual AS 3660.2 inspections are strongly advisable.",
      "Landscapers": "Mount Barker's Hills environment means gardens that genuinely work in a higher-rainfall, cooler climate — European ornamentals, fruit trees, and productive kitchen gardens are common and thrive. Bushfire-aware landscaping is essential for properties on the Hills escarpment and ridge lines, with fuel reduction zones and ember-resistant planting selection guiding design on affected properties.",
    },
  },

  "north-sydney": {
    housing: "North Sydney is an inner-city suburb 3km north of the Sydney CBD, anchored by a significant commercial office precinct that sits alongside high-density residential. Over two-thirds of the housing is medium to high density — units, townhouses, and terraces. Victorian and Federation-era terrace rows survive on the quieter residential streets of Cremorne Point, Kirribilli, and Lavender Bay on the suburb's fringes. The commercial North Sydney core is ringed by apartment buildings ranging from 1960s walk-up blocks to contemporary glass towers. High resident turnover and a large proportion of renters characterise the apartment market.",
    climate: "Harbour-facing northern Sydney microclimate. The spectacular harbour position creates sea breezes off the water and moderates temperature extremes. Summer days are warm and humid but rarely reach the western suburbs highs. Winters are mild, rarely cold. Annual rainfall around 1200mm. The northern harbour slopes catch afternoon sea breezes reliably — it's genuinely more comfortable than inland suburbs on hot days.",
    council: "North Sydney Council",
    region: "Lower North Shore Sydney",
    tradeNotes: {
      "Electricians": "North Sydney's apartment stock spans from 1950s vintage walk-up blocks with original three-phase switchboards through to brand-new towers with BMS-managed common property systems. The full spectrum of electrical work exists here — heritage switchboard replacements in older units, data centre and UPS installations in the commercial precinct, and complex body corporate common property maintenance contracts.",
      "Plumbers": "High-rise apartment buildings throughout North Sydney have hydraulic systems of varying age and condition. The Victorian terrace stock in Kirribilli and Lavender Bay has original cast iron drainage and lead pipe that gets replaced incrementally as renovation projects proceed. The harbour-facing properties have specific requirements around corrosion-resistant fittings in salt air environments.",
      "Builders": "North Sydney Council applies Heritage Conservation Areas across significant parts of Kirribilli, Milsons Point, and McMahons Point that protect Victorian and Federation-era streetscapes. The commercial core is governed by different planning provisions, and the mix of heritage and contemporary development in close proximity requires builders to understand both contexts. SEPP (Transport and Infrastructure) provisions affect development near the Harbour Bridge approaches.",
      "Painters": "Salt air from the harbour accelerates exterior coating degradation on harbour-facing properties throughout the North Sydney area. Lead paint is near-certain in the pre-1970 terrace and flat stock. High-rise repaints require swing-stage or BMU access, and the visual prominence of the harbour precinct means the quality of exterior work is noticed — cutting corners on finishes is not advisable here.",
      "Pest Control": "The inner-city density of North Sydney means pest management is as much about commercial and common property services as individual residences. Cockroach, rodent, and ant management for apartment buildings and commercial premises is a steady service requirement. The older terrace stock has standard Sydney subterranean termite risk, and annual inspections remain worthwhile on timber-framed residences.",
      "Landscapers": "North Sydney's apartment building common property landscaping is typically managed through strata maintenance contracts. Rooftop gardens and communal terrace plantings are popular in the newer buildings. The established trees in the residential streets of Kirribilli and Lavender Bay are subject to North Sydney Council's significant tree provisions and the Heritage Conservation Area controls.",
    },
  },

  "robina": {
    housing: "Robina is Australia's largest master-planned suburb, conceived in the 1980s and developed progressively around Bond University, Robina Hospital, and the Robina Town Centre shopping precinct. The housing reflects that planned origin — distinct residential precincts arranged around three artificial lakes, with housing types varying from medium-density apartments near the commercial spine to generous detached four-bedroom homes in the residential estate sections. The suburb now spans 15 square kilometres and has a population of over 25,000.",
    climate: "Subtropical Gold Coast climate with reliable sea breeze access in the afternoon from the east. Hot, humid summers with the wet season from November through March bringing the bulk of annual rainfall (around 1600mm). Summer days in the low-to-mid 30s with high humidity. Winters dry and genuinely pleasant, around 20-22°C daytime. Severe storm cells with hail are an occasional hazard across the mid-Gold Coast.",
    council: "Gold Coast City Council",
    region: "Southern Gold Coast",
    tradeNotes: {
      "Electricians": "Robina's housing spans 40 years of development, so the electrical work ranges from older 1980s-90s estate homes needing switchboard upgrades through to new apartment towers with sophisticated BMS systems. Bond University and Robina Hospital both generate significant commercial electrical maintenance contracts. Solar PV adoption is very high across the residential estates.",
      "Plumbers": "The master-planned character of Robina means consistent infrastructure design throughout — but the 1980s-90s housing in the earlier estates is now reaching the point where hot water systems and plumbing fixtures are being replaced rather than maintained. The lakeside properties have specific requirements around moisture management and subfloor drainage design.",
      "Builders": "Gold Coast City Council's planning scheme applies specific provisions to Robina as a major activity centre. The NCC cyclone-region wind loading requirements (Region C) apply across all Gold Coast construction. New mixed-use development around Robina Town Centre is ongoing, and the Lakeview Robina development is approved to deliver 2,750 additional dwellings — significant pipeline work for the area.",
      "Painters": "The subtropical UV and humidity in Robina means exterior coatings on rendered estate homes age more quickly than temperate climates — quality exterior acrylic with UV and mould inhibitors is the practical specification. Homes in the lakeside residential sections face additional humidity from the artificial lakes, which drives faster mould growth on shaded wall surfaces.",
      "Pest Control": "The Gold Coast's year-round warmth and Robina's constructed wetland and lake system create ideal conditions for pest activity. Subterranean termite management is essential — AS 3660.1 systems were required for new construction, but older estate homes need verification that their systems remain functional. The lake precincts also generate mosquito management requirements for property owners.",
      "Landscapers": "Robina's lake and open space corridors create a genuinely attractive landscape setting for private gardens. The subtropical climate supports rapid plant establishment and lush planting, but the warm, wet conditions also drive weed growth and lawn maintenance intensity. Gold Coast City Council's vegetation clearing provisions apply to significant trees, and waterway setback requirements affect lakeside landscaping.",
    },
  },

  "ryde": {
    housing: "Ryde is a hilly suburb in Sydney's north, about 12km from the CBD, with a housing history that spans from modest post-war brick homes to the current wave of high-density apartment development. High-density dwellings now make up 44% of the City of Ryde's stock, up from 33% in 2016 — and the pace hasn't slowed. Riverside sections near the Parramatta River have attracted the large apartment complexes. The older residential sections retain 1950s-70s brick homes on decent-sized lots, some of which are being subdivided to accommodate the current NSW Government housing reform agenda.",
    climate: "Northern Sydney inland suburb climate. Warmer and less breezy than the harbour-facing suburbs, but with the Lane Cove National Park escarpment nearby providing some topographical variation. Summers warm and humid, pushing into the mid-to-high 30s on northerly wind days. Winters mild — rarely below 8°C overnight. Annual rainfall around 1100mm, with summer afternoon storms providing a significant proportion.",
    council: "City of Ryde",
    region: "Northern Sydney",
    tradeNotes: {
      "Electricians": "Ryde's mixed housing stock means electricians encounter the full range — original 1950s-60s switchboards in the older brick homes through to new multi-dwelling builder fit-outs in the rapidly expanding apartment sector. The City of Ryde's significant Chinese-Australian community has driven demand for specific domestic installations including induction cooktops, EV charging, and smart home systems.",
      "Plumbers": "The older Ryde housing has the standard galvanised and early copper pipe issues that come with 1950s-70s construction. The apartment development wave along the Parramatta River frontage and around Top Ryde City creates strong demand for hydraulic engineers and licensed plumbers for new residential tower fit-outs.",
      "Builders": "City of Ryde has a State Government housing target of 15,550 new dwellings in 5-10 years — one of the highest targets in Sydney. This is reshaping the planning landscape rapidly, with new SEPP provisions and infill housing corridors being gazetted. Builders experienced in R3 and R4 zone residential development will find significant opportunity in Ryde through the late 2020s.",
      "Painters": "Lead paint is a baseline expectation in Ryde's pre-1970 housing. The AS 4361.2 assessment and management process is standard before any surface preparation work begins. The new apartment tower market also generates painting and coating work — interior common area repaints, and exterior concrete facade treatments as buildings enter their first maintenance cycle.",
      "Pest Control": "The Lane Cove National Park bushland interface creates elevated subterranean termite pressure in Ryde's northern sections. Annual AS 3660.2 inspections are advisable for timber-framed homes, particularly those near the national park escarpment. The apartment development wave also creates commercial pest management demand for builder-phase treatments and ongoing strata pest control contracts.",
      "Landscapers": "Ryde's hilly topography means retaining walls and cut-and-fill earthworks feature in many garden projects. City of Ryde's tree preservation provisions protect significant trees on private land, and the Lane Cove Valley bushland interface means native species selection is both appropriate and council-encouraged. Common property landscaping maintenance for the growing apartment stock is a steady service line.",
    },
  },

  "balwyn-north": {
    housing: "Balwyn North (also called North Balwyn) sits 10km east of Melbourne in the City of Boroondara, and it's genuinely one of the most tightly held family suburbs in the eastern suburbs. The housing stock was mostly developed between 1920 and 1960 — substantial brick homes on large allotments that were considered generous even by the standards of the time. The blocks have stayed largely intact, which means established gardens, mature tree canopy, and the sense of space that defines Boroondara's better streets. The suburb's outstanding school catchments draw families from across Melbourne, which puts persistent upward pressure on prices.",
    climate: "Melbourne's eastern inland suburban climate. Four clear seasons — hot, sometimes very hot summers (38-40°C on the bad days in January), cold winters with regular frosts and overnight lows of 3-6°C. Annual rainfall around 650mm with a slight spring peak. Less moderation from Port Phillip Bay than Bayside suburbs. The mature tree canopy throughout Balwyn North genuinely reduces local temperatures compared to the treeless outer suburbs.",
    council: "City of Boroondara",
    region: "Inner East Melbourne",
    tradeNotes: {
      "Electricians": "The 1920s-1960s housing throughout Balwyn North includes some genuinely old wiring — pre-war homes with fabric-insulated cables and ceramic fuses are not uncommon. As the suburb's homeowners undertake renovation projects, full rewires and switchboard replacements are a standard component of the scope. EV charger installations and smart home systems are increasingly part of the brief on prestige renovations.",
      "Plumbers": "Balwyn North's pre-war to 1950s housing commonly has lead and galvanised supply pipe, original cast iron drainage, and early copper that's reaching the point of regular failures. The large allotments also mean longer service runs that cost more to replace. Irrigation system installations for the generous garden areas are a steady part of the local plumbing workload.",
      "Builders": "City of Boroondara applies Neighbourhood Character Overlays across virtually the whole suburb, and heritage protections apply to the older pre-1940 housing. Any demolition of original housing requires careful consideration of the planning scheme — many submissions are refused or require heritage impact assessment. Extensions and alterations are the dominant work type, and doing them well in a heritage context requires genuine expertise.",
      "Painters": "Lead paint is essentially guaranteed in Balwyn North homes built before 1970, and given the large proportion of 1920s-50s housing, that covers most of the suburb. The AS 4361.2 lead paint management protocol is standard practice before any preparation work. The prestige renovation market here means quality finish expectations are high — clients notice the difference between a careful, properly-prepared repaint and a quick roll-and-go.",
      "Pest Control": "Subterranean termite activity is consistent throughout Boroondara, and Balwyn North's large established gardens with mature elms, oaks, and eucalypts create excellent foraging corridors. The high property values mean termite damage has significant financial consequences, and annual AS 3660.2 inspections alongside active monitoring barriers are the practical standard for the suburb.",
      "Landscapers": "Balwyn North's large allotments and significant tree canopy are genuine assets — mature established gardens that would take 60+ years to recreate. City of Boroondara's Significant Tree Register and Heritage Overlay provisions protect trees above the threshold size. Garden renovation at the prestige end involves formal hedging, quality paving and pool surrounds, and planting that respects the established character.",
    },
  },

  "blackburn-south": {
    housing: "Blackburn South is a quiet, established suburb 16km east of Melbourne in the City of Whitehorse. The housing is almost entirely post-war — the area was primarily orchards before the 1950s, when the brick veneer suburban development that now characterises the suburb was laid out. The typical stock is a 1950s-70s cream brick or red brick home on a 600-700sqm allotment, solid and well-built, with established garden canopy. Blackburn Lake Sanctuary borders the eastern side of the suburb and gives it genuine natural character. It's an unpretentious, stable, owner-occupier suburban environment.",
    climate: "Melbourne's eastern suburban inland climate, similar to Blackburn and Box Hill. Hot summers, proper winters. January days regularly exceed 35°C and August nights drop to 4-6°C. Annual rainfall around 650mm. The bush character of Blackburn Lake Sanctuary creates a more natural microclimate in the eastern sections — slightly cooler and more humid than the open suburban streets further west.",
    council: "City of Whitehorse",
    region: "Eastern Suburbs Melbourne",
    tradeNotes: {
      "Electricians": "Blackburn South's 1950s-70s housing stock contains a significant proportion of original switchboards with ceramic fuses or early circuit breakers — upgrades to modern RCD-protected consumer mains are very common as homeowners renovate or sell. The Laburnum train station precinct and the shopping strip on Springfield Road generate some commercial electrical maintenance work.",
      "Plumbers": "Post-war plumbing throughout Blackburn South means galvanised supply pipe runs and original hot water systems are approaching end of service life. The 600-700sqm allotments support irrigation systems, and rainwater tank installations with pressure pump connections are increasingly common as homeowners respond to Melbourne Water's tariff structure.",
      "Builders": "City of Whitehorse applies Neighbourhood Character Overlays that protect Blackburn South's post-war residential character from overdevelopment. The proximity to Blackburn Lake Sanctuary means some properties have ecological sensitivity considerations, and any development near the reserve boundary needs to account for Council's open space and vegetation protection provisions.",
      "Painters": "Lead paint is the expectation rather than the exception in Blackburn South's pre-1970 housing stock. The AS 4361.2 risk assessment process before any sanding or stripping work is standard industry practice. Melbourne's cold, wet winters mean south-facing weatherboard and timber elements on older homes accumulate moisture damage and need careful surface preparation before repainting.",
      "Pest Control": "City of Whitehorse has active subterranean termite populations, and Blackburn South's proximity to Blackburn Lake Sanctuary and the associated bush corridors increases pressure on properties near the reserve boundary. Annual AS 3660.2 inspections are standard recommendation for any property with timber subfloors or established garden trees within foraging distance.",
      "Landscapers": "The bush character of Blackburn Lake Sanctuary makes native garden design particularly appropriate and visually cohesive in Blackburn South. City of Whitehorse has significant tree protection provisions, and the reserve boundary properties need to be aware of Council requirements around vegetation management at the interface. The 600-700sqm allotments suit practical family gardens with room for both outdoor entertaining and productive plantings.",
    },
  },

  "carindale": {
    housing: "Carindale is a well-established eastern Brisbane suburb, 25 minutes from the CBD, anchored by the Westfield Carindale shopping centre (one of the largest in Queensland). The housing stock is relatively young by Brisbane standards — the suburb developed mostly from the 1970s onwards on what had been peri-urban land, and the dominant stock is 1970s-90s brick and tile family homes on generous allotments. Owner-occupation rates are very high (above 80%) and the demographic tilts strongly toward couples with children and families in the 50-59 age bracket. Parks cover nearly a third of the total suburb area.",
    climate: "Subtropical Brisbane eastern suburbs climate. Hot, humid summers with the wet season bringing concentrated rainfall from November through March. Summer days in the low-to-mid 30s with high humidity. Winters mild and dry — daytime around 20-22°C, genuinely pleasant. The suburb's position in the eastern foothills gives it slightly more afternoon breeze than the southern suburbs. Occasional severe storm events with hail affect this part of Brisbane.",
    council: "Brisbane City Council",
    region: "Eastern Brisbane",
    tradeNotes: {
      "Electricians": "Carindale's 1970s-90s housing stock is entering the range where switchboard upgrades, safety switch compliance, and hot water system electrical connections are regular requests. The suburb's high owner-occupation rate and family demographic means renovation work is a steady driver — kitchen and bathroom upgrades bring electricians in as part of the project team.",
      "Plumbers": "Galvanised supply pipes from the 1970s-80s construction era are regularly failing in Carindale homes, and the subtropical heat cycles accelerate corrosion in exposed supply runs. Hot water system replacements are standard maintenance work across the suburb. The generous allotments support pool installations, which generate ongoing pool equipment plumbing maintenance.",
      "Builders": "Brisbane City Council's planning provisions apply flood mapping requirements to parts of Carindale near the major waterways draining to the Brisbane River. Pre-2011 flood data has been updated, and renovation work on older homes near Bulimba Creek and its tributaries should confirm applicable floor level requirements. The NCC's subtropical design provisions apply across the suburb.",
      "Painters": "Subtropical humidity drives mould growth on south and east-facing exterior surfaces throughout Carindale, particularly on the timber elements of older brick-and-tile homes and the eaves and soffit boards of established housing. Anti-mould exterior finishes and proper biological treatment of active growth before painting are necessary for a lasting result in this climate.",
      "Pest Control": "Brisbane's eastern foothills provide ideal conditions for subterranean termite activity, and Carindale's proximity to Bulimba Creek corridor and the remnant bushland in the suburb's parkland areas increases the baseline risk. Annual AS 3660.2 inspections on the older 1970s-80s housing are strongly advisable, particularly for properties where termite management systems haven't been updated since original installation.",
      "Landscapers": "Carindale's generous allotments and near-third coverage by parks gives it real garden character. Established fruit trees and subtropical plantings thrive, and the high owner-occupation rate means there's genuine investment in private garden spaces. Brisbane City Council's vegetation clearing provisions apply to significant trees on private land, including mature fig trees and eucalypts common in the older established sections.",
    },
  },

  "carlisle": {
    housing: "Carlisle is a compact inner southern Perth suburb in the Town of Victoria Park, sitting right on the Perth-Armadale train line. The housing is a genuine mix: post-war character homes from the 1940s-50s in the western sections closer to the river, 1960s-70s brick veneer through the middle, and increasingly infill medium-density townhouses as the inner suburban land value attracts development. It's a suburb in transition — the older character homes are being bought by renovators or replaced by townhouse developments, and the areas around the train stations are intensifying. Two suburban train stations (Oats Street and Carlisle) give it exceptional transit access.",
    climate: "Mediterranean Perth climate, slightly inland from the coast but still benefiting from the afternoon Fremantle Doctor sea breeze most summer days. Hot dry summers with January regularly hitting 38-40°C. Winters mild and wet, with 800-850mm annual rainfall concentrated between May and September. The Swan River is nearby to the west, which provides some moderating influence.",
    council: "Town of Victoria Park",
    region: "Inner South Perth",
    tradeNotes: {
      "Electricians": "Carlisle's mixed housing era means electricians see everything from pre-war fuse boxes to modern switchboards in the same street. Post-war character homes commonly have pre-RCD wiring, and the renovation market driving townhouse development creates demand for full fit-out electrical work. Solar PV is extremely popular in inner Perth given the combination of strong solar resource and WA's electricity prices.",
      "Plumbers": "The post-war character homes in Carlisle's western sections have galvanised supply and early drainage that's well into its replacement window. The townhouse development wave creates new-build plumbing demand. The Town of Victoria Park also has a strong infill policy, meaning sewer connections and water main tapping for new dwellings on subdivided lots is regular work.",
      "Builders": "The Town of Victoria Park actively supports medium-density infill development near the train stations, and the Carlisle precinct is specifically identified in the Council's structure planning. R-codes compliance for townhouse and grouped dwelling development is the main planning framework. Building and Energy WA licensing requirements apply across all residential construction.",
      "Painters": "Perth's intense UV and the hot summers make exterior paint life shorter than temperate cities — budget exterior products on the west and north-facing elevations of Carlisle homes can chalk and fade within 6-8 years. The post-war fibro and asbestos-cement homes in the older sections require asbestos management protocols and licensed removal before any surface works.",
      "Pest Control": "Perth's subterranean termite pressure is consistent throughout the inner suburbs, and Building and Energy WA requires termite management systems for all new construction. However, Carlisle's older housing stock — particularly the post-war fibro and weatherboard homes — predates modern barrier requirements. Pre-purchase inspections frequently identify activity or inadequate existing systems.",
      "Landscapers": "Carlisle's inner suburban blocks are modest in size, and garden design needs to work within compact footprints. Water-wise native plantings and low-maintenance design are the practical choice in Perth's dry climate. The Town of Victoria Park has strong urban forest ambitions, and street tree canopy improvement is an active program — native plantings in private gardens that extend the canopy character are encouraged.",
    },
  },

  "millner": {
    housing: "Millner is a small Darwin suburb in the Darwin North Coastal zone, covering just 1.5 square kilometres of the city's inner northern residential belt. The housing stock reflects the typical Darwin residential character — elevated single and double-storey homes designed for cyclone resilience and tropical ventilation, mostly from the 1970s post-Cyclone Tracy reconstruction era through to 1990s development. Two-bedroom homes make up the largest single housing category in the suburb (40% of stock). The small suburb has good park coverage and a genuine residential neighbourhood feel despite being close to the city.",
    climate: "Darwin's monsoonal tropical climate in full. Two seasons: a long, hot, and very wet Wet season from October through April, and a warm dry season from May through September. The Wet brings heavy cyclone-season rainfall, high humidity, and afternoon storms daily. The Dry is genuinely lovely — warm, sunny, low humidity, and reliable. Annual rainfall sits around 1700-1800mm, almost all of it falling in the Wet. Cyclone preparedness is a genuine building and maintenance consideration.",
    council: "City of Darwin",
    region: "Darwin Inner Suburbs",
    tradeNotes: {
      "Electricians": "Darwin's cyclone-season electrical loads are significant — air conditioning runs almost continuously through the Wet, and the extreme humidity accelerates corrosion in switchboards and external electrical fittings. Post-Tracy reconstruction housing from the 1970s-80s is reaching the age where switchboard replacements and wiring upgrades are being requested. Solar PV is very popular in the NT given the exceptional solar resource.",
      "Plumbers": "The elevated construction common throughout Darwin's inner suburbs means long understorey pipe runs that are exposed to weather — in Millner's cyclone-zone context, exposed pipe needs to meet cyclone tie-down and securing requirements. Hot water systems in Darwin work hard in the tropical heat and humidity, and solar hot water systems are near-universal. The Wet season creates significant drainage loads.",
      "Builders": "All new and substantially altered buildings in Darwin must comply with NCC cyclone-region design provisions (Region D — the most stringent cyclone classification). The City of Darwin's building approval process incorporates cyclone structural verification, and cyclone-rated roofing, windows, and doors are the baseline specification rather than an upgrade. Post-Tracy housing from the 1970s was rebuilt to the standards of the day, some of which don't meet current NCC requirements.",
      "Painters": "Darwin's tropical climate is brutal on exterior coatings. The combination of intense UV during the Dry, high humidity and rainfall through the Wet, and salt-laden air near the coast means quality coatings designed for tropical conditions are necessary. Anti-fungal primers and exterior finishes formulated for high-humidity environments perform significantly better than products designed for temperate climates.",
      "Pest Control": "Darwin has some of Australia's most aggressive termite pressure — Mastotermes darwiniensis (giant northern termite) is the most destructive species anywhere in the country, and it's active in the Darwin area. The combination of tropical warmth, moisture, and timber construction materials creates near-ideal conditions. Pre-purchase inspections and annual AS 3660.2 inspections are essential, not optional, for any timber-framed Darwin property.",
      "Landscapers": "Millner gardens need to balance tropical lushness with cyclone-aware planting selection. Deep-rooted native species and palms that are cyclone-rated are the practical choice over shallow-rooted ornamentals that become projectiles in severe events. Irrigation design should accommodate both the Dry season watering requirements and the need to reduce waterlogging during the intense Wet season rainfall.",
    },
  },

} as const;
