// SUBURB_CONTEXT entries — Batch 13 (suburbs 121–130)
// Suburbs: dickson, rockingham, upper-coomera, brighton-east,
//          armadale, bondi-junction, darra, weston-creek, caringbah, coomera

export const SUBURB_CONTEXT_BATCH_13 = {

  "dickson": {
    housing: "Dickson is one of Canberra's Inner North centres — a proper mixed-use suburb built around the Dickson shops and café strip, with housing that reflects five decades of ACT development decisions. About half the dwellings are flats and apartments, a quarter are separate houses, and the rest fall somewhere in between. The western edge of the suburb has been intensively redeveloped with multi-storey apartment buildings from the late 2010s onwards. Older ACT Housing stock from the 1970s sits alongside recently built private apartments in a way that feels a bit piecemeal.",
    climate: "Canberra's inland continental climate applies fully here. Cold winters — frosts from May through September are standard, and overnight lows of -5°C are not unusual. Hot dry summers with days regularly reaching 35-37°C. Annual rainfall sits around 620mm, spread through the year without a strong seasonal peak. The Inner North suburbs are somewhat more sheltered from the wind than the newer outer districts.",
    council: "ACT Government (City of Canberra)",
    region: "Inner North Canberra",
    tradeNotes: {
      "Electricians": "Dickson's ACT Housing stock from the 1970s-80s is undergoing progressive renewal and upgrade, and the electrical work involved ranges from switchboard replacements in existing units to full fit-out of new social housing builds. The apartment intensification on the western side drives significant demand for new building connections and multi-dwelling metering configurations.",
      "Plumbers": "The 1970s ACT public housing throughout Dickson commonly has copper pipe nearing 50 years of service — pinhole leaks and hot water service failures are regular callouts. The mixed-use precinct around Dickson shops also creates demand for commercial and retail plumbing maintenance.",
      "Builders": "The ACT Planning System's updated territory plan (2023) designates Dickson as a Key Transit Corridor area, supporting higher-density residential development close to the light rail stops. Builders working on infill development need to understand the NZ zone provisions and the ACT's building approval processes, which differ meaningfully from state-based systems.",
      "Painters": "Canberra's dramatic temperature swings — from -5°C in winter to 38°C in summer — are genuinely hard on exterior coatings. Paint on south-facing walls collects frost damage and moisture cycling through winter, while north-facing surfaces get brutal UV through summer. Two-coat exterior systems with good elasticity perform significantly better than budget products here.",
      "Pest Control": "Canberra's subterranean termite species (particularly Coptotermes acinaciformis) operate year-round and are active in Dickson despite the cold winters. The mix of 1970s public housing with ageing timber elements and newer private development with disturbed soil profiles creates varied risk. ACT Pest Management licensing is required for all treatments.",
      "Landscapers": "Dickson's apartment and townhouse precincts have limited garden space, but the suburb's leafy character streetscapes include significant established trees under ACT Government tree protection provisions. Common property landscaping maintenance for strata buildings is a steady source of work throughout the inner north.",
    },
  },

  "rockingham": {
    housing: "Rockingham is the main centre of Perth's southern coastal corridor, about 47km from the CBD. The housing spans a wide range — from 1960s-70s modest brick homes in the older beach-facing sections near Rockingham Beach, to 1980s-90s suburban estates further inland, through to newer medium-density townhouses supporting the growing population. The waterfront and Mangles Bay areas have pockets of higher-value older housing. The City of Rockingham LGA is substantial, covering a range of sub-precincts from the original town centre to newer outer growth areas.",
    climate: "Mediterranean Perth climate on the coast. Dry, hot summers with sea breezes off Cockburn Sound providing some relief in the afternoons. January and February regularly push 38-40°C on inland heat days. The coastal position brings more consistent summer breeze than the hills and northern suburbs. Winters are mild and wet, around 750-800mm annual rainfall concentrated between May and September.",
    council: "City of Rockingham",
    region: "Southern Perth Coastal Suburbs",
    tradeNotes: {
      "Electricians": "The coastal location means salt air corrosion affects switchboard enclosures, external fittings, and air conditioning units more aggressively than inland Perth suburbs. Older homes from the 1960s-70s beachside sections still have pre-RCD switchboards, and the conversion from single-phase to 3-phase for EV chargers and air conditioning in older dwellings is increasingly requested.",
      "Plumbers": "Older Rockingham properties near the coast frequently have corroded or undersized galvanised pipe that's well past its service life. Hot water system replacements across the 1970s-80s housing stock are steady work. The City of Rockingham also has a significant amount of garden bore pump installations given the sandy coastal plain soils.",
      "Builders": "The City of Rockingham's planning scheme supports ongoing residential growth, with infill development in the town centre and new estate development in the outer growth areas. Building and Energy WA licensing requirements apply, and coastal development near Mangles Bay is subject to coastal management overlays.",
      "Painters": "Salt air from Cockburn Sound and the intense Perth UV makes exterior paint in coastal Rockingham work hard. Quality marine-grade or high-build exterior coatings are the practical choice for beachside properties. The older 1960s-70s fibro and asbestos-cement homes require careful asbestos management protocols during any surface works.",
      "Pest Control": "Perth's subterranean termite pressure extends throughout the Rockingham area. Building and Energy WA requires termite management systems for all new construction, and pre-purchase inspections on older 1960s-80s homes regularly identify gaps or failed chemical barriers. The sandy soils that are common here actually accelerate termite movement.",
      "Landscapers": "Rockingham's coastal plain sandy soils retain virtually no water — garden design needs to account for extremely low water-holding capacity with generous mulching and water-efficient plant selection. The Council's water-wise garden program supports low-water native landscaping, and bore irrigation with timer controls is the practical solution for larger garden areas.",
    },
  },

  "upper-coomera": {
    housing: "Upper Coomera is one of the Gold Coast's fastest-growing fringe suburbs, sitting in the northern inland section of the city about 50km from Brisbane. The housing is almost entirely modern estate development — four-bedroom brick and rendered homes on 400-600sqm lots, built from the mid-1990s onwards in a series of staged residential estates. Over 65% of dwellings are four-bedroom-plus homes. It's textbook rapid suburban expansion: tightly packed estates, newer schools, and neighbourhood shopping centres appearing in sequence as population milestones are hit.",
    climate: "Subtropical Gold Coast inland climate — hotter in summer than the beachside suburbs due to the lack of sea breeze moderation. January and February regularly hit 35°C+ with high humidity. Afternoon thunderstorms are the norm through the wet season. Winters are mild, comfortable, and dry. The suburb's relatively treeless estate character means limited shade and significant urban heat island effect compared to older, more established suburbs.",
    council: "Gold Coast City Council",
    region: "Northern Gold Coast",
    tradeNotes: {
      "Electricians": "Modern housing stock throughout Upper Coomera means the electrical work is predominantly product upgrades rather than age-related issues — solar PV systems with battery storage, EV charger additions, and whole-home automation upgrades. The speed of the suburb's growth has also created a steady stream of defect rectification work on homes built to minimum specification.",
      "Plumbers": "New-build and post-new-build plumbing work dominates here. The large estate homes have significant hot water demand, and heat pump hot water system upgrades replacing the original electric storage units are a common request. Irrigation system installations for the large backyard areas are also regular jobs.",
      "Builders": "Gold Coast City Council's planning scheme includes noise overlay provisions relevant to Upper Coomera, given the proximity to the Pacific Motorway and Coomera rail corridor. Builders should also confirm lot-specific flood levels in the lower-lying sections near Coomera River. The NCC cyclone-region wind loading provisions (Region C) apply across the Gold Coast.",
      "Painters": "Estate-era construction in Upper Coomera tends to be built to minimum acceptable standard, and the exterior coatings on rendered homes in particular often use budget-grade products that chalk and fade within 6-8 years. The subtropical UV and humidity accelerate this. Repaints with quality exterior acrylic are frequently requested on homes hitting the 10-year mark.",
      "Pest Control": "Subterranean termite risk is significant across the northern Gold Coast growth corridor. AS 3660.1 management systems were required for all new construction, but the quality and completeness of those systems in rapidly built estate housing varies. Annual AS 3660.2 inspections are strongly advisable — particularly where homes back onto creek corridors and remnant vegetation.",
      "Landscapers": "Upper Coomera's estate homes often have landscaping that was never done beyond basic turf establishment at handover. Backyard design, shade tree planting, and outdoor entertainment area construction are strong ongoing demands. The subtropical climate supports rapid garden establishment but equally rapid weed growth, so low-maintenance design matters.",
    },
  },

  "brighton-east": {
    housing: "Brighton East is one of Melbourne's prestige southeastern bayside suburbs, 12km from the CBD within the City of Bayside. The housing stock is genuinely diverse in the best sense — Victorian and Edwardian period homes, Inter-War California bungalows, and post-war brick veneer alongside contemporary architect-designed rebuilds. Most properties sit on generous allotments with mature tree canopies, giving the suburb a leafy, peaceful feel. Wide streets and substantial setbacks characterise the better sections. It's not a suburb where you find much of the original stock remaining unchanged — renovation and extension is constant.",
    climate: "Melbourne bayside climate, with the proximity to Port Phillip Bay providing some moderating influence compared to the inner east. Summer days in the low-to-mid 30s, occasionally higher on northerly wind days. Cold but rarely freezing winters — overnight lows around 5-8°C. Annual rainfall around 650mm spread fairly evenly. The bay influence keeps the humidity lower than the inner suburbs in summer.",
    council: "City of Bayside",
    region: "Bayside Melbourne",
    tradeNotes: {
      "Electricians": "Brighton East's ongoing renovation and luxury extension market means electricians are regularly working in period homes with mixed heritage wiring — some original knob-and-tube and rubber-sheathed cable surviving beneath more recent additions. Full rewires are common on renovation projects. EV charger installations and home automation system wiring are standard on higher-end builds.",
      "Plumbers": "The period housing stock has significant age range — the older homes have lead and galvanised pipe that surfaces regularly during bathroom and kitchen renovations. Brighton East's prestige market also means high-specification hydraulic fit-outs for new builds and major renovations — hydronic underfloor heating, multiple bathroom en suite fit-outs, and outdoor kitchen plumbing.",
      "Builders": "City of Bayside's planning scheme applies Heritage Overlays to significant sections of Brighton East's older streetscapes, and the Neighbourhood Character Overlay provisions affect design across the broader suburb. Getting planning approval for demolition of original period housing is not automatic — heritage impact assessments and character assessment reports are frequently required.",
      "Painters": "Lead paint is the baseline assumption in Brighton East's pre-1970 housing. The suburb has a high proportion of owner-occupiers doing prestige renovations, and the AS 4361.2 lead paint management approach is standard practice. Quality exterior coatings on rendered extensions and period brick homes are an expected part of the work — budget products are not the norm at this end of the market.",
      "Pest Control": "Subterranean termite activity is consistent throughout the City of Bayside, and Brighton East's large established garden trees and leafy street canopy create ideal foraging conditions. Annual inspections under AS 3660.2 are standard practice for owners of period homes, and the high property values in the suburb mean skimping on termite management doesn't make financial sense.",
      "Landscapers": "Brighton East gardens tend to be generous by Melbourne standards, and the suburb's established tree canopy is a genuine feature worth protecting. City of Bayside has tree protection provisions under the significant tree register. Garden design at the prestige end of the Brighton East market involves proper design expertise, quality materials, and ongoing maintenance contracts.",
    },
  },

  "armadale": {
    housing: "Armadale VIC (postcode 3143) is one of Melbourne's most tightly held and expensive inner suburbs, sitting about 7km southeast of the CBD within the City of Stonnington. The housing is dominated by grand Victorian and Edwardian period homes — two and three-storey brick and render — and meticulously restored terraces on relatively tight street frontages. High-end boutique apartments in low-rise buildings have appeared in the commercial precincts. The Armadale shops along High Street have been a destination for high-end furniture and homewares for decades, which says a lot about the suburb's demographic.",
    climate: "Melbourne's inner southeastern suburban climate. Four distinct seasons, though more sheltered from extremes than the outer suburbs. Summer days in the low-to-mid 30s, occasionally hot when the northerly blows through. Winters cold but not harsh — frosts are rare in this inner belt. Annual rainfall around 650mm. The suburb's significant tree canopy moderates the urban heat island effect noticeably.",
    council: "City of Stonnington",
    region: "Inner East Melbourne",
    tradeNotes: {
      "Electricians": "Victorian and Edwardian housing in Armadale presents the standard inner Melbourne challenge — original wiring in various states of partial update, undersized switchboards behind ornate original architrave, and the complications of working in period homes where any surface works require careful thought about heritage fabric. High-end renovation clients here expect clean, professional work with no visible conduit or surface cable.",
      "Plumbers": "Lead and early copper pipe runs are routine finds behind the walls of Armadale's older housing. Renovation projects regularly include full bathroom and kitchen replumbing as a matter of course. The high-end renovation market also drives demand for luxury hydraulic specifications — heated towel rails, concealed cisterns, and outdoor kitchen installations are standard requests.",
      "Builders": "City of Stonnington applies Heritage Overlay provisions across substantial parts of Armadale, and the planning process for demolition or significant external alteration of original housing is involved. Heritage impact statements, pre-application meetings, and in some cases referral to the Heritage Council of Victoria are required. The permit process takes time and expertise to navigate.",
      "Painters": "Every pre-1970 home in Armadale should be treated as containing lead paint until proven otherwise. The heritage market here also values quality — cheapo exterior coatings on a $4M Victorian terrace is not appropriate, and clients expect premium products applied correctly. Colour matching to heritage palettes and achieving the correct sheen levels on detailed Victorian timber joinery are specialist skills.",
      "Pest Control": "Subterranean termite activity is a real presence in Armadale's large established-garden properties, particularly in the areas backing onto Hedgeley Dene Gardens and the larger residential gardens with mature elms and oaks. The high property values mean termite damage is financially very significant — annual inspections and active barrier systems are the norm for informed owners.",
      "Landscapers": "Armadale gardens at the higher end are often professionally designed and maintained. The significant trees throughout the suburb are subject to City of Stonnington's Significant Tree Register and Heritage Overlay, and any removal requires council involvement. Garden renovation projects often involve sandstone walls, formal hedging, and heritage-appropriate planting that matches the architectural period of the house.",
    },
  },

  "bondi-junction": {
    housing: "Bondi Junction is the commercial and transport hub of Sydney's eastern suburbs — 6km from the CBD at the terminus of the Eastern Suburbs Railway, opened in 1979. The housing is overwhelmingly apartments, with a significant portion of the Waverley LGA's total dwelling stock concentrated here. The mix ranges from 1970s-80s brick walk-up flats and older medium-rise buildings around the shopping precinct through to contemporary high-rise apartments closer to the interchange. Terraces and semi-detached homes survive in the quieter residential streets on the edges, but the dominant character is apartments.",
    climate: "Sydney eastern suburbs coastal climate — moderated by the Pacific Ocean with regular sea breezes. Summers warm and humid but rarely as hot as the western suburbs. Southerly busters off the Tasman Sea arrive regularly in summer and drop temperatures sharply. Winters genuinely mild, rarely below 9°C overnight. Annual rainfall around 1200mm.",
    council: "Waverley Council",
    region: "Eastern Suburbs Sydney",
    tradeNotes: {
      "Electricians": "The concentration of 1970s-80s apartment buildings around the Bondi Junction interchange means a large proportion of the electrical stock in the area has switchboards approaching 40-50 years of age. Body corporate common property electrical systems — basement car parks, lift plant, common area lighting — require ongoing licensed maintenance. The newer apartment towers need high-specification data and automation installations.",
      "Plumbers": "High-rise apartment buildings throughout Bondi Junction have ageing vertical hydraulic risers that are reaching end of service life in the older towers. Strata committees increasingly face staged hydraulic riser replacement projects that require coordination across all floors. The short-term rental market (proximity to Bondi Beach) drives above-average plumbing wear in some buildings.",
      "Builders": "Waverley Council's Bondi Junction Masterplan (2024-2025) actively promotes further residential intensification around the interchange. Builders working in the area need to be across the B3 Commercial Core zone provisions and the transition zones applying to the residential streets. Heritage protections apply to some of the older pre-war buildings near the Oxford Street strip.",
      "Painters": "Apartment buildings in Bondi Junction range from well-managed strata with proactive maintenance to older buildings where the exterior paint has been deferred for a decade or more. Repainting high-rise and multi-storey buildings requires swing-stage rigging, BMU access, or elevated work platform coordination. Salt air from the ocean (1.5km away) accelerates surface degradation on eastern-facing elevations.",
      "Pest Control": "The eastern suburbs apartment market has lower subterranean termite risk than ground-level housing, but the terrace and semi-detached homes on the residential streets surrounding the commercial core are in standard Sydney termite territory. Cockroach and rodent control in the commercial precinct adjacent to residential properties is a significant ongoing service requirement.",
      "Landscapers": "Common property landscaping for the apartment buildings around Bondi Junction is typically managed through strata maintenance contracts. The residential streets on the fringe have standard eastern suburbs gardens — compact, often shaded, sometimes receiving significant salt spray on windy days from the east. Waverley Council's tree protection provisions apply to street trees and significant private trees.",
    },
  },

  "darra": {
    housing: "Darra is 13km southwest of Brisbane CBD — a suburb with an industrial heritage that's never fully left. Queensland Cement started production here in 1916, and the legacy of that industrial character means the suburb is genuinely mixed: freight depots and warehousing alongside residential streets. The housing is mostly 1940s-50s Queenslander-style homes on stumps, with some post-war cottages and early brick veneer from the 1960s-70s. The suburb has a significant Vietnamese-Australian community who arrived from 1975 onwards and shaped the culture of the area meaningfully.",
    climate: "Humid subtropical Brisbane climate, 13km from the CBD. Hot, wet summers — November through March brings the bulk of the 1100mm annual rainfall, with afternoon thunderstorms common. Summer days in the low 30s with high humidity. Winters mild and dry — daytime temperatures around 20-22°C. The western location of Darra means slightly hotter summer days than the bayside suburbs, with less sea breeze moderation.",
    council: "Brisbane City Council",
    region: "Southern Brisbane",
    tradeNotes: {
      "Electricians": "Darra's 1940s-60s Queenslander and post-war housing stock commonly has original switchboards with rewirable fuses — the kind that predate circuit breakers and safety switches by decades. Switchboard upgrades for safety compliance are regular jobs. The industrial precincts in the suburb also create demand for commercial three-phase electrical installation and maintenance.",
      "Plumbers": "The elevated Queenslander construction throughout Darra creates long under-house pipe runs that are exposed to weather and physical damage. Galvanised supply and cast iron drainage from the 1940s-50s is regularly reaching end of life. The multicultural community has driven cultural-specific plumbing modifications — gas fitting for wok burners, commercial kitchen-style laundry setups.",
      "Builders": "Brisbane City Council's flood mapping is particularly relevant in Darra — parts of the suburb near Oxley Creek experienced significant flooding in 2011 and 2022. Renovation and extension work on flood-affected properties needs to confirm applicable floor level requirements, and the freeboard provisions in Brisbane's flood-affected zones need to be understood before any structural work begins.",
      "Painters": "The subtropical humidity in Darra means mould growth on south and east-facing Queenslander weatherboards is a recurring problem. Quality anti-mould exterior finishes and proper surface preparation — including treatment of any active biological growth before painting — are necessary to get reasonable life from a repaint. Proximity to the industrial areas can also mean airborne oil and particulate contamination on surfaces.",
      "Pest Control": "Subterranean termites in Brisbane's southwest are highly active, and Darra's 1940s-50s Queenslanders on hardwood stumps represent prime habitat. The elevated design helps with visual inspection access, but the stumps and floor joinery are often found to be partially damaged on inspection. AS 3660.1 chemical reticulation systems or physical barriers are the standard treatment approach.",
      "Landscapers": "Darra gardens reflect the suburb's multicultural character — Asian herb gardens, productive food gardens, and densely planted tropical planting are common. The subtropical climate supports rapid garden establishment, and the generous 600-700sqm residential allotments from the post-war subdivision era give space to work with. Flood-aware planting in the lower-lying sections near the creek corridors is worth planning for.",
    },
  },

  "weston-creek": {
    housing: "Weston Creek is a district of eight residential suburbs in southwest Canberra, about 13km from the CBD: Waramanga, Fisher, Weston, Rivett, Duffy, Holder, Chapman, and Stirling. Development ran from 1968 to 1972 and the housing reflects that period almost entirely — double-brick Canberra-style homes on generous ACT allotments, with a smaller proportion of 1970s brick veneer. Fully 82% of dwellings are separate houses, well above the ACT average. The district has aged well, with established tree canopies and stable, owner-occupier dominated streets.",
    climate: "Canberra's cold continental climate applies in full. Hard winters with regular frosts from May through September, overnight lows reaching -7°C on the worst nights. Hot dry summers — January days can hit 38-40°C. Annual rainfall about 620mm with a slight spring peak. Weston Creek's slightly more elevated and western position catches some chill that the northern suburbs avoid, but it's not dramatically different.",
    council: "ACT Government (City of Canberra)",
    region: "Weston Creek Canberra",
    tradeNotes: {
      "Electricians": "Weston Creek's 1968-1972 double-brick housing stock was built during the ceramic fuse era — most homes have original switchboards that are now 50+ years old. Upgrades to modern RCD-protected consumer mains are very common as homeowners renovate. The all-electric ACT housing model and the push toward EV adoption means charger installations are also an increasing part of the local workload.",
      "Plumbers": "The 1970s plumbing throughout Weston Creek is reaching end-of-service-life territory — copper supply lines, early hot water systems, and original drainage are all generating replacement work as homeowners renovate. The double-brick construction makes plumbing runs more complex than timber-framed homes, as walls can't be easily accessed without cutting.",
      "Builders": "The ACT Planning System's Territory Plan designates much of Weston Creek as RZ1 — single dwelling residential — which limits density but is also consistent with the suburb's existing character. Renovation and extension work is the dominant activity. The double-brick construction method common throughout the district requires builders with specific experience in working with this wall type, including understanding how to create openings safely.",
      "Painters": "Canberra's climate is genuinely harsh on exterior paint — the combination of UV-intensive sunny summers and frost-cycling winters creates thermal stress on coatings that's worse than temperate coastal cities. Quality flexible exterior acrylics with good UV stabilisers are worth the extra cost in Weston Creek. Interior moisture control matters too — the double-brick walls can develop condensation issues if not properly managed.",
      "Pest Control": "Subterranean termites are active year-round in Canberra despite the cold winters, and Weston Creek's mature garden suburbs with large established trees create good foraging conditions. The double-brick wall construction doesn't protect the timber floor and roof structures from attack. Annual inspections under AS 3660.2 are the standard recommendation, with physical or chemical barriers on properties that haven't been recently treated.",
      "Landscapers": "Weston Creek's generous 1960s-70s allotments and mature garden canopy are genuine assets — established elms, oaks, and native eucalypts that would take 40 years to grow in a new estate. ACT Government tree protection provisions apply to trees above the threshold size, and removal without approval carries significant penalties. Garden renovation focuses on working with the existing canopy rather than starting from scratch.",
    },
  },

  "caringbah": {
    housing: "Caringbah is a solid mid-tier suburb in Sydney's Sutherland Shire, about 24km south of the CBD. The housing is mostly 1960s-70s brick veneer and fibro — standard Shire-era family homes on decent-sized allotments, many of them little changed from original. The suburb sits near the Cronulla rail line (Caringbah station), which has driven some apartment development along the station precinct over the past decade. The Sutherland Hospital is a dominant landmark at the suburb's edge. Overall it's an unpretentious, practical suburban environment that's becoming more sought-after as Cronulla prices push buyers inland.",
    climate: "Southern Sydney coastal-adjacent climate. Warm humid summers moderated by the proximity to Port Hacking and the Bate Bay coast — rarely as extreme as western Sydney. Summer days around 28-30°C, occasionally higher when the westerlies blow. Winters mild and mostly pleasant. Annual rainfall about 1300mm, with some of the heaviest falls in summer storm events. The Shire's topography funnels storm water in ways that affect low-lying sections of the suburb.",
    council: "Sutherland Shire Council",
    region: "Sutherland Shire Sydney",
    tradeNotes: {
      "Electricians": "Caringbah's 1960s-70s housing has the predictable array of old switchboards and inadequate safety switch coverage. The suburb's landlord market is meaningful (a proportion of the older stock is tenanted), which generates steady switchboard upgrade and compliance work as new tenancy requirements come into force. The hospital precinct creates commercial and healthcare electrical maintenance demand.",
      "Plumbers": "Galvanised pipe is a frequent find in original 1960s-70s Caringbah homes — the hot water services, in particular, are commonly the original electric storage units approaching 30-40 years of age. The Shire's topography means some areas have drainage challenges during heavy rainfall, and sewer connections and overflows are not uncommon maintenance issues.",
      "Builders": "Sutherland Shire Council applies DCP provisions that are relatively conservative on neighbourhood character change. The older fibro homes are reaching the age where asbestos management is a live issue for any renovation — fibro walls and ceilings from the 1960s require licensed asbestos removal before structural work. The infill apartment development around Caringbah station is subject to the applicable station precinct controls.",
      "Painters": "Lead paint and asbestos-containing materials (fibro sheeting, asbestos-cement ceiling panels) are standard finds in Caringbah's 1960s-70s housing. The overlap between lead paint management (AS 4361.2) and asbestos management licensing means painters need to be clear about what they are and aren't licensed to handle. Quality exterior coatings on the older homes make a visible difference to streetscape appeal.",
      "Pest Control": "The Sutherland Shire has genuine termite pressure, particularly in areas near the National Park bushland corridors and the waterways of Port Hacking. Caringbah's position in the middle of the Shire puts it in an area where annual inspections are strongly advisable. Pre-purchase inspections on the older fibro homes regularly identify termite activity or historical damage that wasn't disclosed.",
      "Landscapers": "Caringbah's generous allotments from the 1960s-70s subdivision era suit outdoor entertainment-focused landscaping — pools, alfresco areas, and productive gardens are common requests. The Shire's tree preservation provisions mean significant trees on private land require approval before removal. Proximity to the Royal National Park means native plantings tie in naturally with the broader landscape character.",
    },
  },

  "coomera": {
    housing: "Coomera proper (not to be confused with Upper Coomera to the west) sits on the northern Gold Coast, roughly 50km from Brisbane and 24km from Surfers Paradise. The suburb has grown fast — residential estates from the 1990s onwards have filled the former rural land around Coomera train station, and the pace of development is ongoing. Housing is predominantly three and four-bedroom brick or rendered homes in staged estates, with newer townhouse developments servicing the Westfield Coomera shopping precinct. Median age is 29, which says a lot about the demographic.",
    climate: "Subtropical northern Gold Coast climate — warm to hot year-round, with a wet season from November through March. Coomera's inland position means slightly higher summer temperatures than the coastal Gold Coast suburbs, with less sea breeze moderation. Afternoon thunderstorms are common through summer, with some significant hail events historically affecting the northern Gold Coast growth corridor. Annual rainfall around 1500mm.",
    council: "Gold Coast City Council",
    region: "Northern Gold Coast",
    tradeNotes: {
      "Electricians": "Coomera's modern housing estate stock means electrical work is predominantly upgrades and additions rather than aged infrastructure — solar PV systems are extremely common in this part of the Gold Coast, battery storage is growing, and EV charger installations are an increasing proportion of residential jobs. Large four-bedroom homes with pools drive high electrical load requirements.",
      "Plumbers": "New builds and post-construction plumbing service are the dominant work types in Coomera. The large family homes have significant plumbing loads — multiple bathrooms, large hot water systems, pools, and irrigation. Heat pump hot water systems are replacing original electric storage units on homes hitting 10+ years. Flood-aware drainage design matters for properties near Coomera River and its tributaries.",
      "Builders": "Gold Coast City Council's planning scheme flags parts of Coomera as subject to flood overlay constraints near the Coomera River. NCC climate zone 2 (subtropical) cyclone provisions apply to all new construction on the Gold Coast. The train station precinct at Coomera has been identified for transit-oriented development including higher density residential, which is an emerging work type for builders in the area.",
      "Painters": "Coomera's humid subtropical climate means mould growth on exterior surfaces — particularly on south and east facing rendered walls and under eaves — is an ongoing maintenance issue for estate housing. Quality exterior acrylic with anti-mould additives performs significantly better than budget paint in this climate. Many estate homes approaching 10-15 years are entering their first full repaint cycle.",
      "Pest Control": "Subterranean termite risk is significant across the northern Gold Coast growth corridor, and Coomera's proximity to natural waterway corridors and remnant vegetation adds to the baseline pressure. AS 3660.1 management systems are required for new construction, but the quality and condition of those systems should be verified on older estate housing. Annual inspections are strongly advisable.",
      "Landscapers": "Coomera gardens reflect the suburb's family-oriented young demographic — practical outdoor spaces, pools, lawn areas for kids, and shading trees that would take decades to establish on cleared estate land. Fast-growing tropical shade trees are popular but need selection to avoid storm damage risk. Council's vegetation clearing provisions apply, and proximity to Coomera River corridors means riparian vegetation protections matter in lower sections.",
    },
  },

} as const;
