// =============================================================================
// TRADEREFER CONTENT — BATCH 07
// Suburbs 61–70
// Research-backed, AU-specific content
// =============================================================================

"brunswick-east": {
    housing: "Brunswick East is inner north Melbourne done properly — the suburb sits in the Merri-bek council area about 5km from the CBD, and the housing reflects every era of Melbourne's inner-city growth in a tight geographic space. The oldest streets near Nicholson Street have Victorian terraces and miners' cottages from the 1870s–1890s, solid brick and sometimes iron-lace, the same stock you see in Fitzroy and Carlton. The 1910s–1930s added Edwardian bungalows and weatherboard cottages further back. Post-war, not much changed — Brunswick East escaped the worst of the 1960s flat-building wave that hit the eastern suburbs. More recently, townhouse infill and apartment development along Sydney Road and Lygon Street have added density. The suburb has a notably high rental proportion, around 55%, which shapes the renovation and maintenance market.",
    climate: "Inner north Melbourne — the Merri Creek corridor runs along the eastern edge and creates a thin green buffer, but the suburb is otherwise urban and fully exposed to Melbourne's classic four-season variability. Summer here gets genuinely hot when the northerly comes in, and the urban heat island effect from the density makes it hotter than the suburbs with more canopy cover. The sea breeze from the bay usually arrives mid-afternoon and drops the temperature quickly. Winter is cool and grey with the typical Melbourne overcast.",
    council: "Merri-bek City Council",
    region: "Inner North Melbourne",
    tradeNotes: {
        "Building": "The Victorian and Edwardian housing stock in Brunswick East sits inside Merri-bek's Heritage Overlay — any external alterations on listed homes require council assessment, and Merri-bek has been reasonably active in applying heritage protections to the older residential streets. Builders working on period terrace renovations here need to be familiar with the permitted alterations under the relevant heritage controls.",
        "Plumbing": "The older terrace and cottage stock has in many cases had four or five generations of plumbing modifications layered over original lead or early-galvanised supply lines — tracing services through these homes is complicated work, and the combination of very old supply pipes with post-war cast iron drainage creates a complex picture that doesn't yield to simple scoping.",
        "Electrical": "The high rental proportion and the age profile of the housing stock means Brunswick East electricians encounter a consistent volume of outdated switchboards and insufficient circuit protection — safety switch (RCD) installations and switchboard upgrades on pre-1980s rentals are a regular workload here.",
    },
},

"diamond-creek": {
    housing: "Diamond Creek is one of those Melbourne fringe suburbs that genuinely still feels like a township — 23km north-east of the CBD, and the valley setting along Diamond Creek itself gives it a character that's hard to replicate on the flat western plains. The bulk of the suburb is 1970s–1980s suburban brick veneer on generous 700–900 sqm blocks, built when the Eltham line commuter market opened up this part of Nillumbik. The older village core near the main street has some earlier 1940s–1950s weatherboard homes. The surrounding green wedge land means there hasn't been much estate development — this suburb has a finite character rather than the sprawl you see in the growth corridors.",
    climate: "Nillumbik Shire is in Melbourne's green wedge to the north-east, and the valley topography creates a distinct microclimate — cooler in summer than the flat northern suburbs, but also more variable in winter, with cold air pooling in the lower creek valley on still winter nights. The surrounding Diamond Creek Bushland Reserve and Kinglake National Park proximity make fire weather a genuine consideration — the Black Saturday 2009 fires burned right up to the edge of the northern suburbs, and the region has High BAL ratings for many properties on the outer edges.",
    council: "Nillumbik Shire Council",
    region: "North-East Melbourne / Nillumbik",
    tradeNotes: {
        "Building": "Nillumbik Shire's bushfire overlay is one of the most significant planning considerations in Diamond Creek — BAL (Bushfire Attack Level) ratings apply to a large proportion of properties, and any new construction or addition within a BAL zone requires compliant materials, window glazing, decking specifications, and setbacks that substantially exceed standard suburban build costs. BAL-29 and BAL-40 ratings are not uncommon on the semi-rural fringe streets.",
        "Landscaping": "Diamond Creek's location in Nillumbik's green wedge means the council's Vegetation Management Policy is actively applied — significant native tree removal requires council consent, and the riparian vegetation along Diamond Creek is subject to the Yarra Ranges Regional Conservation Strategy obligations. Landscaping in fire-prone zones also requires low-fuel-accumulating species adjacent to structures rather than the heavily planted suburban garden style.",
        "Pest Control": "The creek corridor and surrounding bushland create consistent subterranean termite pressure in Diamond Creek — established Eucalyptus in the reserve corridors provide ideal colony habitat, and Coptotermes colonies regularly foraging into the 1970s–1980s timber-subfloor homes in the valley streets. Annual inspections in this suburb are not optional for any home with timber framing or sub-floor.",
    },
},

"dingley-village": {
    housing: "Dingley Village is a quietly self-contained suburb in Melbourne's south-east — 23km from the CBD, governed by Kingston, and with a very specific development history. Urbanisation here started in earnest in the early 1960s and the bulk of the housing stock was built between 1965 and 1985: standard three-bedroom brick veneer on around 650–750 sqm, the Kingswood Golf Club running along the eastern edge providing a green buffer that's kept the suburb's character more tightly residential than some equivalent-era developments. The 'village' name isn't just marketing — the suburb genuinely has a contained, settled feel because the green wedge designation to the east prevented the outward sprawl that swallowed similar suburbs. Not a lot of post-1990 development.",
    climate: "South-east Melbourne — the Port Phillip Bay influence is noticeable here and the Dandenong Creek corridor nearby provides some additional moisture. Summers are warm with generally reliable afternoon sea breezes from the south-west. Winters are cool and wet with the typical Melbourne grey overcast. Significantly less temperature extreme than the northern and western suburbs on the hottest days.",
    council: "City of Kingston",
    region: "South-East Melbourne / Kingston",
    tradeNotes: {
        "Roofing": "The 1965–1985 housing stock in Dingley Village carries a large proportion of original Marseille terracotta roof tiles — now 40–60 years old, many are cracked at the lugs and the ridge capping mortar has failed on the older installations. The south and east-facing aspects on some slopes also carry significant moss and lichen accumulation that accelerates tile degradation if left untreated.",
        "Concreting": "Kingston Council's reactive clay soils underlie much of Dingley Village's residential area — the grey sandy clay that characterises the Port Phillip Bay coastal plain requires proper control joints and adequate base compaction to manage seasonal movement in driveways and paths. Original 1960s–1970s concrete that's reached the end of its life is a steady replacement demand in this suburb.",
        "Landscaping": "The established Dingley Village blocks have decades of garden development — mature trees, old concrete edging, original irrigation systems — and the renovation work here tends to involve working around established root systems and existing structures rather than the blank slate of newer estates.",
    },
},

"canberra-cbd": {
    housing: "Canberra CBD — officially the suburb of Canberra in the ACT — is a planned city centre of an entirely different character to Sydney or Melbourne's CBDs. Walter Burley Griffin's 1912 competition-winning design set out a landscape-integrated city, and the parliamentary triangle, lake, and surrounding institutions still define the structure. Residential in the strict CBD sense is limited — there are apartment towers along Northbourne Avenue and some residential pockets, but the dominant character is government, institutional, and commercial. The National Triangle area has the Parliament House, national cultural institutions, and the formal garden precincts that no other Australian city centre can match. What residential stock exists ranges from 1990s purpose-built apartments to more recent mixed-use developments near City Hill.",
    climate: "Continental ACT climate — no coastal influence whatsoever. Canberra's CBD gets genuine winter cold, with overnight temperatures regularly dropping to -5°C or below and frosts occurring from May through August. Summer is warm to hot with very low humidity. The lake provides a modest microclimate effect around the CBD foreshore but doesn't meaningfully moderate the overall continental extremes. The open planned parkways and wide roads mean wind can be fierce across the open spaces in winter.",
    council: "ACT Government",
    region: "Canberra CBD / Parliamentary Triangle",
    tradeNotes: {
        "Building": "Development in the Canberra CBD falls under the National Capital Authority's design requirements for National Land — the NCA has jurisdiction over the Parliamentary Zone and City Hill areas, and development on Territory Land is subject to the ACT Planning Authority's rules. Any significant building work in the CB area needs to navigate both NCA and ACT Planning requirements, which can require more pre-application consultation than purely state or territory-governed CBDs.",
        "Electrical": "The mix of 1970s–1990s government office buildings that have been converted to residential or mixed use in Canberra's CBD fringe creates a specific electrical maintenance workload — aging switchgear, BMS upgrades, and compliance upgrades to fire detection systems under AS 1670.1 are consistent demands across the government precinct buildings.",
    },
},

"cranbourne-east": {
    housing: "Cranbourne East is the Casey growth corridor doing what the Casey growth corridor does — flat, fast, and relentless. The suburb is about 50km south-east of the CBD and the development here is almost entirely post-2005, with the majority of current housing being 2010s brick veneer and lightweight steel frame on 350–500 sqm lots. Casey Fields, the major sporting precinct, sits within the suburb. The masterplanned estates dominate: curved streets, neighbourhood parks on a grid, the identical footprint of display home village streetscapes. It's not finished yet — active development is still running on the western and southern fringes as more PSP (Precinct Structure Plan) land is released.",
    climate: "South-east Melbourne fringe, 50km inland — the coastal moderating effect is minimal here. Summer heat is more extreme than inner Melbourne and the flat agricultural land that surrounds the newer estates provides no topographic shelter from northerly heat events. Winter frosts occur regularly. The Western Port Bay influence is very faint from this distance. The almost complete absence of mature street tree canopy in the newest streets makes summer temperatures noticeably higher than in established Melbourne suburbs.",
    council: "City of Casey",
    region: "South-East Melbourne Growth Corridor",
    tradeNotes: {
        "Building": "Cranbourne East's new housing stock is within the statutory warranty period under the Domestic Building Contracts Act 1995 — building practitioners here work heavily in new construction completion, variation work, and the early defect rectification market. The volume of houses built by large project home builders means defect claims follow predictable patterns: waterproofing failures in wet areas, movement in concrete slabs on expansive clay, and roof penetration sealing are the common ones.",
        "Landscaping": "New Cranbourne East estates have stripped topsoil during construction and replaced it with compacted clay fill — standard establishment practice in a brand-new garden is to bring in topsoil and organic amendment before anything will thrive. The total absence of established shade trees also means irrigation needs are higher here in summer than in comparable blocks in established suburbs.",
        "Solar & Energy": "The combination of new NCC-compliant homes (solar-ready conduit runs are standard), extreme summer heat, and a demographic heavily skewed toward young families watching energy bills creates a very active solar installation market in Cranbourne East. Battery storage adoption is also higher in these outer growth estates than in inner suburbs.",
    },
},

"gungahlin": {
    housing: "Gungahlin is Canberra's newest town centre — the ACT Government designated it as the fourth Town in 1991 and the development that followed was comprehensive, planned, and fast. Almost every house in Gungahlin was built between the mid-1990s and 2020s, which gives the suburb an unusual uniformity of age for a Canberra suburb: double-brick construction (the ACT standard), two-storey family homes on 400–600 sqm blocks, with consistent community facility planning. The light rail line to the city opened in 2019 and has accelerated medium-density apartment development near the town centre. Gungahlin is now the ACT's most populous district.",
    climate: "Northern Canberra — the ACT continental climate in full. Winters are cold with regular frosts and occasional snow days, summer is warm to hot and dry with the UV intensity that comes with 578m elevation and minimal atmospheric haze. The open planned suburbs of Gungahlin have limited mature tree canopy by comparison to older Canberra inner suburbs, which makes summer temperatures feel more extreme. The northerly fringe suburbs of Gungahlin get exposed to the Monaro wind channel on the worst winter days.",
    council: "ACT Government",
    region: "Northern Canberra / Gungahlin District",
    tradeNotes: {
        "Insulation": "Gungahlin's ACT continental climate — genuine cold winters and hot summers — combined with 1990s–2000s housing stock built to minimum standards of that era means there's a meaningful insulation upgrade market here. The ACT Government's Sustainable Household Scheme has subsidised insulation and other energy upgrades, and the double-brick construction typical in the ACT creates different thermal challenges to Melbourne brick veneer — the thermal mass of double brick is valuable if the building is well-insulated, but the older homes often aren't.",
        "Solar & Energy": "The ACT Government's reverse-auction renewables scheme has driven very high solar uptake in Canberra, and Gungahlin's new housing is well-placed for rooftop solar — good solar angles on most roofs, strong government incentives through the Sustainable Household Scheme, and an educated population familiar with the economics. Battery storage adoption is growing quickly in this market.",
        "Landscaping": "Gungahlin's young housing stock means gardens are still in early stages of maturation — the ACT Government's street tree program has been active in the district, but private gardens are often limited to the builder-grade landscaping that came with the house. The high UV and cold winter cycle in Canberra demand different plant selection to the coastal cities, with drought tolerance and frost hardiness both being necessary rather than either/or.",
    },
},

"humpty-doo": {
    housing: "Humpty Doo is the Northern Territory at its most distinctive — a rural-residential locality about 40km south-east of Darwin, sitting in the Litchfield municipality. Most residential properties here are on five-acre rural blocks rather than suburban allotments, and the housing reflects the NT's post-Tracy rebuild era: 1970s–1980s lowset and highset homes, many in lightweight construction, some in more recent elevated timber frame style suited to the tropical environment. There's nothing like Humpty Doo anywhere in the southern states — it's genuinely rural but close enough to Darwin to commute, which attracts a demographic that wants space and lifestyle over suburban convenience. The mango farms, horse properties, and occasional water buffalo sighting are part of the deal.",
    climate: "Tropical wet/dry — same climate as Darwin but with less coastal moderation and more exposure to the monsoonal system. The wet season is intense here: Humpty Doo sits in the Adelaide River flood plain and serious wet season flooding of the lower-lying roads and properties is a genuine event, not just a theoretical risk. The dry season is magnificent. Year-round temperatures are warm to hot; the UV is relentless; and the combination of moisture and warmth during the wet season creates the most demanding biological environment for buildings in Australia.",
    council: "Litchfield Council",
    region: "Darwin Rural Fringe / Litchfield",
    tradeNotes: {
        "Pest Control": "Humpty Doo's tropical climate and rural block sizes create some of the most severe termite conditions in Australia — Mastotermes darwiniensis, the giant northern termite, is endemic to the Northern Territory and is capable of structural damage to poorly treated buildings that has no parallel in southern Australia. Pre-construction soil treatment to AS 3660.1 is mandatory under the NT Building Code, and post-construction annual inspections are essential in this environment. The large block sizes and established native vegetation provide ongoing colony habitat right next to residential structures.",
        "Solar & Energy": "The Territory's strong and consistent year-round solar resource makes Humpty Doo's five-acre blocks excellent solar generation sites — and the year-round air conditioning demand (unlike southern cities where it's seasonal) makes the economics extremely clear. Battery storage adoption on rural NT blocks is also higher than metropolitan averages because grid reliability in the rural Litchfield network can be variable during wet season storms.",
        "Building": "All construction in the NT must meet the cyclone wind loading provisions of the NCC, which apply territory-wide regardless of distance from the coast — Humpty Doo is far enough inland to be outside the worst cyclone intensity zone but still requires engineering-compliant roof tie-down and structural design. The rural block setting also creates access and logistics challenges for trades doing deliveries during the wet season when roads can become impassable.",
    },
},

"launceston-cbd": {
    housing: "Launceston is Australia's third-oldest city, and the CBD reflects that age with a genuinely remarkable Victorian and Edwardian built heritage — sandstone and brick commercial buildings from the 1870s–1910s, terrace houses with wrought-iron balconies on the residential streets closest to the city grid, and a level of intact 19th-century streetscape that Hobart doesn't quite match. The residential pockets within and immediately around the CBD have a mix of this Victorian terrace stock alongside 1950s–1960s post-war brick homes and more recent apartment conversions of former commercial buildings. The Tamar River defines the northern edge and provides a scenic backdrop that makes Launceston's CBD location quite different from inland Victorian cities.",
    climate: "Northern Tasmanian river valley — Launceston's position at the junction of the North Esk, South Esk, and Tamar rivers creates a distinctive microclimate. The valley can trap cold air in winter, and Launceston CBD is one of the most frost-prone city centres in Australia. Fog events in the valley in autumn and spring are common. Summer is pleasant and warm. The prevailing westerly weather that dominates Tasmania is somewhat sheltered by the surrounding ranges, making Launceston drier than the western TAS coast but still with meaningful winter rainfall.",
    council: "City of Launceston",
    region: "Launceston CBD / Northern Tasmania",
    tradeNotes: {
        "Building": "Launceston's Victorian CBD is on the Tasmanian Heritage Register and the City of Launceston's Local Heritage Register — any external works on registered properties must comply with the Heritage Tasmania guidelines and typically require heritage officer consultation. Sandstone and brick masonry work is common here in a way that's rare elsewhere in Australia, and builders need specific skills in lime mortar repair and masonry conservation that standard residential builders don't typically carry.",
        "Painting": "The 19th-century commercial and residential buildings in inner Launceston almost universally have lead-based paint in their earlier applied coats — exterior painting work on pre-1970 buildings should follow AS 4361.2 and comply with Work Safe Tasmania's lead paint Code of Practice. The sandstone facades that are a feature of Launceston's heritage buildings also require breathable coating systems that are compatible with the masonry substrate.",
        "Plumbing": "The older residential stock around the CBD fringe has lead supply lines and early cast-iron drainage in many cases — Launceston's post-war housing in the residential blocks adjacent to the CBD frequently needs full plumbing system replacement rather than piecemeal repair. The very cold winter temperatures in the valley create specific risk of pipe freeze damage in under-floor and wall cavities on exposed southern aspects.",
    },
},

"bruce": {
    housing: "Bruce is a mid-Canberra suburb in the Belconnen district — gazetted 1968, built out through the 1970s and 1980s, and notable now for the concentration of institutional uses that have accumulated here. The Australian Institute of Sport, the University of Canberra, and the Canberra Stadium all sit in Bruce, and the residential fabric around these major institutions reflects the planning of the era: medium-density townhouses and duplexes built to ACT Government spec, some ACT Housing units from the 1970s, and the double-brick detached homes on 600–700 sqm blocks that are standard Belconnen-era Canberra. It's a suburb that's somewhat dominated by its major facilities and the traffic that goes with them, but the residential areas on the quieter streets retain a settled Canberra suburban feel.",
    climate: "Belconnen district of Canberra — ACT continental climate, full stop. Cold winters, proper frosts from April through September, occasional snow. Hot and dry summers with very low humidity. The Belconnen creek corridor and the nearby Ginninderra Wetlands provide some local habitat value but don't significantly moderate the climate. The stadium and AIS precinct create some urban heat island effect in the immediate vicinity.",
    council: "ACT Government",
    region: "Belconnen / Northern Canberra",
    tradeNotes: {
        "Insulation": "Bruce's 1970s–1980s double-brick housing stock is thermally challenging in the ACT's cold winters — double brick has significant thermal mass which works well if the building is properly insulated, but the original 1970s homes typically have inadequate ceiling insulation and no wall insulation. The ACT Government's Sustainable Household Scheme has provided retrofit insulation incentives that have seen meaningful uptake in the Belconnen district.",
        "Electrical": "Bruce's institutional precinct — the AIS, UC, and stadium — generates significant commercial electrical maintenance demand around the suburb, while the residential stock carries the typical Canberra 1970s–1980s electrical profile: older switchboards, sometimes undersized for modern appliance loads, and limited RCD protection on pre-1990s homes. Safety switch upgrades are a consistent residential workload here.",
    },
},

"docklands": {
    housing: "Melbourne Docklands is one of the biggest urban renewal projects in Australian history — what was derelict industrial port land in the early 1990s became a planned inner-city suburb of apartment towers, waterfront promenades, and corporate campuses from the late 1990s onward. Around 98% of residents live in apartments. The development happened in phases and the architectural quality is variable — the 2000s-era towers are now reaching a maintenance cycle, while the 2010s and 2020s buildings are still relatively new. Victoria Harbour is the centrepiece and the waterfront faces of Collins Street, the NewQuay precinct, and the Yarra's Edge development define the suburb. There's essentially no pre-2000 housing stock here.",
    climate: "Western CBD Melbourne, Victoria Harbour waterfront — the harbour creates real maritime conditions that the CBD blocks don't experience. Wind across the water can be considerable, particularly on the western side of the development. The harbour orientation means some precincts get excellent winter sun while others are in the shade of the tower developments. Melbourne's characteristic southerly change comes across the bay and hits the Docklands waterfront early and directly. Salt air influence from the harbour is a factor for exterior building maintenance.",
    council: "City of Melbourne",
    region: "Melbourne CBD / Docklands",
    tradeNotes: {
        "Building": "The volume of strata apartment buildings in Docklands — many now 15–25 years old — is entering a significant maintenance and upgrade cycle: facade inspections, waterproofing of basement carparks and planters, lift and BMS replacements, and fire safety system upgrades under the NCC. Owners corporations in Docklands are major clients for building practitioners with commercial and high-rise strata experience.",
        "Electrical": "The density and age spread of Docklands apartment towers creates a specialist commercial electrical maintenance market — Building Management System updates, emergency lighting compliance testing under AS 2293, smart metering installations, and common area upgrades across buildings that range from late-1990s first-generation smart buildings to 2020s fully integrated systems. Residential electricians without high-rise strata experience will find this work requires unfamiliar systems and compliance frameworks.",
        "Air Conditioning & Heating": "The harbour-facing orientation of many Docklands towers creates HVAC challenges — the western and northern harbour aspects get very different solar loading to the sheltered eastern sides, and the wind exposure affects centralised mechanical ventilation systems. Building-wide HVAC maintenance contracts are the dominant work type here rather than individual unit split system installations.",
    },
},
