// SUBURB_CONTEXT entries — Batch 15 (suburbs 141–150)
// Suburbs: ashmore, bentley, cranbourne-west, hurstville, labrador,
//          lane-cove, newstead (Launceston TAS), rocklea, waurn-ponds, brunswick-west

export const SUBURB_CONTEXT_BATCH_15 = {

  "ashmore": {
    housing: "Ashmore is one of the Gold Coast's older, more established residential suburbs — sitting about 9km from Surfers Paradise and bounded by the Nerang River and Pacific Motorway. The suburb has genuine character from its rolling terrain and elderly street trees, which set it apart from the flat estate suburbs further north. The housing stock is predominantly 1960s-80s brick homes on generous allotments, with a mix of acreage properties, villas, and townhouses scattered through the suburb. Owner-occupation sits at nearly 70%, which reflects the settled, family-oriented nature of the place.",
    climate: "Subtropical Gold Coast climate at a slightly elevated inland position. Hot, humid summers with afternoon thunderstorms common through the wet season (November-March). Summer days in the low-to-mid 30s with high humidity. The afternoon sea breeze from the east reaches Ashmore most days, which moderates the heat compared to the far western suburbs. Winters mild, dry, and genuinely comfortable. Annual rainfall around 1600mm.",
    council: "Gold Coast City Council",
    region: "Central Gold Coast",
    tradeNotes: {
      "Electricians": "Ashmore's 1960s-80s housing generation is hitting the range where switchboard upgrades and safety switch compliance are regular requests. The mix of brick family homes and older villa complexes creates varied work types — residential switchboard replacements, body corporate common property upgrades, and the increasingly common solar PV and battery storage installations.",
      "Plumbers": "The 1960s-70s housing in Ashmore's older sections commonly has galvanised supply and original drainage stacks — both of which generate replacement work as homes are renovated or change hands. The subtropical climate drives strong demand for solar hot water and heat pump systems replacing electric storage units that have reached end of service life.",
      "Builders": "Gold Coast City Council's planning scheme applies NCC cyclone-region provisions (Region C) across all Gold Coast construction. The older villa and unit complexes in Ashmore often have body corporate approval processes for renovation work affecting common property. The ACO and drainage provisions for the low-lying sections near the Nerang River need to be confirmed on flood-sensitive lots.",
      "Painters": "The subtropical UV and humidity combination in Ashmore means exterior paint on the older brick homes — particularly on shaded south and east-facing walls — develops mould growth that needs biological treatment before repainting. Quality exterior acrylics with anti-mould inhibitors make a practical difference to paint life in this climate.",
      "Pest Control": "Subterranean termite activity is consistent throughout the Gold Coast's established residential suburbs, and Ashmore's mix of older homes, elderly street trees, and generous garden allotments provides ideal foraging conditions. Annual AS 3660.2 inspections are the practical standard, and the older villa complexes often need body corporate-level termite management programs.",
      "Landscapers": "Ashmore's rolling terrain and established tree canopy create good conditions for productive, attractive private gardens. The subtropical climate supports rapid plant establishment. Gold Coast City Council's vegetation clearing provisions apply to significant trees, and some of the older Ashmore blocks have significant fig trees and other mature species that can't be removed without approval.",
    },
  },

  "bentley": {
    housing: "Bentley is an inner southeastern Perth suburb 8km from the CBD, shared between the City of Canning and a small portion of the Town of Victoria Park. The State Housing Commission began building in the area from 1944, constructing nearly 1,000 social housing units over four decades — a legacy that gives parts of Bentley a more mixed tenure character than most inner Perth suburbs. Post-war character homes from the 1940s-50s sit alongside this early social housing stock, and the presence of Curtin University and Technology Park on the suburb's southern edge has created a younger, more transient demographic in some sections.",
    climate: "Mediterranean Perth climate, slightly inland. Hot dry summers with January and February regularly reaching 38-40°C. The Fremantle Doctor sea breeze reaches Bentley most summer afternoons and provides meaningful relief. Winters mild and wet — 800-850mm annual rainfall concentrated between May and September. The suburban heat island effect is more pronounced in Bentley's densely-built sections than in the leafier inner-city suburbs.",
    council: "City of Canning",
    region: "Inner South Perth",
    tradeNotes: {
      "Electricians": "The post-war State Housing Commission stock in Bentley from the 1940s-60s has electrical infrastructure that's well past its design life in many dwellings — ceramic fuse boxes, pre-RCD circuits, and surface-run cable in some of the older stock. Curtin University's technology park precinct generates commercial and IT infrastructure electrical work that's a different market segment but geographically nearby.",
      "Plumbers": "Bentley's older housing stock has galvanised and early copper supply that generates steady replacement work as homes are maintained or renovated. The social housing stock has had progressive upgrade programs through METRONET and Housing Authority maintenance contracts. The Curtin University campus is a significant source of commercial plumbing maintenance work.",
      "Builders": "City of Canning supports medium-density infill development in Bentley, particularly around the bus rapid transit and train station precincts. Building and Energy WA licensing requirements apply across all residential construction. Asbestos management is a live issue in the 1940s-60s social housing stock — pre-works asbestos surveys are required before renovation work starts.",
      "Painters": "Bentley's post-war housing stock from the 1940s-50s should be presumed to contain lead paint unless proven otherwise. The AS 4361.2 lead paint assessment process is standard before surface preparation. Asbestos-cement sheeting is also common in the older sections — painters need to be clear on their obligations around asbestos identification and referral for licensed removal.",
      "Pest Control": "Building and Energy WA requires termite management systems for all new Perth construction, but Bentley's older 1940s-60s housing predates these requirements. The combination of sandy soils, mature garden trees, and timber-framed construction in the older sections creates standard Perth subterranean termite risk. Pre-purchase inspections on older stock are strongly advisable.",
      "Landscapers": "Perth's low annual rainfall and Bentley's sandy soils mean water-wise garden design is practical necessity rather than preference. The City of Canning supports water-wise garden schemes and has rebate programs for irrigation efficiency upgrades. The Curtin University campus and Technology Park create some commercial landscaping and grounds maintenance contracts in the area.",
    },
  },

  "cranbourne-west": {
    housing: "Cranbourne West is one of Melbourne's fastest-growing outer southeastern suburbs — a City of Casey suburb 40km from the CBD where the population more than doubled between 2011 and 2021, reaching around 20,000 people. The housing is entirely modern: estate-built homes from 2005 onwards, almost exclusively single and double-storey brick veneer on 350-500sqm lots. Over 83% of dwellings are separate houses, and most of them were built in the last 15 years. The median age is 32, which says a lot about the demographic — young families, often with mortgages over $1800 per month.",
    climate: "Melbourne's southeastern suburban climate without coastal moderation. Hot dry summers — January days regularly hitting 36-38°C and the heat can linger. Cold winters with frosts common from May through August, overnight lows to 3-5°C. Annual rainfall around 680mm. Cranbourne West's relatively treeless estate character means limited shade and a pronounced urban heat island effect in summer compared to older suburbs with mature canopy.",
    council: "City of Casey",
    region: "Outer Southeast Melbourne",
    tradeNotes: {
      "Electricians": "Cranbourne West's modern housing stock means electrical work is predominantly product upgrades and additions rather than aged infrastructure issues. Solar PV adoption is strong across the southeastern growth corridor, and battery storage and EV charger installations are growing rapidly. Large estate homes with pools and home theatre systems create significant load requirements that the original builder's switchboard was often not sized for.",
      "Plumbers": "New-build plumbing and post-construction service calls dominate the Cranbourne West market. The slab-on-ground construction standard in the growth corridor concentrates all plumbing services under the slab — drainage issues require saw-cutting and concrete reinstatement. Heat pump hot water system upgrades are increasingly requested as homeowners look to reduce running costs on original electric storage units.",
      "Builders": "City of Casey has active structure planning for the Cranbourne West growth area, and the suburb is still within its development phase in some sections. Builders should be across the applicable Development Contributions Plans — infrastructure contribution levies apply per lot. The NCC's energy efficiency requirements (Section J) for new residential construction are more demanding than they were when the earlier estates were built, affecting renovation and addition scopes.",
      "Painters": "Estate housing in Cranbourne West is relatively new, but the first wave of 2005-2015 builds is entering its first full exterior repaint cycle. Budget-grade exterior coatings on rendered homes are chalking and fading noticeably in Melbourne's climate, and quality repaint programs using proper primer and topcoat systems are showing clear life expectancy improvements.",
      "Pest Control": "City of Casey subterranean termite management requirements apply to all new construction, but the quality and condition of those AS 3660.1 systems on 10-15-year-old estate housing should be verified — particularly where homes are close to the creek corridors and remnant vegetation in Cranbourne Regional Park. Annual AS 3660.2 inspections are the practical recommendation.",
      "Landscapers": "Cranbourne West's estate homes often have minimal landscaping beyond builder-standard turf — the suburb's growth pace means many gardens were never properly designed. Outdoor entertainment areas, shade pergolas, pools, and productive garden spaces are the common first landscape project for settled homeowners. Native planting is appropriate given proximity to the Royal Botanic Gardens Cranbourne campus and its famous Australian Garden.",
    },
  },

  "hurstville": {
    housing: "Hurstville is the administrative centre of the Georges River Council area, 16km south of the Sydney CBD, and one of Sydney's most significant multicultural commercial hubs. The housing is a genuine mix spanning about a century of development: Federation-era homes and inter-war bungalows survive in the quieter residential streets, overlaid by post-war brick flats, 1970s-80s medium-density, and an ongoing wave of high-rise apartment construction that has fundamentally changed the suburb's skyline over the past decade. The Chinese-Australian community has shaped the suburb's retail and residential character substantially.",
    climate: "Southern Sydney climate at moderate distance from the coast. Warm, humid summers with occasional extreme heat days on westerly winds — typically mid-to-high 20s to low 30s. Winters mild and pleasant, rarely below 8°C overnight. Annual rainfall around 1250mm. The Georges River catchment to the south provides some moderating influence. The suburb's urban density creates a pronounced heat island effect in summer.",
    council: "Georges River Council",
    region: "St George Sydney",
    tradeNotes: {
      "Electricians": "Hurstville's mixed housing stock spans 100 years of electrical technology — from Federation-era homes with original knob-and-tube wiring through to high-rise apartment towers with sophisticated BMS systems. The ongoing high-density development around Hurstville station drives significant new building electrical fit-out work. The large concentration of retail tenancies along Forest Road and Park Road generates commercial electrical maintenance contracts.",
      "Plumbers": "The older housing stock has lead, galvanised, and early copper pipe that gets progressively replaced during renovation projects. The high-density apartment development wave creates strong demand for hydraulic engineers and licensed plumbers for large residential tower fit-outs. The concentration of Chinese-Australian-operated restaurants and retail in Hurstville's commercial centre creates commercial kitchen plumbing maintenance demand.",
      "Builders": "Georges River Council is in the middle of significant housing reform pressure — 8,246 new homes are planned across the LGA under the NSW Government's housing targets. The planning scheme provisions around Hurstville station are being reworked to accommodate higher density, which creates a complex and evolving approval environment for builders working in the area.",
      "Painters": "Lead paint is essentially certain in Hurstville's pre-1970 housing stock, which represents a substantial proportion of the older residential sections. The AS 4361.2 lead paint management protocol is standard practice before any surface preparation work. High-rise apartment repaints require swing-stage or BMU programs — the increasing number of towers from the 2000s-2010s are entering their first major exterior maintenance cycle.",
      "Pest Control": "The Georges River bushland interface creates meaningful subterranean termite pressure in Hurstville's older residential sections. Annual AS 3660.2 inspections are advisable on timber-framed homes, particularly where gardens have established trees and where the property boundary is near bushland. Cockroach and rodent management for the commercial strip is a steady ongoing service requirement.",
      "Landscapers": "Hurstville's apartment building common property landscaping is typically managed through strata maintenance contracts. The older residential streets have substantial established trees subject to Georges River Council's tree preservation provisions. The suburb's multicultural character creates demand for Asian-inspired garden design and kitchen herb gardens in the residential sections.",
    },
  },

  "labrador": {
    housing: "Labrador is a Broadwater-fronting Gold Coast suburb sitting between Southport and the Runaway Bay canal network, with a population of around 19,000. The housing is genuinely varied — original Queenslander-style homes from the 1950s-60s in the older residential streets, post-war fibro and brick cottages, and a growing layer of newer townhouses and mid-rise apartments fronting the Broadwater. Social housing makes up about 7% of the stock, slightly above the Gold Coast average. The suburb has a younger demographic median than the canal estates to the north, and a mix of long-term residents and newer arrivals.",
    climate: "Subtropical Gold Coast climate right on the Broadwater. The water frontage provides sea breezes and moderates the humidity somewhat. Hot, wet summers (November-March) with afternoon storms and daily humidity. Annual rainfall around 1500mm. Winter is genuinely lovely — dry, sunny, around 20-22°C. The Broadwater location means salt air exposure is a real maintenance consideration for materials facing the water.",
    council: "Gold Coast City Council",
    region: "Northern Gold Coast Broadwater",
    tradeNotes: {
      "Electricians": "Labrador's older 1950s-60s housing stock has switchboards and wiring that's well past its design life in the unrenovated sections. Salt air corrosion from the Broadwater affects external electrical fittings, switchboard enclosures, and air conditioning units on water-facing properties — marine-grade specifications and more frequent maintenance inspections are the practical standard near the water.",
      "Plumbers": "The original beach cottage and Queenslander stock in Labrador has galvanised supply and early drainage that generates replacement work as homes are renovated. The Broadwater-facing apartments and townhouses have hydraulic system requirements that need to account for the salt air environment — corrosion-resistant fittings and balustrade penetration details matter more here than in inland suburbs.",
      "Builders": "Gold Coast City Council's planning scheme applies coastal hazard and erosion setback provisions to Labrador's Broadwater-facing lots. The NCC cyclone-region provisions (Region C) apply across all Gold Coast construction. The mix of older Queenslander stock and newer medium-density development means builders need to be comfortable working across different construction eras and planning contexts.",
      "Painters": "Salt air from the Broadwater is the defining exterior paint challenge in Labrador — coatings on water-facing elevations and metal elements get significantly shorter life than the same products used inland. Anti-corrosion priming on all metal elements, quality marine-grade exterior coatings, and more frequent inspection cycles are the practical approach for Broadwater-facing properties.",
      "Pest Control": "The warm, humid subtropical climate and the moisture from the Broadwater create year-round pest activity in Labrador. Subterranean termite management in the older timber-framed stock — particularly the Queenslanders and fibro cottages — is essential. The elevated construction common in the area makes subfloor inspection access relatively straightforward, but the number of entry points is also higher.",
      "Landscapers": "Labrador's Broadwater frontage and waterway proximity create both opportunities and constraints for landscaping — salt-tolerant species are essential near the water, and council's vegetation protection provisions apply to the Broadwater foreshore areas. The older residential streets have established mango trees and tropical plantings that give the suburb its distinctive Gold Coast character.",
    },
  },

  "lane-cove": {
    housing: "Lane Cove is a bush-fringed Lower North Shore suburb 9km northwest of Sydney CBD, where apartments and freestanding houses coexist in roughly two-thirds and one-third proportions. The village character of the Longueville Road commercial strip and the extensive bushland of Lane Cove National Park on the suburb's margins give it a genuine sense of being close to the city and close to nature at the same time. Post-war brick homes and 1960s-70s apartment blocks dominate the older sections, with newer apartment buildings pushing the density up around the town centre.",
    climate: "Sydney's lower north shore climate — moderately humid, sea breezes from the north and northwest most afternoons. Summers warm, rarely extreme. Winters mild with overnight lows around 9-11°C. Annual rainfall around 1200mm with some concentration in summer storm events. The Lane Cove National Park provides genuine ecological presence and some microclimate moderating effects in the bushland-adjacent sections.",
    council: "Lane Cove Council",
    region: "Lower North Shore Sydney",
    tradeNotes: {
      "Electricians": "Lane Cove's mix of 1950s-70s post-war homes and apartments alongside newer buildings creates diverse electrical work — original switchboard upgrades in older residences, body corporate common property maintenance on ageing apartment blocks, and new building electrical fit-outs as infill development continues. The suburb's proximity to the tech and professional sector creates demand for home office infrastructure and smart home installations.",
      "Plumbers": "Post-war plumbing is standard in Lane Cove's older housing and apartment blocks — galvanised supply and early copper generate replacement work as properties are renovated. The Lane Cove National Park adjoining properties need to account for drainage and stormwater management at the bushland interface to avoid environmental compliance issues with Council.",
      "Builders": "Lane Cove Council applies Heritage Conservation Area protections to parts of the older townscape, and vegetation protection provisions across the suburb are among the strongest on the North Shore — Lane Cove has a very active tree preservation policy. Bushfire attack level (BAL) assessments apply on properties at the national park interface, and these can significantly affect material specifications and building envelopes.",
      "Painters": "Lane Cove's post-war housing has standard lead paint considerations — AS 4361.2 risk assessment before any surface preparation work is the industry standard. The national park interface properties can have moisture and biological growth issues on south-facing surfaces due to the shade and humidity from the adjacent bushland. Quality anti-fungal exterior finishes make a practical difference in these locations.",
      "Pest Control": "Lane Cove National Park creates real subterranean termite pressure on properties along the park boundary, and the suburb's extensive tree canopy provides ongoing foraging corridors throughout. Annual AS 3660.2 inspections on timber-framed homes are strongly advisable, particularly for properties backing onto the national park, Batten Reserve, or the bushland corridors near the river.",
      "Landscapers": "Lane Cove's bushland character is one of its defining assets, and the Council's tree preservation policy is robustly enforced — significant tree removal requires approval and is not always granted. Garden design that works with the bush character and supports the national park wildlife corridor is both appropriate and aligned with Council's expectations. Bush regeneration, native understory planting, and fire-aware design are relevant for park-adjacent properties.",
    },
  },

  "newstead": {
    housing: "Newstead is a quiet, established residential suburb 3km east of the Launceston CBD — an owner-occupier dominated area where three-bedroom homes on modest lots make up the majority of the stock. The suburb developed progressively through the post-war decades, and the housing reflects that: 1950s-70s brick veneer and weatherboard homes are the backbone, with some earlier stock and a scattering of recent infill. Owner-occupation sits at 66%, and the population is stable and slowly growing. It's unpretentious Launceston residential — solid, well-maintained, and without the pretensions of the hilltop suburbs.",
    climate: "Launceston's cool maritime climate — four distinct seasons with cold winters and mild summers. July nights regularly drop to 2-4°C and frosts are routine between May and September. Summers are warm and often very pleasant with low humidity, reaching 25-28°C on a good January day. Annual rainfall around 700mm spread through the year without a strongly wet season. The surrounding hills give Launceston a distinctive frost-hollow character that affects properties in the lower ground.",
    council: "City of Launceston",
    region: "Launceston",
    tradeNotes: {
      "Electricians": "Newstead's 1950s-70s housing has the standard array of ageing switchboards and pre-safety-switch wiring that generates upgrade work as homes are sold or renovated. Launceston's cold climate means heating loads are significant — heat pump installations and upgrade of electric storage heating to reverse-cycle systems are a common part of the local electrical workload.",
      "Plumbers": "The combination of old galvanised pipe runs and Launceston's cold winters creates both corrosion-based failures and occasional pipe freeze issues in exposed uninsulated sections. Hot water system replacements are frequent in the older 1950s-70s homes. The City of Launceston has periodic support for rainwater tank installations as part of water management programs.",
      "Builders": "The City of Launceston's planning scheme applies heritage protections to parts of the inner suburbs, and some of Newstead's older housing falls within heritage consideration zones. Bushfire risk applies to the escarpment-adjacent properties, though Newstead itself is relatively sheltered compared to the eastern hills suburbs. Builders in Launceston need to work with the cold climate building specifications that differ from mainland standards.",
      "Painters": "Launceston's cold, damp winters create real moisture-related paint failure in poorly ventilated homes — particularly on weatherboard homes where the wall cavities aren't effectively sealed. Mould and mildew on south-facing walls is the most common exterior maintenance issue. Interior condensation on cold walls in the colder months drives interior paint maintenance on a more frequent cycle than warmer-climate cities.",
      "Pest Control": "Tasmanian subterranean termite species (primarily Coptotermes acinaciformis) are active year-round despite the cold winters, and Newstead's established weatherboard and timber-framed housing provides the substrate they prefer. Annual AS 3660.2 inspections under Tasmania's pest management licensing requirements are strongly recommended, particularly for older unrenovated homes.",
      "Landscapers": "Launceston's cool climate supports beautiful cool-climate planting — ornamental cherries, deciduous oaks and elms, cool-climate roses, and vegetable gardens that thrive through the mild summers. Newstead's modest allotments suit productive gardens and practical outdoor spaces. Frost-aware plant selection and timing of establishment (spring planting is far safer than autumn for tender species) are the practical gardening realities in this climate.",
    },
  },

  "rocklea": {
    housing: "Rocklea is primarily an industrial suburb 9km south of Brisbane CBD, bordered by the Oxley Creek to the west. The residential component is genuinely small — a population of only around 1,700 people. What housing exists is mostly post-war to 1960s character on the streets away from the industrial zones, a legacy of wartime housing estates built for workers at the Rocklea Munitions Works (opened 1941). The suburb is dominated in character and land use by the Brisbane Markets (opened 1964) and the industrial and freight precincts that grew around them. Residential streets here feel distinctly embedded in an industrial context.",
    climate: "Humid subtropical Brisbane climate, southwest of the CBD. Hot, wet summers with the wet season concentrated from November through March. Annual rainfall around 1100mm. The Oxley Creek corridor creates localised flood risk that is among the most significant of any Brisbane suburb — Rocklea experienced major flooding in both 2011 and 2022, and flood overlay mapping affects virtually all development in the low-lying sections.",
    council: "Brisbane City Council",
    region: "Southern Brisbane",
    tradeNotes: {
      "Electricians": "Rocklea's industrial character means commercial and industrial electrical work is the dominant service requirement — three-phase power for cold storage, freight handling equipment, processing facilities, and the Brisbane Markets precinct. The small residential population generates standard post-war domestic electrical maintenance work, but the industrial sector is the primary electrical market in this suburb.",
      "Plumbers": "Commercial and industrial plumbing services for the Brisbane Markets, cold storage facilities, and the manufacturing precincts make up the bulk of the plumbing work in Rocklea. The residential section's older post-war housing has standard galvanised supply issues. Flood preparedness and stormwater management are significant considerations — properties in the Oxley Creek floodplain have experienced repeated major flood events.",
      "Builders": "Brisbane City Council's flood overlay mapping significantly constrains new construction and renovation in Rocklea — many properties sit within the defined flood level area, and floor levels, freeboard requirements, and flood-resistant construction techniques need to be understood by any builder working here. The industrial zone planning provisions govern most of the development activity.",
      "Painters": "The industrial character of Rocklea means commercial painting — factory floor coatings, industrial shed exteriors, warehouse fit-outs — is more relevant than domestic residential work. The small residential section has standard subtropical maintenance requirements, but the flood risk affects what investment owners are willing to make in properties that have been damaged repeatedly.",
      "Pest Control": "Rocklea's proximity to the Oxley Creek waterway corridor and the Brisbane Markets (with their produce and food waste) creates elevated rodent pressure alongside the standard subtropical termite risk. Commercial pest management contracts for the Brisbane Markets complex and surrounding industrial tenancies are significant and recurring.",
      "Landscapers": "The industrial character of Rocklea means commercial grounds maintenance — truck entry areas, loading dock surrounds, industrial site perimeter plantings — is more relevant than residential garden design. The residential section has modest older gardens that receive standard subtropical maintenance. Flood-aware planting in the low-lying sections near Oxley Creek makes native and flood-tolerant species the practical choice.",
    },
  },

  "waurn-ponds": {
    housing: "Waurn Ponds is a rapidly evolving suburb 10km south of Geelong's CBD in the City of Greater Geelong. The suburb has a split character: an established residential section around the Waurn Ponds Shopping Centre and Deakin University campus, with newer growth estates being progressively developed on the suburban fringe. Development Victoria has plans for around 400 new homes in the pipeline. The existing residential stock is a mix of 1980s-90s brick veneer homes and newer estate housing from the 2010s. The Deakin University campus brings a young, transient student population.",
    climate: "Geelong's coastal-influenced but not coastal climate — warmer and drier than the Bellarine Peninsula to the south, but not as extreme as inland Victoria. Summer days in the low-to-mid 30s with the You Yangs providing some shelter from the north. Winters are cool, occasional frosts, overnight lows around 4-7°C. Annual rainfall around 500-520mm — noticeably drier than Melbourne. The grass plains character of the Geelong hinterland means strong northerly winds are a feature on hot summer days.",
    council: "City of Greater Geelong",
    region: "Geelong Southwest",
    tradeNotes: {
      "Electricians": "Waurn Ponds' mix of 1980s-90s established homes and new growth estate housing means electricians see both older switchboard upgrades and new builder fit-out work. Deakin University's Waurn Ponds campus is a significant commercial electrical maintenance client. Solar PV adoption has been strong across Geelong's southern growth areas, and battery storage installations are growing.",
      "Plumbers": "The 1980s-90s established section has plumbing that's reaching end-of-service-life in places — galvanised supply in the older homes, hot water system replacements, and irrigation system upgrades are steady work. The new estate development creates ongoing builder-phase plumbing demand. The City of Greater Geelong's social housing program (20% of the Development Victoria pipeline homes) will add some public housing maintenance work.",
      "Builders": "City of Greater Geelong's growth area provisions govern the new estate development in Waurn Ponds. Development Contribution Plans apply per lot. The suburb's proximity to the You Yangs escarpment means some bushfire risk provisions apply to properties on the elevated fringe, and BAL ratings should be confirmed for any new construction in those areas.",
      "Painters": "Geelong's drier climate compared to Melbourne means exterior paint life is somewhat longer here. But the strong northerly winds in summer drive significant dust and UV exposure on north-facing elevations, and quality exterior coatings still make a noticeable difference on the established homes. The new estate housing is entering its first full repaint cycle on the older sections.",
      "Pest Control": "City of Greater Geelong subterranean termite populations are active across the suburban areas. Waurn Ponds' proximity to remnant native vegetation in the You Yangs regional park and the grassland reserves to the south creates background pest pressure. Annual AS 3660.2 inspections on timber-framed homes are the standard recommendation — particularly for the older 1980s-90s stock where barriers haven't been recently renewed.",
      "Landscapers": "Waurn Ponds' drier climate makes water-efficient garden design important — Council water restrictions have applied during dry summer periods historically. The new estate sections benefit from proper landscaping investment, as builder-standard turf establishes poorly in Geelong's grassland soils without irrigation support. Native plantings that complement the grassland character of the surrounding You Yangs parkland work particularly well.",
    },
  },

  "brunswick-west": {
    housing: "Brunswick West is an inner northern Melbourne suburb 6km from the CBD in the City of Merri-bek (formerly Moreland). The suburb has a genuinely interesting housing mix — Victorian and Edwardian terrace rows in the older eastern sections near Grantham and Shamrock Streets, interwar brick bungalows through the middle, and post-war brick veneer and fibro in the western sections near Moonee Ponds Creek. Light industrial land near the creek has been progressively converted to residential and mixed-use. It's a suburb with Italian, Greek, Indian, and Australian heritage communities living in close proximity, which gives the neighbourhood a particular character.",
    climate: "Melbourne's inner northern suburban climate. Four distinct seasons — hot summers, proper cold winters. January days occasionally pushing 40°C when northerlies blow, August nights down to 4-6°C with occasional frosts. Annual rainfall around 620mm spread reasonably evenly. Moonee Ponds Creek to the west provides a vegetation corridor that offers some relief from the urban heat island in the immediate surrounds.",
    council: "City of Merri-bek",
    region: "Inner North Melbourne",
    tradeNotes: {
      "Electricians": "Brunswick West's housing spans from pre-war to post-war, and the older Victorian and Edwardian sections have original wiring configurations that require careful handling — fabric-insulated cable, ceramic fuses, and in some cases original two-wire systems without earth conductors. The renovating homeowner market in the inner north drives demand for full rewires, switchboard upgrades, and smart home infrastructure installations.",
      "Plumbers": "The full range of plumbing eras is represented in Brunswick West — lead and galvanised in the older terrace sections, early copper in the mid-century housing, and modern PEX in recent renovations. The light industrial to residential conversion sites have specific hydraulic requirements around contaminated ground drainage management. Italian-Australian homeowners in the suburb often have outdoor kitchen and entertaining area plumbing requests.",
      "Builders": "City of Merri-bek applies Heritage Overlays to significant sections of Brunswick West's Victorian and Edwardian streetscapes, and the Neighbourhood Character Overlay covers broader areas of the suburb. Renovation and extension work in heritage areas needs to respond to the character provisions — additions that are out of scale with original housing are regularly refused or required to be redesigned. The Moonee Ponds Creek corridor is subject to floodway and land subject to inundation overlays.",
      "Painters": "Lead paint is near-certain in the older terrace and Edwardian sections of Brunswick West. The AS 4361.2 lead paint risk assessment and management process is the standard approach before any preparation work. Melbourne's cold winters can drive moisture ingress through the older single-skin brick terrace walls, creating surface staining and paint failure issues that recur if the source isn't addressed before repainting.",
      "Pest Control": "Subterranean termite activity is present throughout the inner north, and Brunswick West's older terrace and bungalow sections with established garden trees create the conditions they prefer. Annual AS 3660.2 inspections on timber-framed homes — particularly the older unrefined weatherboard sections near the creek — are the standard recommendation. The creek corridor also generates rodent management requirements.",
      "Landscapers": "Brunswick West gardens range from the tight courtyard-sized terrace backyards in the eastern sections to more generous post-war allotments in the west. City of Merri-bek's tree preservation provisions protect significant established trees, and the Italian-Australian community character drives demand for productive fruit and vegetable gardens that thrive in Melbourne's climate. Native plantings along the Moonee Ponds Creek corridor tie private gardens into the broader ecosystem.",
    },
  },

} as const;
