// SUBURB_CONTEXT entries — Batch 12 (suburbs 111–120)
// Suburbs: glebe, cockburn-central, golden-grove, golden-square,
//          palm-beach, randwick, surfers-paradise, arundel, box-hill-north, chermside

export const SUBURB_CONTEXT_BATCH_12 = {

  "glebe": {
    housing: "Glebe is one of Sydney's oldest residential suburbs, carved up into terrace lots as far back as the 1870s. The housing stock reflects that history — long rows of two-storey Victorian and Edwardian terraces, most of them 130+ years old, with ornate ironwork verandahs and tight footprints. A significant public housing precinct sits along the western edge, some blocks dating to the 1950s and 60s. More recent infill townhouses occupy the odd pocket, but the terrace character is overwhelming and protected.",
    climate: "Inner-city temperate Sydney climate. Summers run warm and humid, often pushing into the low-to-mid 30s, though sea breezes off Blackwattle Bay provide some relief in the evenings. Winters are mild — rarely below 8°C overnight. Annual rainfall sits around 1200mm, spread pretty evenly through the year. The area gets its fair share of summer storms rolling in off the harbour.",
    council: "City of Sydney",
    region: "Inner West Sydney",
    tradeNotes: {
      "Electricians": "Victorian and Edwardian terraces throughout Glebe commonly have undersized switchboards and original wiring runs that were never designed for modern loads — upgrading to 3-phase supply or adding EV charging circuits often requires a full panel replacement and cable rerouting through very tight ceiling cavities.",
      "Plumbers": "Cast iron and lead pipe is still running through a surprising number of Glebe terraces. When renovating bathrooms or kitchens, tradespeople regularly encounter original stacks that need condemning, alongside the complications of restricted access in terrace-style floor plans where there's no subfloor crawl space.",
      "Builders": "Heritage conservation overlays apply extensively across Glebe, managed through the City of Sydney LEP. Any external alterations — new skylights, rear additions, rooftop decks — require heritage impact assessment, and even internal works touching original fabric need documenting carefully before submission.",
      "Painters": "Given the age of the housing, lead paint is the default assumption not the exception. AS 4361.2 risk assessments are standard practice before any surface preparation in Glebe. Many properties also have significant damp penetrating the party walls, which shows up as peeling and staining within a few years if not properly treated first.",
      "Pest Control": "Subterranean termite activity is a real concern in Glebe, particularly in the older public housing blocks and the terraces with dense plantings around sandstone foundations. Annual inspections under AS 3660.2 make sense here, and older timber floor systems in unrenovated terraces regularly need full chemical barrier treatments.",
      "Landscapers": "Glebe gardens are almost universally small — most terrace lots have courtyard-sized rear yards, often shaded by neighbouring two-storey buildings. Maximising privacy, managing drainage on compact impervious surfaces, and working within council guidelines on tree removal are the main challenges. Rooftop gardens are becoming popular on converted terrace tops.",
    },
  },

  "cockburn-central": {
    housing: "Cockburn Central is genuinely new — the suburb name wasn't even approved until 2007, created when the Kwinana Freeway cut through what had been the western edge of Jandakot. The housing is modern by Perth standards: a mix of two-storey brick-and-tile homes built from the late 2000s onward, medium-density apartment complexes servicing the train station precinct, and mixed-use developments around the Cockburn Gateway shopping centre. Very little pre-2005 stock exists here.",
    climate: "Mediterranean Perth climate, so proper dry summers and mild wet winters. January and February regularly hit 38°C+ and the area is exposed to strong Fremantle Doctor sea breezes which arrive most summer afternoons and knock the heat back significantly. Winters are mild and fairly pleasant — rainfall is concentrated between May and September, around 750mm annually in this part of the southern suburbs.",
    council: "City of Cockburn",
    region: "Southern Perth Suburbs",
    tradeNotes: {
      "Electricians": "Cockburn Central's newer housing stock was built during the period when solar PV became mainstream in Perth — a large proportion of homes already have rooftop systems, and battery storage retrofits are increasingly common. Split-system installations and pool equipment wiring are regular jobs across the suburb.",
      "Plumbers": "Modern construction throughout, so the issues are typically product-specific rather than age-related. However, the slab-on-ground builds common in this area concentrate all plumbing services under the slab, meaning drainage issues require saw-cutting and careful relocation work.",
      "Builders": "City of Cockburn has active structure planning for the Cockburn Central precinct and ongoing medium-density infill policies. Builders working here need to be across R-codes compliance requirements, particularly for the higher-density residential zones around the station precinct.",
      "Painters": "Cockburn Central's hot, sunny climate means exterior paint on render and brick-veneer homes cops significant UV exposure. Quality exterior coatings with good UV stabilisers are worth the extra cost — cheaper paints chalk and fade fast. New apartment complexes in the precinct often need repaints within 8-10 years.",
      "Pest Control": "Perth's termite pressure is real across the southern suburbs. Building and Energy WA requires termite management systems for new construction, but older infill sites don't always have compliant systems in place. Pre-purchase inspections frequently turn up gaps.",
      "Landscapers": "Water-wise garden design is strongly encouraged by City of Cockburn, and many newer properties were landscaped with WELS-rated irrigation from the start. However, the sandy coastal plain soils retain almost nothing, so plant selection and irrigation scheduling need to account for very low water-holding capacity.",
    },
  },

  "golden-grove": {
    housing: "Golden Grove is Australia's first fully master-planned suburb — the development scheme ran from 1983 all the way to 2003, and the planned origins show in everything from the road layout to the housing density. Most homes are 1980s to early 2000s brick veneer, ranging from modest three-bedders on smaller lots in the earlier sections to larger four-bedroom family homes on the outer rings. The suburb sits in hilly terrain with native vegetation corridors threading through it.",
    climate: "Adelaide's northeastern Mediterranean climate — hot dry summers and cool wet winters, though the elevated terrain compared to the coastal plains means slightly cooler summer nights. January temperatures regularly exceed 38°C and heatwaves of 40°C+ are not unusual. Annual rainfall sits around 550-600mm, most of it falling between May and September.",
    council: "City of Tea Tree Gully",
    region: "Northeastern Adelaide",
    tradeNotes: {
      "Electricians": "The 1980s and early 1990s housing in Golden Grove was built during the era of ceramic fuses and early circuit breakers. Plenty of homes still have switchboards that pre-date modern safety switch requirements — upgrades are common when homeowners extend or renovate.",
      "Plumbers": "The original plumbing in 1983-1995 homes is reaching the end of its expected service life in many cases — galvanised copper supply pipes and early-generation hot water systems are frequently replaced on inspection. Water restrictions in SA mean rainwater tank plumbing is common too.",
      "Builders": "City of Tea Tree Gully design guidelines emphasise bushfire risk management given the proximity to native vegetation corridors. Builders and renovators should confirm BAL ratings before planning any additions, particularly on the outer lots backing onto reserve land.",
      "Painters": "The hilly position and hot summers mean exterior paint on the western and northern elevations of Golden Grove homes fades hard. The prevalence of brick veneer construction means render cracks and bond failures in cavity mortar joints are common on houses approaching 30-40 years old.",
      "Pest Control": "Subterranean termite pressure increases markedly in suburbs adjacent to native vegetation reserves. Golden Grove's native corridors make annual AS 3660.2 inspections strongly advisable — particularly for the older timber-framed homes that predate modern chemical barrier systems.",
      "Landscapers": "Water-wise native landscaping fits Golden Grove's character and climate perfectly. The hilly blocks often need earthworks and retaining to create usable garden spaces, and Council's tree protection overlays apply around the vegetation corridors threading through the suburb.",
    },
  },

  "golden-square": {
    housing: "Golden Square is the established inner-western suburb of Bendigo, sitting about 2km from the city centre. The housing is mostly 1950s to 1970s brick — solid cream brick and red brick homes on decent-sized allotments, the kind of Bendigo stock that's aged well and requires steady maintenance rather than overhaul. A handful of inter-war weatherboards survive in the older pockets closer to the town centre fringe. New social housing development has added some contemporary dwellings in recent years.",
    climate: "Inland Victoria climate — hot dry summers and cool, sometimes frosty winters. Bendigo averages around 250mm rainfall annually, making it one of the drier parts of regional Victoria. Summer maxima frequently top 38-40°C, and the area experiences northerly wind events that accelerate fire risk. Winter nights regularly drop to 2-5°C.",
    council: "City of Greater Bendigo",
    region: "Bendigo",
    tradeNotes: {
      "Electricians": "Post-war brick homes throughout Golden Square often have original switchboards with ceramic fuses and undersized metering — upgrading these is practically a rite of passage when any significant renovation work starts. The area also has a reasonable number of single-phase properties where homeowners are adding heat pumps and EV charging.",
      "Plumbers": "1950s-70s plumbing means galvanised pipe is standard behind the walls of a lot of Golden Square homes. When burst hot water services fail or kitchens get renovated, full replumbing is often the practical outcome. The City of Greater Bendigo also has rainwater tank rebate programs that drive tank installations.",
      "Builders": "The City of Greater Bendigo's Golden Square Structure Plan (updated 2022) identifies the suburb as an infill target zone with opportunities for medium-density development. Builders operating here should understand the R1 zone provisions and the requirements around neighbourhood character overlays in the older sections near the town centre.",
      "Painters": "Bendigo's hot summers and dramatic temperature swings between seasons are rough on exterior paintwork. Brick homes don't always need repainting externally, but the timber fascias, window frames, and eaves boards on 1960s-70s homes need attention every 8-12 years. Interior rendering on the older brick homes cracks seasonally and needs regular patching.",
      "Pest Control": "Subterranean termites are active throughout Bendigo — the combination of clay soils and hot summers suits them well. Golden Square's older timber-framed sections and the surviving weatherboard homes are particularly vulnerable, and pre-purchase inspections regularly find activity.",
      "Landscapers": "Bendigo's low rainfall means water-wise gardening is less a trend and more a necessity. Council water restrictions apply in dry summers, so drip irrigation and mulching are standard practice. Many Golden Square blocks have decent-sized yards from the post-war subdivision era, which suits veggie gardens and established native plantings.",
    },
  },

  "palm-beach": {
    housing: "Palm Beach QLD sits at the southern end of the Gold Coast, roughly halfway between Coolangatta and Broadbeach. The suburb built its reputation on a world-class surf break and a beachy village atmosphere. The housing ranges from original 1960s-70s beach cottages and fibro shacks (some still intact, many now replaced or renovated) through to modern two-storey rendered homes and a scattering of apartments close to the surf beach. It's a genuine mixed bag — modest workers' cottages on small lots sitting beside architect-designed contemporary builds.",
    climate: "Subtropical Gold Coast climate at the southern fringe — warm year-round, with the wet season from November through March bringing the bulk of annual rainfall (around 1600mm). Summer days hit the low 30s with high humidity; winter is dry and mild, hovering around 20-22°C. The suburb faces southeast and gets good ocean breezes, which helps on summer afternoons. Salt air exposure is significant this close to the surf beach.",
    council: "Gold Coast City Council",
    region: "Southern Gold Coast",
    tradeNotes: {
      "Electricians": "Salt air corrosion affects electrical installations throughout Palm Beach — external fittings, air conditioning units, and switchboard enclosures on ocean-facing properties need marine-grade specifications. Older fibro and weatherboard beach shacks being renovated frequently have undersized 1960s-70s switchboards that need full replacement before additional circuits can be added.",
      "Plumbers": "Original beach shacks from the 1960s-70s commonly have galvanised supply lines and basic drainage that was never designed for full-time habitation. When these properties change hands and get renovated, full replumbing is usually the starting point. The subtropical climate also drives solar hot water and heat pump demand — good ongoing replacement work across the suburb.",
      "Builders": "Gold Coast City Council's development controls apply coastal hazard and erosion setback provisions to lots near the beach and the Currumbin Creek corridor at the southern end. Renovation or new build projects should confirm applicable overlays early — flooding and coastal erosion mapping affects portions of the lower-lying sections.",
      "Painters": "The combination of subtropical UV, salt air, and high humidity means exterior paint in Palm Beach is working hard. Quality acrylic coatings with anti-mould additives are the baseline recommendation. Mould growth on south-facing walls and under eaves can appear within a single wet season if preparation and primer selection were inadequate.",
      "Pest Control": "Subterranean termite pressure is real in Palm Beach's older timber-framed beach cottages — the combination of tropical warmth, moisture from proximity to the ocean and creek systems, and aging timber creates ideal conditions. Pre-purchase inspections should be treated as non-negotiable, and annual AS 3660.2 inspections on existing homes with timber subfloors are strongly advisable.",
      "Landscapers": "Salt-tolerant, wind-resistant species are the practical choice for gardens facing the ocean corridor. Coastal banksias, grevilleas, and ground-covering natives perform well in the sandy soils. Water-wise design matters — the sandy coastal soils drain quickly and need mulching to retain any moisture through the dry Gold Coast winter.",
    },
  },

  "randwick": {
    housing: "Randwick is one of Sydney's classic eastern suburbs — tightly held, architecturally diverse, and anchored by a housing stock that spans from Victorian terraces in the northern streets to inter-war California bungalows in the middle sections and post-war red-brick flats everywhere else. UNSW dominates the northwestern edge and brings a perennial rental demand that keeps the apartment market churning. The Randwick Racecourse footprint occupies a significant chunk of the suburb and keeps adjoining land at premium.",
    climate: "Sydney eastern suburbs coastal climate — moderated by ocean influence more than most Sydney areas, keeping summer humidity high and winter nights genuinely mild. Summer days hover around 25-28°C with sea breezes common. Southerly busters arrive off the Tasman Sea and can drop temperatures 10°C in an hour on hot days. Rainfall averages around 1250mm annually.",
    council: "Randwick City Council",
    region: "Eastern Suburbs Sydney",
    tradeNotes: {
      "Electricians": "Randwick's housing spans 120+ years of electrical technology, and the older Victorian and inter-war sections commonly have original pre-1970s wiring alongside undersized consumer mains. The large concentration of rental properties means landlords are frequently chasing compliance upgrades for safety switches, smoke alarms, and switchboard condition as tenancy legislation evolves.",
      "Plumbers": "The Victorian and early Federation terraces in Randwick's northern section have original cast iron drainage stacks and copper supply that dates to the 1890s-1920s. When leaks emerge or renovations start, full replumbing is often more cost-effective than piecemeal patching. The rental market here means plenty of after-hours emergency callouts.",
      "Builders": "Randwick City Council has active DCP provisions protecting the character of the inter-war and Victorian streetscapes, particularly around the Randwick Heritage Conservation Area near the racecourse. Additions and alterations need to demonstrate neighbourhood character compatibility, and BASIX assessments are required for all residential additions.",
      "Painters": "Lead paint is a near-certainty in the pre-1970s housing stock across Randwick. The AS 4361.2 risk assessment process should be standard practice before any preparation work begins. The eastern suburbs coastal air accelerates surface chalking and oxidation on exterior paintwork — quality coatings and correct substrate prep make a real difference to life expectancy.",
      "Pest Control": "Eastern suburbs soil conditions and the leafy garden character of Randwick's better streets support strong subterranean termite populations. Properties backing onto Centennial Park or the UNSW campus have elevated risk. Annual inspections under AS 3660.2 and barrier treatments on older timber-framed homes are strongly advisable.",
      "Landscapers": "Randwick gardens tend to be generous compared to the inner city — the 1920s-50s housing era came with proper side passages and rear yards. Established trees are significant and Randwick City Council's tree preservation provisions apply broadly. Coastal-appropriate planting that handles the salt spray on east-facing elevations is worth factoring in for properties near Coogee and Maroubra.",
    },
  },

  "surfers-paradise": {
    housing: "Surfers Paradise is unlike any other suburb in Australia for its housing profile — over 60% of all dwellings are apartments, and the majority of those are in high-rise towers above four storeys. The apartment stock spans from early 1970s towers that have aged hard through to contemporary luxury penthouses in the glassy newer developments. Separate houses make up a small fraction of the total, mostly on Chevron Island and the canals of Isle of Capri and McIntosh Island. Short-term holiday letting is pervasive, which changes how maintenance works in practice.",
    climate: "Classic humid subtropical Gold Coast climate — warm to hot year-round, with a wet season from November through March that brings the bulk of annual rainfall (around 1700mm total). Summer temperatures sit in the low 30s with high humidity. Winter is genuinely lovely: sunny, dry, and around 20-22°C daytime with cool but not cold nights. Cyclone risk is low for the Gold Coast compared to north Queensland, but severe storm cells are common in summer.",
    council: "Gold Coast City Council",
    region: "Gold Coast",
    tradeNotes: {
      "Electricians": "High-rise apartment buildings in Surfers Paradise have complex common property electrical systems — basement car park lighting, lift plant, pool equipment, common area circuits — that strata committees need licensed electricians to maintain under regular contracts. The older towers from the 1970s-80s often need full common property switchboard upgrades.",
      "Plumbers": "The sheer density of apartments means hydraulic systems are complex, shared, and age-dependent. 1970s-80s tower blocks frequently have failing copper supply lines and cast iron drainage stacks requiring staged replacement. The short-term rental market creates high-use plumbing that wears faster than permanent residences.",
      "Builders": "Gold Coast City Council's planning scheme requires tropical design principles for new and substantially renovated buildings — cross-ventilation, shading, and cyclone bracing provisions under NCC. Strata-titled buildings require body corporate approval for any works affecting common property, adding a layer to the approval process.",
      "Painters": "The subtropical UV and salt air combination is brutal on exterior coatings. High-rise repaint programs are significant contracts requiring BMU (building maintenance unit) access or swing-stage rigging. The older concrete towers have carbonation and chloride-induced reinforcement corrosion that requires concrete repair before repainting can deliver lasting results.",
      "Pest Control": "Timber elements in older Surfers Paradise residential buildings — joinery, flooring, structural members — are subject to both termite and wood borer activity. The humidity levels in the subtropical climate accelerate timber decay and attract pests year-round rather than seasonally.",
      "Landscapers": "Common property landscaping in Surfers Paradise apartment complexes is typically managed through strata maintenance contracts. Pool surrounds, tropical garden beds, and resort-style planting characterise the better properties. Salt-spray tolerance and tropical species selection are baseline requirements for any coastal-facing landscape work.",
    },
  },

  "arundel": {
    housing: "Arundel is a family-oriented Gold Coast suburb that grew up from the mid-1980s, officially gazetted in 1989. The housing reflects the era: mostly four-bedroom brick or brick-and-tile homes on modest suburban lots, built for families and oriented around the school catchments and shopping precincts of the northern Gold Coast. A smattering of newer townhouse developments sit within larger estates, but the streetscape is overwhelmingly single-dwelling suburban. Very little stock predates 1984.",
    climate: "Humid subtropical Gold Coast climate — warm, sunny winters and hot wet summers. Annual rainfall sits around 1600mm, concentrated between November and March. Summer days in the low-to-mid 30s with significant humidity. Arundel sits inland of the coastal strip so gets slightly less sea-breeze moderation than beachside suburbs — summer evenings can stay sticky.",
    council: "Gold Coast City Council",
    region: "Northern Gold Coast",
    tradeNotes: {
      "Electricians": "Arundel's 1980s-90s housing stock is hitting the age where original switchboards and wiring are being looked at critically. Safety switch compliance for all circuits is a common upgrade request from landlords and real estate agents preparing properties for sale. Pool and spa wiring to current standards is another regular job.",
      "Plumbers": "The subtropical climate drives high hot water usage, and solar hot water or heat pump systems are increasingly common replacements for aging electric storage units. First-generation electric systems in the 1987-1995 homes are reaching or past 30 years old. Irrigation and pool plumbing maintenance is steady work across the suburb.",
      "Builders": "Gold Coast City Council's building requirements include storm event design provisions that are particularly relevant for the light-frame construction common in Arundel's housing estate era. Homeowners extending or adding patios should be across wind loading requirements for this coastal region.",
      "Painters": "The subtropical humidity and UV load means exterior paint life in Arundel rarely exceeds 8-10 years for budget products. The proliferation of second-storey homes in the estate sections creates demand for elevated access work. Mould growth on south and east-facing walls in shaded sections is a recurring maintenance issue in the wet season.",
      "Pest Control": "Gold Coast's warm, wet subtropical climate supports year-round termite activity, and Arundel's 1980s-90s homes — many of which have ageing or absent termite management systems — are regularly found to have subterranean activity on inspection. AS 3660.1 inspections are strongly recommended before purchase.",
      "Landscapers": "Arundel's family-friendly suburban blocks are well-suited to practical landscaping — lawns, veggie patches, and outdoor entertaining areas are the standard brief. The tropical-adjacent climate makes lawn care maintenance intensive through summer, and irrigation systems that can handle dry winter periods and wet summers need careful zoning.",
    },
  },

  "box-hill-north": {
    housing: "Box Hill North sits 14km east of Melbourne CBD within the City of Whitehorse. The housing is mostly post-war to 1970s brick — the quintessential eastern suburban Melbourne mix of weatherboard in the older pockets, cream brick veneer through the 1960s-70s, and brick-and-tile from the 1970s-80s. The suburb has been through significant demographic change, with the area now home to a substantial Chinese-Australian community, which has driven a wave of renovation and extension activity particularly on the larger corner blocks.",
    climate: "Melbourne's inland southeastern suburbs climate — four distinct seasons with hot, sometimes very hot summers and cold, occasionally frosty winters. Summer days hit 38-40°C on the bad weeks in January and February. Winter lows drop to 4-6°C regularly. Annual rainfall around 650mm spread fairly evenly through the year. The lack of coastal moderation makes temperature swings more dramatic than bayside suburbs.",
    council: "City of Whitehorse",
    region: "Eastern Suburbs Melbourne",
    tradeNotes: {
      "Electricians": "Box Hill North's 1950s-70s housing has the usual array of old switchboards with ceramic fuses and inadequate RCD protection. As the suburb undergoes renovation and densification, the requests for full switchboard upgrades, additional circuits for home offices, and EV charger installations are steadily increasing.",
      "Plumbers": "Copper pipe runs from the 1960s-70s are the norm here, and pinhole leaks in older copper are appearing regularly as the pipes approach 50-60 years of age. The renovation wave also brings bathroom and kitchen replumbing jobs, often alongside re-stumping projects where the original hardwood stumps are being replaced.",
      "Builders": "City of Whitehorse applies Neighbourhood Character Overlays across significant sections of Box Hill North that limit demolition and require design responses compatible with the existing street character. The Planning Scheme provisions should be checked carefully before any new build or significant addition — what's permitted varies block by block.",
      "Painters": "Lead paint is essentially certain in Box Hill North homes built before 1970. The preparation, containment, and disposal requirements under AS 4361.2 are standard practice before any sanding or stripping work begins. The cold, wet Melbourne winters are hard on weatherboard homes — moisture ingress behind failing paint causes timber decay if left unchecked.",
      "Pest Control": "Subterranean termite activity is active across the City of Whitehorse, and Box Hill North's older homes with timber subfloors and established garden trees are regularly inspected and treated. Annual inspections under AS 3660.2 are the standard recommendation — particularly before and after any major renovation work that disturbs the termite management barriers.",
      "Landscapers": "Box Hill North's generous post-war allotments often have large established eucalypts and ornamental trees that need arborist assessment and council approval before any works. The neighbourhood character emphasis on canopy trees means removal is not straightforward. The renovation market has created demand for rear-yard transformations with alfresco areas and low-maintenance planting.",
    },
  },

  "chermside": {
    housing: "Chermside sits 9.8km north of Brisbane CBD and functions as a genuine regional centre for Brisbane's northern suburbs, anchored by Westfield Chermside (one of Queensland's largest shopping centres) and the Prince Charles Hospital precinct. The housing is a proper mix of original 1950s-60s Queenslanders on timber stumps, 1970s-80s brick-and-tile family homes, and an increasing proportion of newer medium-density apartments and townhouses feeding off the commercial activity and hospital employment. The Queenslander stock is the character backbone of the suburb's residential streets.",
    climate: "Humid subtropical Brisbane climate — warm to hot summers with a distinct wet season (November-March), and mild, dry winters. Summer days sit in the low-to-mid 30s with significant humidity. Winter daytime temperatures of 20-23°C are genuinely pleasant. Annual rainfall around 1100mm, concentrated in the summer months. Severe storm events with large hail are a notable risk for the northern Brisbane suburbs, occurring several times annually.",
    council: "Brisbane City Council",
    region: "Northern Brisbane",
    tradeNotes: {
      "Electricians": "Chermside's 1950s-60s Queenslander stock often has original wiring approaching 60-70 years of age, and the combination of timber construction and ageing insulation creates real safety risks. Switchboard upgrades, safety switch compliance, and air conditioning circuit additions are the most common jobs across this part of Brisbane's northern suburbs.",
      "Plumbers": "The elevated Queenslander design creates specific plumbing challenges — supply and drainage runs are long, and the under-house space concentrates drainage odour issues if the stacks aren't properly maintained. The hospital precinct drives significant demand for commercial plumbing contractors as well as the residential market.",
      "Builders": "Brisbane City Council's flood mapping affects parts of Chermside, particularly in the lower areas closer to Kedron Brook. Renovation and new construction projects need to confirm floor level requirements against the applicable flood regulation before design commences. The heritage character of older Queenslander streetscapes influences design guidelines for additions.",
      "Painters": "Brisbane's subtropical humidity drives significant mould and mildew growth on south and east-facing surfaces, particularly on the shaded undersides of Queenslander verandahs and the timber boards in enclosed understories. Quality anti-mould exterior finishes and proper substrate treatment are necessary — paint that looks fine in winter can show mould by March if the prep was inadequate.",
      "Pest Control": "Subterranean termites are one of the biggest pest risks for timber-framed Queenslanders in Chermside. The elevated construction that makes Queenslanders liveable in subtropical heat also means subfloor inspections are relatively straightforward — but the access also makes it easier for termites to enter from multiple points. AS 3660.1 annual inspections should be treated as standard.",
      "Landscapers": "Chermside gardens adjacent to Kedron Brook and other drainage corridors should incorporate flood-tolerant species in lower sections. The subtropical climate supports lush garden growth but also means lawn areas need significant maintenance through the wet season. Tree protection provisions under the Vegetation Protection Overlay apply to significant trees on private land.",
    },
  },

} as const;
