// =============================================================================
// TRADEREFER CONTENT — BATCH 10
// Suburbs 91–100
// Research-backed, AU-specific content
// =============================================================================

"edwardstown": {
    housing: "Edwardstown is inner south-west Adelaide — 8km from the CBD, sitting in the City of Marion, and named for a 19th century landholder in the most Adelaide way possible. The suburb's housing character is shaped by the SA Housing Trust's post-war activity in the Marion council area — cavity brick and double brick homes from the 1950s and 1960s, built to house the industrial workforce attracted by the manufacturing precinct developing in the area. Three-bedroom brick homes on 600–700 sqm blocks are the dominant type. It's a suburb that's spent the last twenty years becoming more attractive as its proximity to the CBD, the Tonsley Innovation District, and the Oaklands Park rail corridor have made its affordable housing stock interesting to a new demographic.",
    climate: "Inner south-west Adelaide — Mediterranean, hot and dry in summer, mild wet winters. The inner southern position provides some slight moderation compared to the flat northern suburbs on the worst summer heatwave days, but Adelaide's 40°C+ summer events reach everywhere in the metro area. The proximity to the Sturt Creek and Brownhill Creek corridors provides a thin green buffer.",
    council: "City of Marion",
    region: "Inner South-West Adelaide / Marion",
    tradeNotes: {
        "Building": "Edwardstown's SA Housing Trust cavity brick homes from the 1950s–1960s are structurally sound but create specific renovation challenges — cavity walls limit service routing options, and extensions must be detailed carefully to manage movement at the junction between old and new construction. The infill medium-density development that's been occurring on subdivided blocks requires engagement with Marion Council's planning provisions for the area.",
        "Air Conditioning & Heating": "Adelaide's summer heat extremes make reverse-cycle split systems essential in Edwardstown's older brick homes — the original evaporative cooling systems that were common in south-west Adelaide brick homes are increasingly being replaced by refrigerative units as the extreme heat days when evaporative cooling's performance drops off have become more frequent. The brick construction does provide genuine thermal mass benefit for the cooler months.",
        "Roofing": "The 1950s–1960s concrete tile roofs across most of Edwardstown are in the 65–75 year zone where sealer coat loss, ridge pointing failure, and valley flashing corrosion are widespread. The Adelaide summer UV loading is among the most intense in the country and accelerates coating degradation faster than cooler climates.",
    },
},

"ballarat-central": {
    housing: "Ballarat Central is a regional city centre that's genuinely special — 115km north-west of Melbourne, and the Victorian-era gold rush wealth that built the city is written into every streetscape in the central area. Lydiard Street has one of the best-preserved 19th-century commercial streetscapes in Australia, and the surrounding residential streets have Victorian villas, Georgian red brick homes, and Edwardian bungalows of genuine quality built between roughly 1860 and 1910. The post-war development that typically overwhelmed Australian inner suburbs was moderate here — Ballarat's slower growth rate after the gold rush preserved the period character. The City of Ballarat employs Heritage Advisors and takes conservation seriously.",
    climate: "Inland western Victoria — one of the coldest urban climates in Australia. Ballarat's elevation (435m) and inland position mean genuine winter cold: frosts are common from April through September, and occasional snow events happen most winters. Summer is warm and pleasant but brief. The contrast between Ballarat's winters and the temperate coastal cities surprises people who move here from Melbourne or the coast — it's a genuinely different climate.",
    council: "City of Ballarat",
    region: "Ballarat CBD / Western Victoria",
    tradeNotes: {
        "Building": "Ballarat Central's Victorian heritage building stock is one of the most significant concentrations of 19th-century residential and commercial architecture in regional Victoria — the City of Ballarat's Heritage Overlay covers the majority of the central residential and commercial precincts, and development or significant works on Heritage Overlay properties requires heritage permit assessment. The City's Heritage Advisors offer pre-application consultation that is genuinely useful for builders unfamiliar with the Ballarat heritage provisions.",
        "Roofing": "The Victorian and Edwardian homes in Ballarat Central have original corrugated galvanised iron and terracotta tile roofing — in a frost climate with genuine winters, moss and lichen on the south-facing aspects is essentially universal, and the freeze-thaw cycle at this elevation creates specific risks for pointing failure on ridge capping that don't apply in coastal cities. Conservation-aware re-roofing on heritage-listed properties requires matching original profile and materials.",
        "Insulation": "The cold Ballarat climate makes insulation upgrades among the most financially justifiable home improvements in the region — the Victorian homes in Ballarat Central were built without any meaningful insulation, and ceiling insulation to R5.0 plus draught sealing on the timber sash windows that characterise the period homes provides genuine comfort improvement. The City of Ballarat's energy efficiency programs have targeted the CBD residential precinct.",
    },
},

"brisbane-city": {
    housing: "Brisbane City — the CBD proper — is like Sydney and Melbourne in that it's almost entirely apartment living now, though Brisbane's CBD has a different character from its southern equivalents. The mix includes 1980s–1990s residential towers from the first wave of CBD living, purpose-built 2000s and 2010s apartments in the South Bank, Eagle Street, and New Farm edge precincts, and a growing number of high-rise towers under construction as SEQ's population growth drives CBD demand. There are small pockets of older housing near the heritage precinct of Spring Hill (Federation-era workers' housing within walking distance of the CBD) and in the Victorian-era commercial buildings that have been adapted for residential use. But overwhelmingly: strata apartments.",
    climate: "Subtropical Brisbane river valley — the Brisbane River curves through the CBD and creates the familiar view. The valley position creates some heat island effect, and Brisbane's humidity in the wet season (November–March) makes the CBD noticeably stickier than the ocean-facing suburbs. The northwest prevailing summer winds and the southeast sea breeze that arrives on most summer afternoons moderate the CBD somewhat. Winters are genuinely mild — daytime temperatures around 22°C in winter are not unusual.",
    council: "Brisbane City Council",
    region: "Brisbane CBD",
    tradeNotes: {
        "Building": "Brisbane CBD development operates under the Brisbane City Plan and the State Government's planning policies for the inner city — heritage buildings in the Spring Hill precinct and along Edward and Queen Streets have detailed heritage conservation requirements under the Brisbane Local Heritage Register and the Queensland Heritage Act. High-rise builders need QBCC licensing appropriate for their class of building and should be familiar with the specific requirements of Queensland's tropical-rating energy provisions.",
        "Electrical": "The concentration of strata buildings in Brisbane's CBD — ranging from 1980s first-generation residential towers to 2020s smart buildings — creates a specialist commercial electrical market: BMS maintenance, AS 3000:2018 wiring compliance upgrades, emergency lighting testing under AS 2293, and energy monitoring upgrades are constant demands. The subtropical climate also creates greater HVAC electrical load than equivalent-tier Melbourne buildings.",
    },
},

"lara": {
    housing: "Lara is the town between Geelong and Melbourne that's been quietly growing for twenty years and is now a full-on growth corridor in its own right. The Princes Highway and the Geelong–Melbourne railway both run through, and that connectivity has made Lara attractive to both Geelong workers and Melbourne CBD commuters who couldn't afford either city. The established area around the old township has 1980s–2000s brick veneer on 600–700 sqm blocks. The newer estates on the north and west are the classic City of Greater Geelong growth corridor style — 2010s–2020s brick and rendered homes on 400–500 sqm blocks. Lara West will eventually add another 11,000 residents when fully developed.",
    climate: "Northern Greater Geelong — the Corio Bay influence is present but from a distance, and the flat plains to the north and west mean wind exposure is significant. Summer is warm with the typical Geelong westerly sea breeze arriving in the afternoons. Winters are cooler than Melbourne coastal and the open plains location creates genuine wind chill on the worst days. The elevated position of the original township above the Lara valley floor creates some local climate variation between streets.",
    council: "City of Greater Geelong",
    region: "Northern Greater Geelong / Princes Freeway Corridor",
    tradeNotes: {
        "Solar & Energy": "Lara's position midway between Geelong and Melbourne, with a demographic heavily weighted toward families who've moved there for affordability, creates a strong solar market — energy costs are a real budget consideration for the young families in the newer estates, and the available roof space on the single-storey homes is well-suited to rooftop generation. Battery storage uptake is growing in the outer corridor suburbs.",
        "Building": "The Lara West growth area is one of the largest activated growth areas in the Greater Geelong municipality — builders working here are dealing with PSP-governed subdivision and infrastructure sequencing rather than individual infill development. The growth area provisions under the Geelong Planning Scheme require compliance with the relevant Infrastructure Contributions Plan for each new development.",
        "Landscaping": "The basalt plains soils and the Melbourne lava plains clay that characterise Lara's landscape are reactive and slow-draining in wet winters. Garden establishment in the newer estates requires topsoil import and organic amendment — the construction-compacted fill that comes with a new house on a cleared paddock block is not a workable growing medium without intervention.",
    },
},

"christie-downs": {
    housing: "Christie Downs is one of southern Adelaide's significant public housing suburbs — the South Australian Housing Trust purchased large tracts of farmland here in the late 1950s and developed the suburb through the 1960s and 1970s, creating a community built primarily to house working families in modest three-bedroom brick homes. The result is a suburb of fairly consistent character: 1965–1980 brick veneer and cavity brick homes on 650–750 sqm blocks, flat, practical, and well-maintained by successive generations of owner-occupiers and housing trust tenants. It's 35km south of the Adelaide CBD and 3km from Christies Beach, which has kept the suburb affordable and in steady demand from the coastal-adjacent lifestyle market.",
    climate: "Southern metropolitan Adelaide, coastal proximity — Christie Downs is close enough to the Gulf St Vincent and the Southern Ocean coast that the sea breeze arrives reasonably reliably and moderates summer heat compared to the flat northern suburbs. Still genuinely hot in summer, but the southern coastal position takes the edge off. Winter is mild with the standard SA Mediterranean pattern.",
    council: "City of Onkaparinga",
    region: "Southern Adelaide / Onkaparinga",
    tradeNotes: {
        "Roofing": "Christie Downs' 1965–1980 concrete tile roofs are in the 45–60 year zone where sealer coat degradation, failed ridge pointing, and valley flashing issues are widespread — the roof inspection and re-bedding/re-pointing market is active in this suburb, and full re-roof demand is building as the oldest stock hits end of life.",
        "Air Conditioning & Heating": "Southern Adelaide's coastal position moderates temperatures but doesn't eliminate the need for cooling — the 1960s–1980s brick homes in Christie Downs have significant thermal mass which helps, but reverse-cycle systems are still the dominant demand. The Onkaparinga housing stock has been a focus of the SA Housing Authority's energy efficiency upgrade program for the public housing stock.",
        "Building": "The SA Housing Trust origin of much of Christie Downs' stock means there's a proportion of properties with specific housing authority maintenance and renovation procurement requirements for the trust's remaining housing portfolio. Private renovations on the 1960s–1970s homes need to account for the cavity brick construction's limitations for services routing and the need for careful detailing on extensions.",
    },
},

"ellenbrook": {
    housing: "Ellenbrook is Australia's most awarded masterplanned community — which is genuinely impressive and says something real about its design. Located 25km north-east of Perth CBD in the City of Swan, the development started in 1996 and has grown to over 11,000 homes across eight walkable village precincts. Everything here is from the 1996–2020s era: brick and rendered double-brick homes on lots that range from compact 300 sqm townhouse lots to the larger 650 sqm family allotments in the older village precincts. The town centre, the excellent school provision, and the 35km of cycleways were planned from the start. It's not organic suburban growth — it's designed community, and it mostly works.",
    climate: "Eastern Perth fringe, Swan Valley — the ocean is about 35km west and the coastal sea breeze arrives in the afternoon but is somewhat attenuated compared to the beachfront suburbs. Ellenbrook sits on the eastern fringe where summer temperatures run a few degrees hotter than coastal Perth on the worst days. The Swan Valley itself creates some local humidity in the lower-lying areas near the river. Winters are mild and wet in the standard Perth pattern.",
    council: "City of Swan",
    region: "North-East Perth / Swan Valley",
    tradeNotes: {
        "Landscaping": "The sandy soils of the Swan Coastal Plain that underlie most of Ellenbrook's residential areas drain very quickly — water-wise garden design is not optional here but a genuine necessity given the Water Corporation's Perth residential restrictions and the soil's minimal water-holding capacity. The City of Swan's urban greening initiatives have established street tree programs, but private gardens need systematic irrigation design and soil amendment to establish effectively.",
        "Solar & Energy": "Perth's solar irradiance is among the highest in the world and Ellenbrook's single-storey brick homes on good north-facing lots are ideal for rooftop solar. The household energy cost consciousness that characterises outer suburban Perth demographics makes the solar economics straightforward. Ellenbrook's age range — 1996 to present — means a mix of retro-fit solar markets and first-install new builds.",
        "Building": "Ellenbrook's design standards and the City of Swan's development controls create a higher-than-average design compliance overhead for building work in the development area — design guidelines apply to external materials, colours, and landscape requirements that are more prescriptive than standard residential building in most Perth suburbs. Builders working here for the first time should familiarise themselves with the Community Title requirements and design review process.",
    },
},

"sorell": {
    housing: "Sorell is one of Tasmania's oldest towns — settled in 1808 and historically the first service town on the main road to the Tasman Peninsula. The original town has historic stone and brick cottages from the 1820s–1850s, modest weatherboard homes from the late colonial and Federation period, and the standard post-war brick housing that filled in through the 1950s–1980s. The last decade has been dramatic: Sorell has become one of Tasmania's fastest-growing residential areas, attracting Hobart workers who can't afford Hobart prices. New residential estates have appeared on the former farmland around the old town, bringing 2010s–2020s brick and lightweight construction homes. The old town and the new estates exist in genuinely different planning contexts.",
    climate: "South-east Tasmanian coastal lowland — the Frederick Henry Bay to the south and the Coal River valley create a specific microclimate that's sunnier and drier than Hobart but still cold in winter. Frosts occur regularly from May through August. The southern exposure can deliver sharp southerly winds off the bay on the more exposed properties. Summer is pleasant and warm with good sunshine.",
    council: "Sorell Council",
    region: "South-East Tasmania / Sorell",
    tradeNotes: {
        "Building": "Sorell's historic town centre has colonial-era stone and brick buildings on the Tasmanian Heritage Register and the Local Heritage Register — any work on these properties requires heritage permit assessment and compliance with Heritage Tasmania guidelines. Stone masonry repair and lime mortar work are specialist skills that aren't widely available in regional Tasmania, and sourcing appropriate heritage-compatible materials requires planning.",
        "Roofing": "The older corrugated iron roofing on Sorell's colonial and post-war housing stock is a consistent replacement market — the cold wet winters and the bay coastal exposure accelerate deterioration on south-facing roofs, and the growing residential market in the new estates creates demand for both new installation and maintenance across different construction generations.",
        "Insulation": "Sorell's Zone 7 Tasmanian climate (equivalent to Hobart) means insulation upgrades have among the best payback periods in Australia. The older housing stock in the historic town area typically has minimal ceiling insulation and no sub-floor insulation, and the newer estates, while built to more recent NCC energy standards, still benefit from upgrades to current best practice for the cool climate.",
    },
},

"casey": {
    housing: "Casey is Canberra's newest suburb in the Gungahlin district — land titles were first registered here around 2010 and development has continued through the 2010s and into the 2020s. This means essentially the entire housing stock is less than 15 years old: ACT-standard double-brick and lightweight steel frame homes on 300–500 sqm lots, built to the energy ratings of the NCC 2010 era and later. The suburb has that characteristic new Canberra look — consistent in age, designed community facilities, roundabout-connected estate streets. Everything is very recent and the first generation of owners is still the dominant occupier.",
    climate: "Gungahlin district, northern Canberra — the ACT continental climate in its northern form. Cold winters with frosts from April through September, warm dry summers. The northern Canberra position is somewhat more exposed than the Tuggeranong Valley to the south. The Gungahlin light rail provides a connection to the city that the newer estates in the district didn't previously have.",
    council: "ACT Government",
    region: "Gungahlin District / Northern Canberra",
    tradeNotes: {
        "Insulation": "Casey's post-2010 housing stock was built to NCC 2010 energy standards at minimum, which is considerably better than Canberra's older suburbs, but the ACT's Zone 7 climate means best practice for insulation (R6.0+ ceiling, R2.5 wall, secondary glazing or double-glazed windows) is still a meaningful upgrade over builder standard. The cold continental winters reward insulation investment more than in any coastal city.",
        "Landscaping": "Brand new Casey estates have the standard new-estate soil problem: compacted clay fill with stripped topsoil, minimal organic matter, and no established root networks. Garden establishment here requires soil remediation work before planting — imported quality topsoil, deep organic amendment, and mulching are the baseline requirements before anything will establish in the ACT's cold winters and dry summers.",
        "Solar & Energy": "The ACT Government's Sustainable Household Scheme provides significant rebates for solar, battery storage, and EV infrastructure in new homes. Casey's new housing stock is well-positioned to capture these incentives — the rooftop orientations are typically good, the conduit runs are already installed, and the ACT's progressive clean energy policy environment has driven high solar uptake in the Gungahlin district generally.",
    },
},

"clifton-springs": {
    housing: "Clifton Springs is a Bellarine Peninsula coastal town 17km east of Geelong — the kind of suburb that transitioned from weekend holiday destination to genuine residential community over the span of about twenty years. The older streets near the waterfront have fibro and timber holiday shacks from the 1950s–1970s era, some still in their original state and some comprehensively renovated. Behind these, the permanent residential development that followed the sea-change migration of the 1990s and 2000s added brick veneer homes on 500–700 sqm blocks. The newer Bellarine Views estate on the southern fringe is 2010s–2020s development adding more permanent housing. Drysdale, immediately to the north, provides the commercial services.",
    climate: "Bellarine Peninsula, Port Phillip Heads facing — the bay is close and Clifton Springs gets the classic Bellarine marine climate: sea breeze off the bay in summer, cool southerly influence in winter, and the general pattern of wind that makes the Bellarine very different from flat inland Geelong. The Rip entrance to Port Phillip creates some distinctive water conditions on the southern-facing aspects. Winters are cooler than central Geelong and the wind exposure on the more open blocks is real.",
    council: "City of Greater Geelong",
    region: "Bellarine Peninsula / Greater Geelong",
    tradeNotes: {
        "Roofing": "The coastal location creates the standard bay-side product specification requirement — the fibro and timber holiday homes from the 1950s–1970s often have corrugated iron roofing at or past service life, and the newer brick homes on the more exposed streets should be specified to coastal-rated product. The conversion of former weekenders to permanent residences often reveals that the original roofing wasn't designed for year-round habitation.",
        "Building": "The transition from holiday housing to permanent residential use is a live building issue in Clifton Springs — upgrading former weekenders to permanent habitation standards requires compliance with current NCC insulation, ventilation, and energy efficiency requirements that the original holiday builds didn't need to meet. Some of the fibro construction also has asbestos exposure risk in pre-1987 material.",
        "Landscaping": "The Bellarine Peninsula's sandy coastal soils drain quickly and the bay coastal exposure creates salt air conditions that limit plant selection on the more exposed properties. Native coastal species suited to the wind and salt exposure are consistently more successful than the full ornamental palette, and irrigation design that accounts for the quick-draining soils is essential for garden establishment.",
    },
},

"marrickville": {
    housing: "Marrickville is inner-west Sydney — 7km from the CBD, Inner West Council, and one of the city's more genuinely interesting suburb characters. The housing stock is a proper layered mix: Federation bungalows and Victorian terraces from the 1880s–1910s on the residential streets, with the workers' cottages of the earlier industrial workers' housing sitting alongside the more prosperous inter-war bungalows from the 1920s–1940s. The industrial precinct along the railway corridor has been converting to residential and creative industries for twenty years — warehouse apartments, terrace conversions, small-footprint new developments in the gaps between the original lot patterns. The suburb is in the later stages of the gentrification cycle that started in the 1990s.",
    climate: "Inner west Sydney — maritime temperate. The north-east sea breeze off Botany Bay and the Pacific moderates summer temperatures. Marrickville is warmer than the eastern suburbs on the worst summer days but significantly cooler than western Sydney. The Cooks River corridor runs along the southern edge and provides a linear green space. Winter is mild and mostly dry with occasional fog in the low valley areas.",
    council: "Inner West Council",
    region: "Inner West Sydney",
    tradeNotes: {
        "Building": "The Inner West Council's heritage controls cover significant portions of Marrickville's pre-war housing stock — the Federation and Victorian terraces on the residential streets are in heritage conservation areas or are individually heritage listed, and external works require heritage assessment and often council approval. The Inner West LEP and DCP heritage provisions are detailed and actively applied.",
        "Plumbing": "The older terrace and cottage stock in Marrickville — some of it pushing 130 years old — frequently has lead service pipes, original galvanised iron hot water supply, and clay drainage that's well past its useful life. The heavily Victorian terrace presence means lead pipe identification is standard practice before any plumbing scope in the pre-1910 homes.",
        "Electrical": "Marrickville's mix of original terrace housing and converted industrial buildings creates a wide variety of electrical system ages and configurations — the terrace stock has often had wiring updated piecemeal over decades rather than as a coherent system, and the industrial conversions can have commercial-grade electrical infrastructure that's been adapted to residential use in ways that require expert assessment.",
    },
},
