// =============================================================================
// TRADEREFER CONTENT — BATCH 06
// Suburbs 51–60
// Research-backed, AU-specific content
// NOTE: "epping-vic" is used here as a suggested alternate slug because "epping"
// is already used for Epping NSW (Parramatta). Resolve in constants.ts.
// =============================================================================

"botany": {
    housing: "Botany has one of the more layered histories in inner Sydney — market gardens and industry from the 1850s, then a wave of workers' cottages and modest brick terraces that went up through the Federation and inter-war years to house the workforce around the port and factories. Post-war, the suburb added standard 1950s–1960s brick bungalows, but Botany also has a later chapter: the old industrial land along the southern end has been rezoned and knocked over for apartments in the 2010s and 2020s, particularly near Botany Road and the Mascot edge. It's a suburb that's never had a single character — it has always been working, busy, and a bit rough around the edges.",
    climate: "Botany Bay right on the doorstep, which means the suburb gets real coastal conditions — afternoon sea breezes, salt air, and the kind of humidity that gets into everything. The flight path for Sydney Airport runs straight over the suburb, which isn't a climate issue but does affect daily life in ways that matter to trades working outdoors. Summer is warm and humid, winters genuinely mild. The bay foreshore gets more wind than the streets a few blocks back.",
    council: "Bayside Council",
    region: "South Sydney / Bayside",
    tradeNotes: {
        "Building": "Botany's industrial history means some sites close to the port and factory zones have contaminated soil that needs environmental assessment before any excavation or earthworks — this doesn't come up for standard maintenance work but matters enormously for any ground-up development or deep works. The older workers' housing stock also has a mix of original terracotta, fibro, and brick that needs careful handling.",
        "Roofing": "The bay proximity puts coastal corrosion demands on roofing in Botany, and the mix of housing ages — from 1910s terraces to 1960s flats to 2010s apartments — means roofers work across a very wide range of material types within a small area. Standard Colorbond is typically fine a few streets back from the water; anything on the foreshore edge should be specified to coastal grade.",
        "Landscaping": "Parts of Botany, particularly near the former industrial sites and the airport-adjacent zones, have disturbed or potentially contaminated soils that require testing before any major planting works. The coastal influence makes salt-tolerant species more practical for exposed gardens, but the established inner streets have standard Sydney urban soil conditions.",
    },
},

"clyde": {
    housing: "Clyde is about as new as suburbs get — the residential development here is almost entirely 2010s to present, and a good chunk of it is still under construction or in the planning stage. Casey Fields is the dominant development context: master-planned estate housing on 300–450 sqm lots, predominantly lightweight steel frame and brick veneer construction, with all the consistency (and all the limitations) that come from a single-era buildout. Very few trees, no heritage, minimal established character yet. The suburb will look completely different in ten years as vegetation matures.",
    climate: "South-east Melbourne fringe — 50km from the CBD and well outside any coastal influence. Summers get genuinely hot here, regularly into the high 30s, and there's not much shade yet on the newer streets. The Cardinia Creek corridor provides a thin green buffer but doesn't significantly moderate temperatures. Winters are cold with frosts, and the flat exposed location means wind cuts through unimpeded on the worst days.",
    council: "City of Casey",
    region: "South-East Melbourne Growth Corridor",
    tradeNotes: {
        "Building": "Clyde's entirely 2010s+ housing stock means builders here are almost exclusively working on new construction or early-stage defect rectification — the seven-year statutory warranty period under the Domestic Building Contracts Act applies to the vast majority of homes here, and defect claims on new construction are a significant portion of building work in this suburb.",
        "Landscaping": "Brand-new estates like Clyde present a specific landscaping challenge: the topsoil has typically been stripped during construction and replaced with imported fill that's compact, low in organic matter, and often hydrophobic. Establishing gardens here requires soil remediation and heavy mulching before anything will properly take hold.",
        "Solar & Energy": "The City of Casey is one of Victoria's fastest-growing municipalities and Clyde's new housing is largely built to NCC 2019/2022 energy standards with solar ready conduit runs included — the uptake of solar is high in these new estates and the combination of hot western summers and relatively few established shade trees makes the economics straightforward.",
    },
},

"dee-why": {
    housing: "Dee Why is one of Sydney's more densely residential northern beaches suburbs — the long beach, the surf club, and the lagoon are the defining features, and the housing that grew up around them reflects the different eras of northern beaches growth. Closest to the beach and along the main strip it's mostly 1950s–1970s walk-up apartment blocks — three and four storeys, brick, the kind of buildings that were everywhere on Sydney's beach corridors in that era. Inland from the beach the mix includes 1960s–1970s houses and duplexes, with a significant overlay of newer apartment development from the 2000s and 2010s as the Northern Beaches density push took hold. Over 80% of dwellings here are apartments.",
    climate: "Proper ocean beach exposure — the Tasman Sea is right there, and the north-east swell that defines the northern beaches produces consistent onshore wind, spray, and salt air year-round. Summer is genuinely warm and the sea breeze usually shows up reliably by mid-afternoon. Winter is mild but the south-westerly off the ocean can be sharp. The salt air environment is real and measurable — exterior materials deteriorate faster here than even a couple of kilometres inland.",
    council: "Northern Beaches Council",
    region: "Northern Beaches, Sydney",
    tradeNotes: {
        "Roofing": "The ocean exposure at Dee Why demands coastal-grade product specifications — BlueScope Colorbond Ultra (or equivalent coastal-rated alternatives) is the correct choice for any roof within 500m of the beach, and standard galvanised iron or regular Colorbond will have a noticeably shorter service life in this environment. The older 1950s–1970s walk-up flat roofing is a constant maintenance demand here.",
        "Building": "The huge proportion of strata apartment buildings in Dee Why means most building work here is strata renovation — bathroom and kitchen refurbishments within units, fire safety upgrades to older buildings, facade maintenance on 1960s–1970s brick blocks. Builders need familiarity with the NSW strata legislation requirements and owners corporation approval processes.",
        "Air Conditioning & Heating": "The mild northern beaches climate means ducted systems are somewhat less common here than in western Sydney — split systems are the dominant residential install. But the salt air environment accelerates corrosion on condenser coils and outdoor units, meaning replacement cycles can be shorter than the product's nominal lifespan would suggest.",
    },
},

"glenorchy": {
    housing: "Glenorchy is the working-class northern suburb of Hobart proper — the Derwent River valley narrows here and the suburb climbs the valley slopes in a way that gives it a distinct and slightly dramatic topography. The housing grew primarily with Hobart's post-WWII industrial expansion, and the Housing Trust was active here from the late 1940s through the 1960s, building weatherboard and fibrous cement homes for the manufacturing workforce. Cadbury's Claremont factory, the EZ zinc works, and the Ralphs Bay area all generated employment that filled these streets. Later infill from the 1970s–1980s added brick veneer. The weatherboard and fibro stock is old enough now that maintenance is a constant demand.",
    climate: "Northern Hobart valley — protected from the worst of the Antarctic-sourced southwesterlies by Mount Wellington to the south, but still genuinely cold in winter. Glenorchy gets frosts regularly from May through August, and the valley floor pockets can be noticeably colder than the hill streets when inversions trap cold air. Summer is pleasant and mild. Rainfall is moderate and spread through the year, and the cloud base over the mountain keeps the suburb frequently overcast in winter.",
    council: "City of Glenorchy",
    region: "Northern Hobart / Glenorchy",
    tradeNotes: {
        "Insulation": "Glenorchy's original post-war Housing Trust weatherboard and fibro homes are some of the worst-insulated houses in Tasmania — minimal ceiling insulation, no wall insulation, and original single-pane windows on the earlier stock. The payback period on ceiling insulation upgrades to R5.0 in Hobart's Zone 7 climate is among the best in Australia, and the Tasmanian government's energy efficiency programs actively target this suburb's older rental stock.",
        "Building": "The older fibrous cement homes in Glenorchy frequently contain asbestos in the cladding, eaves, internal linings, and flooring adhesives — any renovation work on pre-1987 homes needs an asbestos assessment under the Safe Work Tasmania regulations and WorkSafe Tasmania's Code of Practice before work begins. Glenorchy's high proportion of Housing Tasmania stock also means some renovation work goes through Social Housing procurement channels.",
        "Roofing": "Weatherboard homes on the valley slopes take a beating from the combination of cold, wet winters and the occasional high wind that funnels through the river valley — moss and lichen on older corrugated iron roofing is almost universal on Glenorchy's north and east-facing slopes, and valley flashings on the 1950s–1960s stock have usually corroded well beyond serviceable.",
    },
},

// NOTE: This entry uses slug "epping-vic" to avoid collision with "epping" (Parramatta NSW).
// Consider whether to rename one in the final constants.ts implementation.
"epping-vic": {
    housing: "Epping VIC is one of Melbourne's busiest northern growth suburbs — the old township on the Whittlesea line has been surrounded and largely absorbed by successive waves of residential development since the 1970s. The inner parts of Epping are 1970s–1990s brick veneer on 600–700 sqm blocks, classic northern Melbourne suburban fabric. Then Epping North happened — from about 2006 onward, the paddocks north of the old township were converted to residential estates at pace, and that development is still running. New construction is 350–500 sqm lots with lightweight steel frame or brick veneer. The suburb now has a very distinct split character between the established older streets near the town centre and the new estates to the north.",
    climate: "Northern Melbourne fringe — the City of Whittlesea sits well inland and gets none of the coastal moderation you'd find in bayside Melbourne. Summer heat here regularly exceeds 40°C and the northerly winds from the interior of Victoria arrive unchecked. Winters are cold with regular frosts on the lower pockets around the old township. There's no significant topographic feature to moderate either extreme.",
    council: "City of Whittlesea",
    region: "Northern Melbourne / Whittlesea",
    tradeNotes: {
        "Landscaping": "The northern Melbourne basalt plains soil that underlies much of Epping's older established areas is black cracking clay — reactive, slow-draining in winter, and bone-hard in summer. Gardens need significant soil amendment and correct drainage design to establish properly. The newer Epping North estate areas have often had topsoil stripped during construction, creating a different but equally challenging starting point for landscapers.",
        "Solar & Energy": "The City of Whittlesea's population growth rate is among the highest in Victoria and Epping's mix of 1970s–1990s renovatable homes and brand-new estates creates two distinct solar markets: retrofitting older homes that are often under-insulated, and first installs on new builds where the conduit runs are already in. The extreme summer heat makes air conditioning a genuine essential, which in turn makes solar economics very clear.",
        "Air Conditioning & Heating": "Northern Melbourne heat extremes and proper Whittlesea winter frosts mean this suburb has real demand at both ends of the HVAC spectrum — the 1970s–1990s housing stock is mostly on ducted reverse-cycle or old gas ducted heating, and the replacement cycle on these systems is active. The newer estates are typically installing 7–10kW split systems or ducted refrigerative from new.",
    },
},

"bellerive": {
    housing: "Bellerive is on Hobart's eastern shore — the suburb looks across the Derwent Estuary toward the CBD and Mount Wellington, and that position has made it one of Hobart's most consistently sought-after addresses. The housing stock reflects successive generations of eastern shore growth: there are some solid inter-war brick and weatherboard homes from the 1930s and 1940s near the waterfront, then the bulk of the suburb filled out through the 1950s and 1960s with fibrous cement and brick homes typical of the Housing Trust era, and the 1970s–1980s added brick veneer further back from the water. Some lovely original homes survive near the Bellerive Oval and the village precinct. The views over the river have kept this suburb expensive relative to Hobart.",
    climate: "Derwent Estuary facing — the river is a significant presence and Bellerive gets the full estuarine microclimate. South-westerly winds cross the water and arrive with considerable force on exposed riverfront properties. Summer is mild and pleasant. Winters are cold, frosts occur in the inland streets, and the exposed ridgeline properties cop the full weight of Hobart's frequent westerly fronts. Salt air influence from the estuary is measurable for properties within a few hundred metres of the waterfront.",
    council: "City of Clarence",
    region: "Eastern Shore Hobart / Clarence",
    tradeNotes: {
        "Roofing": "Bellerive's mix of post-war fibro and older weatherboard homes means a lot of corrugated iron roofing is on its second or third decade past ideal service life — the estuary wind exposure accelerates wear on ridge cappings and valley flashings, and moss growth on south-facing aspects is nearly universal on the older stock. The heritage streetscapes near the waterfront have specific material requirements under the Clarence planning scheme.",
        "Insulation": "Hobart is Zone 7 for NCC energy purposes and Bellerive's older 1950s–1960s housing is poorly insulated by any modern standard. The City of Clarence's building stock has among the highest heating energy intensity in the Australian residential sector — upgrading to R5.0 ceiling insulation and adding sub-floor batts to the older pier-and-beam homes is the single most effective thermal improvement, and the government energy rebates make the economics compelling.",
    },
},

"coconut-grove": {
    housing: "Coconut Grove sits about 8km north of Darwin's CBD, and like most of inner Darwin, it carries the legacy of Cyclone Tracy. The Category 4 cyclone that hit on Christmas Day 1974 wiped out the majority of Darwin's housing stock — what you see in Coconut Grove today is almost entirely post-1975 construction. That means 1970s and 1980s lowset and highset homes, predominantly lightweight construction using fibre cement sheeting and timber framing, built to the improved post-Tracy cyclone standards. Some properties have later 1990s–2000s additions. The tropical environment ages buildings hard here — timber deteriorates, paint chalks, and anything not maintained properly shows it within a decade.",
    climate: "Fully tropical — Darwin's climate is one of the most demanding environments for buildings and trades in Australia. The wet season runs November to April, delivering intense monsoonal rain, extreme humidity approaching 90%+, and genuine cyclone risk. The dry season is warm and relatively pleasant, but the transition periods are brutal. Outdoor work is essentially impossible during the worst wet season periods. UV intensity is extreme year-round. Everything degrades faster here than anywhere in temperate Australia.",
    council: "City of Darwin",
    region: "Darwin Northern Suburbs",
    tradeNotes: {
        "Air Conditioning & Heating": "Air conditioning in Darwin is not a luxury — it is a genuine necessity for human health and comfort across the wet season, and the salt-laden humid air means condenser coils and outdoor units corrode significantly faster than in southern cities. Replacement cycles here are typically 8–12 years rather than the 15+ years expected in Melbourne or Sydney. Annual servicing, particularly coil cleaning, is essential practice.",
        "Pest Control": "Darwin's tropical climate produces termite pressure that is among the most severe in Australia — the combination of year-round warmth, wet season moisture, and an abundance of timber construction creates ideal conditions for Mastotermes darwiniensis (giant northern termite) and Coptotermes species. Pre-construction soil treatment and post-construction annual inspections are essential, not optional, in the Northern Territory. AS 3660.1 compliance is the minimum standard.",
        "Building": "All new construction and significant structural work in Darwin must comply with the NT's cyclone provisions under the NCC, which require engineering input and design wind speeds significantly above the southern Australian standard. The post-Tracy Building Act in the NT introduced wind loading requirements that affect everything from roof tie-down design to window glazing specifications. Builders from interstate regularly underestimate the additional compliance cost.",
    },
},

"queanbeyan": {
    housing: "Queanbeyan is ACT-adjacent but NSW — just over the border from Canberra, which has defined the suburb's character in ways that are hard to overstate. The housing stock built up primarily from the 1950s through the 1980s, attracting Canberra public service workers who couldn't afford or didn't want ACT prices. The dominant type is 1960s–1980s brick veneer on generous 600–800 sqm blocks — solid, practical, unremarkable. There are older federation-era homes in the original town area near the Queanbeyan River. More recent years have brought townhouse and medium-density development as the suburb reinvents itself for a younger demographic that still uses Canberra for work but finds the ACT unaffordable.",
    climate: "ACT-adjacent tableland climate — this is not a coastal suburb. Queanbeyan sits at around 600m elevation and gets proper continental winters: regular frosts from May through August, occasional heavy snowfalls (more often on the surrounding hills than the town itself), and genuine overnight lows that rival Canberra's. Summers are warm and dry with the fire risk that comes with ACT-region December–February conditions. The Queanbeyan River valley creates some local cold air pooling on winter nights.",
    council: "Queanbeyan-Palerang Regional Council",
    region: "Capital Region / ACT Border",
    tradeNotes: {
        "Insulation": "Queanbeyan's elevation and cold continental climate make it one of the stronger cases for insulation upgrades in NSW — the 1960s–1980s brick homes here were built to standards that are entirely inadequate by current best practice, and the annual heating bills in these houses reflect it. Zone 7 NCC energy ratings apply in the Queanbeyan area, and ceiling insulation upgrades to R5.0 alongside sub-floor batts on the older pier-and-beam construction make a measurable difference.",
        "Concreting": "The frost cycle at Queanbeyan puts demands on exposed concrete that don't apply in coastal NSW — poorly specified mixes without adequate air entrainment can spall and crack over successive freeze-thaw cycles. Driveways and paths here also sit on shrink-swell clays that create movement problems if the sub-base and control joint design isn't handled correctly. The ACT-adjacent building market means some Queanbeyan residential work involves contractors who are primarily calibrated to ACT pricing and standards.",
        "Building": "Queanbeyan sits in the NSW/ACT bushfire interface zone — significant portions of the suburbs adjoining the ACT border are in bushfire-prone land under the Queanbeyan-Palerang planning scheme, requiring BAL assessments for new construction and certain renovation work. The 2019–2020 Namadgi National Park fires made this a live issue rather than a theoretical compliance question for many residents.",
    },
},

"cleveland": {
    housing: "Cleveland is the administrative and commercial hub of the Redlands — it sits on the western side of Moreton Bay about 25km from Brisbane, and it's a proper bayside suburb with a long coastal history. The housing reflects that layered history: original post-war homes from the 1950s and 1960s on the established streets near the town centre and waterfront, followed by the suburban growth wave of the 1970s and 1980s that pushed the suburb outward onto the lower-lying land. Raby Bay — one of Queensland's two main canal estates — took shape in the 1990s and added a premium waterfront precinct to the mix. Toondah Harbour connects Cleveland to the bay islands, which adds a marine dimension to the suburb that's quite unusual for a mainland QLD suburb.",
    climate: "Moreton Bay coastal — the bay is a moderating influence and Cleveland gets reliable sea breezes off the water, which keeps summer temperatures noticeably lower than the inland Brisbane fringe. Humidity is the challenge in summer, particularly during the January–March thunderstorm season. The bay exposure also creates some wind on the more exposed waterfront properties. Subtropical: warm and wet in summer, mild and dry in winter, generally pleasant.",
    council: "Redland City Council",
    region: "Redlands Coast / Bayside Brisbane",
    tradeNotes: {
        "Roofing": "The bay coastal environment in Cleveland creates the same accelerated roofing material deterioration you'd find anywhere on Moreton Bay — salt spray, humidity, and the subtropical UV load all shorten the service life of standard roof materials. The canal estate properties in Raby Bay have particularly demanding exposure and should be specified to Colorbond Ultra or equivalent marine-grade product where there's direct water frontage.",
        "Landscaping": "The Redlands is known for its strawberry farming and market garden heritage, and the red volcanic soils in parts of the area have genuinely good fertility — but Cleveland's residential areas sit on variable substrates including waterfront reclaimed land and the lower-lying clay plains. The Redland City Council has active vegetation protection policies for remnant Moreton Bay fig and other locally significant species.",
        "Building": "Parts of Cleveland adjoin the conservation zone around the Moreton Bay Marine Park and some residential properties near the waterfront carry vegetation management obligations. Toondah Harbour is subject to a long-running development proposal that has created planning uncertainty for properties in the immediate harbour precinct — builders working near the harbour area should check current zoning status carefully.",
    },
},

"caulfield-north": {
    housing: "Caulfield North is one of Melbourne's more prestigious inner south-east suburbs — 8km from the CBD in the Glen Eira council area, and the housing stock is a genuine showcase of Melbourne's late Victorian and Edwardian residential wealth. The suburb has a remarkable concentration of period homes from the 1880s through the 1920s: grand brick and rendered double-fronted Victorian terraces and freestanding villas, Edwardian bungalows with broad verandahs and ornate fretwork, and a scattering of serious inter-war Art Deco. Some of the largest residential allotments in inner Melbourne are here. Post-war development is conspicuously absent from many of the better streets. Gentrification here happened a long time ago.",
    climate: "Inner south-east Melbourne — the temperate four-season Melbourne climate, somewhat moderated by proximity to Port Phillip Bay. Summer is warm but rarely extreme; the sea breeze comes in reliably from the south-west on hot days. Winters are cool and grey with the southerly dominance that characterises Melbourne's bay influence. The large established tree canopy in Caulfield North's premium streets genuinely moderates temperatures on the worst summer days — it's measurably cooler under a full Elm canopy than on the open streets a suburb away.",
    council: "City of Glen Eira",
    region: "Inner South-East Melbourne / Glen Eira",
    tradeNotes: {
        "Building": "Heritage overlay properties are thick on the ground in Caulfield North — the City of Glen Eira's Heritage Overlay covers significant portions of the suburb's pre-war streetscapes, and any external works on these homes requires heritage assessment and often council approval before a building permit is issued. Builders working here should be familiar with Glen Eira's heritage guidelines and the specific requirements for materials and detailing on HO properties.",
        "Landscaping": "The large established gardens that come with Caulfield North's generous allotments include mature Elms, Oaks, and ornamental plantings of genuine age — the City of Glen Eira's Significant Tree register covers many of these and removal or significant pruning requires council approval. Landscapers here are often working around protected root zones in a way that demands care and knowledge of arboricultural best practice rather than standard suburban garden renovation approach.",
        "Painting": "The Victorian and Edwardian homes in Caulfield North almost universally have multiple layers of historical paint that may include lead-based coatings in the earlier applications — exterior and interior painting work on pre-1970 homes in this suburb should follow AS 4361.2 lead paint procedures, with dust management and correct disposal of stripped material. The rendered masonry facades common on Victorian villas require specific surface preparation and breathable coating systems to avoid moisture trapping.",
    },
},
