export const JOB_TYPES: Record<string, string[]> = {
    "Plumbing": [
        "blocked drain repair",
        "hot water system installation",
        "hot water system replacement",
        "leaking tap repair",
        "burst pipe repair",
        "toilet repair and replacement",
        "pipe relining",
        "CCTV drain inspection",
        "backflow prevention testing",
        "sewer line replacement",
        "bathroom renovation plumbing",
        "gas hot water system repair",
        "water leak detection",
        "rainwater tank installation",
        "thermostatic mixing valve installation",
    ],
    "Electrical": [
        "switchboard upgrade",
        "safety switch installation",
        "power point installation",
        "lighting installation",
        "ceiling fan installation",
        "smoke alarm installation",
        "electrical fault finding",
        "home rewiring",
        "NBN point installation",
        "TV antenna installation",
        "test and tag",
        "EV charger installation",
        "split system air conditioner electrical",
        "home automation and smart wiring",
        "security camera and CCTV wiring",
    ],
    "Carpentry": [
        "timber deck construction",
        "pergola building",
        "door frame repair and replacement",
        "built-in wardrobe installation",
        "timber staircase construction",
        "skirting board installation",
        "timber fence and gate construction",
        "window and door installation",
        "timber retaining wall construction",
        "wall framing and structural carpentry",
        "timber cladding installation",
        "floating floor installation",
        "balustrade and handrail installation",
        "outdoor privacy screen installation",
        "formwork carpentry",
    ],
    "Landscaping": [
        "landscape design",
        "retaining wall construction",
        "backyard landscaping",
        "front yard landscaping",
        "artificial turf installation",
        "outdoor living area design",
        "native garden design",
        "paving and pathways",
        "garden bed construction",
        "garden bed edging",
        "decking installation",
        "turf laying",
        "garden lighting installation",
        "landscape construction",
    ],
    "Roofing": [
        "roof leak repair",
        "roof tile replacement",
        "Colorbond roof installation",
        "roof restoration",
        "roof painting",
        "ridge capping repair",
        "metal roof replacement",
        "roof flashing repair",
        "gutter guard installation",
        "skylight installation",
        "whirlybird installation",
        "roof inspection",
        "emergency roof repair",
        "asbestos roof removal",
        "roof rebedding and repointing",
    ],
    "Painting": [
        "interior painting",
        "exterior painting",
        "house painting",
        "roof painting",
        "spray painting",
        "fence painting",
        "kitchen cupboard painting",
        "deck staining and painting",
        "colour consultation",
        "strata painting",
        "wallpaper removal",
        "feature wall painting",
        "ceiling painting",
        "commercial painting",
        "weatherboard painting",
    ],
    "Cleaning": [
        "end of lease cleaning",
        "bond cleaning",
        "office cleaning",
        "carpet steam cleaning",
        "window cleaning",
        "pressure washing",
        "deep cleaning",
        "hoarder clean-up",
        "oven cleaning",
        "strata cleaning",
        "commercial kitchen cleaning",
        "mould cleaning and removal",
        "after-builders cleaning",
        "NDIS cleaning",
        "upholstery cleaning",
    ],
    "Building": [
        "home extension and addition",
        "granny flat construction",
        "bathroom renovation",
        "kitchen renovation and remodel",
        "new home build and construction",
        "structural wall removal",
        "second storey addition",
        "property renovation and refurbishment",
        "carport and garage construction",
        "Colorbond shed and outbuilding construction",
        "retaining wall construction",
        "concrete slab and foundation work",
        "duplex and dual occupancy construction",
        "knockdown rebuild",
        "house raising and restumping",
    ],
    "Concreting": [
        "concrete driveway installation",
        "exposed aggregate driveway",
        "concrete slab for shed",
        "coloured concrete",
        "concrete path installation",
        "honed concrete",
        "stamped concrete patio",
        "concrete pool surrounds",
        "concrete cutting",
        "concrete grinding and polishing",
        "concrete resurfacing",
        "stencilled concrete",
        "house slab pouring",
        "concrete retaining wall",
        "concrete repair and crack filling",
    ],
    "Tiling": [
        "bathroom tiling",
        "kitchen splashback tiling",
        "floor tiling",
        "wall tiling",
        "outdoor tiling",
        "pool tiling",
        "waterproofing and tiling",
        "tile removal",
        "laundry tiling",
        "balcony tiling",
        "tile regrouting",
        "mosaic tiling",
        "large format tiling",
        "herringbone tiling",
        "bathroom renovation tiling",
    ],
    "Plastering": [
        "gyprock installation",
        "gyprock repair",
        "cornice installation",
        "ceiling plastering",
        "wall patching",
        "plaster crack repair",
        "ornamental plastering",
        "plasterboard installation",
        "ceiling rose installation",
        "square set plastering",
        "suspended ceiling installation",
        "water damage plaster repair",
        "Villaboard installation",
        "plaster sanding and finishing",
        "steel stud framing",
    ],
    "Fencing": [
        "Colorbond fencing installation",
        "timber paling fence installation",
        "pool fencing installation",
        "glass pool fencing",
        "aluminium pool fencing",
        "pool fence compliance inspection",
        "boundary fence replacement",
        "retaining wall construction",
        "front fence installation",
        "Colorbond fence with lattice top",
        "security fencing",
        "picket fence installation",
        "aluminium slat fencing",
        "farm fencing",
        "fence gate installation",
    ],
    "Demolition": [
        "house demolition",
        "asbestos removal",
        "partial demolition",
        "strip-out demolition",
        "commercial demolition",
        "concrete removal",
        "garage demolition",
        "demolition and site clearing",
        "pool demolition",
        "shed demolition and removal",
        "brick wall demolition",
        "knockdown rebuild",
        "demolition permit application",
        "asbestos testing and inspection",
    ],
    "Excavation": [
        "site cut and fill",
        "pool excavation",
        "bobcat hire",
        "excavator hire",
        "trench digging",
        "land clearing",
        "rock hammering",
        "foundation excavation",
        "basement excavation",
        "mini excavator hire",
        "driveway excavation",
        "retaining wall excavation",
        "stump and tree removal",
        "levelling and grading",
    ],
    "Air Conditioning & Heating": [
        "split system air conditioner installation",
        "ducted air conditioning installation",
        "air conditioner repair and service",
        "multi-split air conditioning installation",
        "ducted gas heating installation",
        "evaporative cooling installation",
        "air conditioning cleaning and maintenance",
        "ducted heating repair",
        "air conditioner replacement",
        "zone control system installation",
        "ceiling cassette air conditioner installation",
        "hydronic heating installation",
        "gas ducted heating to reverse cycle conversion",
    ],
    "Solar & Energy": [
        "solar panel installation",
        "solar battery installation",
        "solar system repair and maintenance",
        "solar inverter replacement",
        "EV charger installation",
        "hot water heat pump installation",
        "solar hot water system installation",
        "solar system upgrade",
        "off-grid solar system installation",
        "commercial solar installation",
        "solar panel cleaning",
        "home energy audit",
        "solar feed-in tariff optimisation",
    ],
    "Pest Control": [
        "termite inspection",
        "termite treatment",
        "termite barrier installation",
        "pre-purchase pest inspection",
        "cockroach treatment",
        "possum removal",
        "rodent control",
        "bed bug treatment",
        "spider spray",
        "ant treatment",
        "white ant treatment",
        "flea treatment",
        "wasp removal",
        "bee removal",
        "end of lease pest control",
    ],
    "Tree Lopping & Removal": [
        "tree removal",
        "tree lopping",
        "stump grinding",
        "tree pruning",
        "palm tree removal",
        "dead tree removal",
        "emergency tree removal",
        "tree trimming",
        "land clearing",
        "arborist report",
        "tree root removal",
        "branch removal",
        "powerline clearance",
        "council tree removal permit",
        "mulch supply and wood chipping",
    ],
    "Gardening & Lawn Care": [
        "garden maintenance",
        "hedge trimming",
        "garden clean-up",
        "weed removal and spraying",
        "mulching",
        "pruning",
        "garden bed maintenance",
        "native plant installation",
        "green waste removal",
        "pre-sale garden makeover",
        "fertilising and lawn feeding",
        "garden design",
        "planting services",
        "pest and disease treatment",
        "leaf removal and autumn clean-up",
    ],
    "Mowing": [
        "lawn mowing",
        "ride-on mowing",
        "acreage mowing",
        "lawn edging",
        "grass slashing",
        "buffalo grass care",
        "Sir Walter turf maintenance",
        "kikuyu lawn care",
        "lawn aeration",
        "lawn fertilising",
        "nature strip mowing",
        "regular lawn mowing service",
        "commercial lawn mowing",
        "top dressing",
        "lawn weed control",
    ],
    "Pool & Spa": [
        "pool fence inspection",
        "pool resurfacing",
        "green pool clean-up",
        "pool pump repair",
        "pool equipment installation",
        "salt chlorinator installation",
        "pool compliance certificate",
        "pool heating installation",
        "pool leak detection",
        "pool maintenance service",
        "spa repair",
        "pool filter cleaning",
        "pool tile repair",
        "pool safety inspection",
    ],
    "Bathroom Renovation": [
        "bathroom demolition and rebuild",
        "bathroom tiling",
        "bathroom waterproofing",
        "bathroom waterproofing certificate",
        "frameless shower screen installation",
        "bath to shower conversion",
        "vanity installation",
        "wall-hung vanity installation",
        "floor-to-ceiling tiles bathroom",
        "bathroom stripout",
        "ensuite renovation",
        "small bathroom renovation",
        "shower screen replacement",
        "bathroom tap installation",
        "bath resurfacing",
    ],
    "Kitchen Renovation": [
        "stone benchtop installation",
        "Caesarstone benchtop installation",
        "flat-pack kitchen installation",
        "kitchen island bench installation",
        "rangehood installation",
        "kitchen splashback installation",
        "kitchen cabinet replacement",
        "kitchen demolition and rebuild",
        "kitchen benchtop replacement",
        "kitchen plumbing relocation",
        "kitchen sink installation",
        "budget kitchen renovation",
        "kitchen electrical upgrade",
        "custom kitchen cabinetry",
        "kitchen renovation project management",
    ],
    "Flooring": [
        "timber floor sanding and polishing",
        "vinyl plank installation",
        "hybrid flooring installation",
        "carpet laying",
        "engineered timber flooring installation",
        "laminate flooring installation",
        "floating floor installation",
        "timber floor repair",
        "polished concrete flooring",
        "carpet removal",
        "floor levelling",
        "bamboo flooring installation",
        "staircase sanding and polishing",
        "epoxy flooring",
        "timber floor staining",
    ],
    "Glazing & Windows": [
        "broken window repair",
        "double glazing retrofit",
        "window replacement",
        "shower screen installation",
        "glass balustrade installation",
        "emergency glass replacement",
        "pet door installation glass",
        "fly screen repair",
        "security screen door installation",
        "glass splashback installation",
        "window reglazing",
        "pool fencing glass",
        "sliding door glass replacement",
        "commercial shopfront glazing",
        "mirror installation",
    ],
    "Guttering": [
        "gutter replacement",
        "gutter cleaning",
        "gutter guard installation",
        "downpipe repair",
        "fascia and soffit repair",
        "Colorbond gutter installation",
        "gutter leak repair",
        "leaf guard installation",
        "Zincalume gutter installation",
        "box gutter repair",
        "downpipe installation",
        "rainwater tank connection to gutters",
        "gutter resealing",
        "stormwater drainage repair",
        "roof plumbing services",
    ],
    "Handyman": [
        "furniture assembly and flat-pack installation",
        "door repair and replacement",
        "picture and mirror hanging",
        "TV wall mounting",
        "gutter cleaning and repair",
        "flyscreen repair and replacement",
        "curtain rod and blind installation",
        "plaster and drywall repair",
        "fence and gate repair",
        "shelving installation",
        "deck maintenance and oiling",
        "clothesline installation",
        "smoke alarm installation and replacement",
        "general property maintenance",
        "minor plumbing repairs",
    ],
    "Insulation": [
        "ceiling insulation installation",
        "wall insulation installation",
        "underfloor insulation",
        "insulation batts installation",
        "spray foam insulation",
        "insulation removal and replacement",
        "acoustic insulation",
        "roof insulation top-up",
        "cavity wall insulation",
        "garage door insulation",
        "thermal imaging assessment",
        "commercial insulation",
        "reflective foil insulation",
        "blown-in insulation",
    ],
    "Locksmith": [
        "emergency lockout service",
        "lock change and replacement",
        "deadbolt installation",
        "key cutting",
        "car lockout service",
        "master key system installation",
        "restricted key system",
        "digital lock installation",
        "lock rekeying",
        "window lock installation",
        "screen door lock replacement",
        "after-hours locksmith",
        "safe opening and repair",
        "transponder key programming",
        "commercial locksmith services",
    ],
    "Paving": [
        "brick paving installation",
        "driveway paving",
        "concrete paver installation",
        "sandstone paving",
        "pool paving",
        "travertine paving",
        "paver repair and relaying",
        "patio paving",
        "garden path paving",
        "limestone paving",
        "bluestone paving",
        "crazy paving",
        "permeable paving",
        "paver sealing and cleaning",
    ],
    "Rendering": [
        "cement rendering",
        "acrylic rendering",
        "texture coating",
        "render repair",
        "house rendering",
        "coloured render",
        "polystyrene rendering",
        "blueboard rendering",
        "Hebel rendering",
        "fence rendering",
        "retaining wall rendering",
        "concrete resurfacing",
        "render crack repair",
        "bagging",
    ],
    "Scaffolding": [
        "scaffolding hire residential",
        "scaffolding hire commercial",
        "mobile scaffold tower hire",
        "Kwikstage scaffolding hire",
        "scaffolding erection and dismantle",
        "scaffold for painting",
        "scaffold for roof access",
        "aluminium scaffolding hire",
        "scaffolding for renovations",
        "edge protection scaffolding",
        "scaffolding for rendering",
        "shrink wrap scaffolding",
        "scaffolding safety inspection",
    ],
    "Security Systems": [
        "CCTV installation",
        "home alarm system installation",
        "security camera installation",
        "intercom system installation",
        "back-to-base monitoring",
        "access control system installation",
        "smart home security system",
        "alarm system upgrade",
        "video doorbell installation",
        "motion sensor installation",
        "security system servicing",
        "commercial CCTV installation",
        "security lighting installation",
        "alarm monitoring service",
    ],
    "Shopfitting": [
        "retail shop fit-out",
        "restaurant and cafe fit-out",
        "office fit-out and refurbishment",
        "commercial joinery and custom fixtures",
        "retail display unit design",
        "bar and pub fit-out",
        "medical and dental practice fit-out",
        "pharmacy fit-out",
        "gym and fitness studio fit-out",
        "beauty salon fit-out",
        "shopping centre tenancy fit-out",
        "commercial signage and branding installation",
        "franchise and retail rollout fit-out",
        "shop strip-out and make-good",
        "kiosk and pop-up shop fit-out",
    ],
    "Signwriting": [
        "shop front signage",
        "vehicle signwriting",
        "vehicle wrapping",
        "building signage",
        "LED sign installation",
        "window frosting",
        "A-frame signs",
        "banner printing",
        "vinyl lettering",
        "3D lettering signage",
        "lightbox signage",
        "construction site signage",
        "fleet vehicle graphics",
        "wall graphics and murals",
        "real estate signage",
    ],
    "Stonemasonry": [
        "sandstone restoration",
        "stone cladding installation",
        "sandstone wall repair",
        "stone retaining wall construction",
        "stone fireplace installation",
        "heritage stonework restoration",
        "natural stone paving",
        "granite benchtop installation",
        "sandstone steps installation",
        "stone feature wall",
        "stone letterbox construction",
        "sandstone pool surrounds",
        "stone column installation",
        "bluestone paving",
    ],
    "Waterproofing": [
        "bathroom waterproofing",
        "shower waterproofing",
        "balcony waterproofing",
        "basement waterproofing",
        "waterproofing membrane installation",
        "leaking shower repair",
        "leaking balcony repair",
        "roof waterproofing",
        "retaining wall waterproofing",
        "waterproofing over tiles",
        "planter box waterproofing",
        "laundry waterproofing",
        "crack injection waterproofing",
        "wet area waterproofing certificate",
        "remedial waterproofing",
    ],
    "Welding & Fabrication": [
        "steel fabrication",
        "aluminium welding",
        "handrail fabrication",
        "gate fabrication",
        "mobile welding",
        "structural steel installation",
        "metal fence fabrication",
        "stainless steel fabrication",
        "welding repairs",
        "custom metalwork",
        "steel staircase fabrication",
        "trailer repairs",
        "balustrade installation",
        "emergency welding repair",
    ],
    "Garage Doors": [
        "garage door repair",
        "roller door repair",
        "automatic garage door opener installation",
        "garage door spring replacement",
        "panel lift door installation",
        "Colorbond garage door installation",
        "garage door motor replacement",
        "tilt door repair and conversion",
        "garage door remote programming",
        "new garage door installation",
        "garage door servicing and maintenance",
        "roller door motor installation",
        "emergency garage door repair",
        "commercial roller shutter repair",
        "garage door track replacement",
    ],
    "Blinds & Curtains": [
        "roller blinds installation",
        "plantation shutters installation",
        "venetian blinds installation",
        "curtain installation",
        "outdoor blinds installation",
        "motorised blinds installation",
        "blockout blinds installation",
        "curtain track installation",
        "roman blinds installation",
        "vertical blinds installation",
        "sheer curtains installation",
        "blind repair",
        "security roller shutters",
        "honeycomb blinds installation",
        "awning installation",
    ],
    "Cabinet Making": [
        "custom kitchen cabinetry",
        "bathroom vanity custom build",
        "built-in wardrobe and robe fitout",
        "entertainment unit and TV cabinet",
        "laundry cabinetry and storage",
        "kitchen cabinet resurfacing",
        "custom home office and study desk",
        "butlers pantry cabinetry",
        "custom bookshelf and shelving",
        "garage storage and workshop cabinetry",
        "window seat and bench seat with storage",
        "antique furniture restoration",
        "commercial reception desk",
        "kitchen benchtop replacement",
    ],
    "Decking": [
        "Merbau decking installation",
        "composite decking installation",
        "hardwood decking installation",
        "timber deck restoration",
        "deck oiling and staining",
        "deck sanding and sealing",
        "treated pine decking installation",
        "elevated deck construction",
        "pool decking installation",
        "deck repair and replacement",
        "timber deck board replacement",
        "Spotted Gum decking installation",
        "deck balustrade installation",
        "outdoor entertaining area construction",
    ],
    "Drainage": [
        "stormwater drainage installation",
        "French drain installation",
        "ag pipe installation",
        "blocked drain clearing",
        "soak well installation",
        "stormwater pit installation",
        "drain camera inspection",
        "sewer drainage repair",
        "surface drainage systems",
        "yard drainage solutions",
        "downpipe and gutter drainage",
        "retaining wall drainage",
        "subsurface drainage",
        "hydro jetting drain cleaning",
    ],
    "Gas Fitting": [
        "gas leak detection and repair",
        "gas cooktop installation",
        "gas heater installation",
        "gas hot water system installation",
        "gas bayonet point installation",
        "gas appliance servicing",
        "gas line installation",
        "gas BBQ connection",
        "gas to electric conversion",
        "gas heater removal and disconnection",
        "gas compliance certificate",
        "carbon monoxide testing",
        "gas pool heater installation",
    ],
    "Irrigation": [
        "irrigation system installation",
        "sprinkler system installation",
        "drip irrigation installation",
        "reticulation installation",
        "reticulation repairs",
        "irrigation system repair",
        "bore water system installation",
        "garden irrigation design",
        "pop-up sprinkler installation",
        "smart irrigation controller installation",
        "irrigation system maintenance",
        "automatic watering system",
        "lawn irrigation",
        "irrigation solenoid replacement",
        "waterwise irrigation",
    ],
    "Rubbish Removal": [
        "skip bin hire",
        "green waste removal",
        "hard rubbish collection",
        "deceased estate clean-up",
        "construction waste removal",
        "e-waste disposal",
        "furniture removal and disposal",
        "same-day rubbish removal",
        "commercial rubbish removal",
        "mattress removal",
        "garage clean-out",
        "demolition waste removal",
        "appliance removal",
        "hoarder house clean-up",
        "property pre-sale clean-out",
    ],
    "Shed Building": [
        "Colorbond shed installation",
        "garage construction",
        "barn shed construction",
        "farm shed construction",
        "garden shed installation",
        "workshop shed construction",
        "shed concrete slab preparation",
        "shed council approval",
        "custom steel shed construction",
        "Colorbond garage installation",
        "shed kit assembly and erection",
        "liveable shed construction",
        "carport construction",
        "machinery shed construction",
        "cyclone-rated shed installation",
    ],
    "Splashbacks": [
        "glass splashback installation",
        "tiled splashback installation",
        "mirror splashback installation",
        "acrylic splashback installation",
        "kitchen splashback replacement",
        "bathroom splashback installation",
        "laundry splashback installation",
        "coloured glass splashback",
        "printed splashback",
        "splashback behind cooktop",
        "subway tile splashback",
        "pressed metal splashback",
        "stainless steel splashback installation",
    ],
    "Stump Removal": [
        "stump grinding",
        "tree stump removal",
        "root grinding",
        "palm stump removal",
        "land clearing stump removal",
        "house restumping",
        "house reblocking",
        "pier replacement",
        "house relevelling",
        "concrete stump replacement",
        "steel stump installation",
        "partial restumping",
        "foundation underpinning",
    ],
    "Surveying": [
        "boundary survey",
        "title re-establishment survey",
        "contour and detail survey",
        "subdivision survey",
        "building setout survey",
        "identification survey",
        "strata plan survey",
        "feature and level survey",
        "topographic survey",
        "fence line survey",
        "easement survey",
        "property boundary marking",
        "drone survey",
    ],
};

export function jobToSlug(job: string): string {
    return job.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

export function slugToJob(slug: string): string {
    return slug.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
}

export const TRADE_COST_GUIDE: Record<string, { unit: string; low: number; high: number }> = {
    "Plumbing": { unit: "/hr", low: 80, high: 200 },
    "Electrical": { unit: "/hr", low: 70, high: 130 },
    "Carpentry": { unit: "/hr", low: 80, high: 140 },
    "Landscaping": { unit: "/m²", low: 50, high: 150 },
    "Roofing": { unit: "/hr", low: 50, high: 100 },
    "Painting": { unit: "/hr", low: 40, high: 70 },
    "Cleaning": { unit: "/hr", low: 35, high: 65 },
    "Building": { unit: "/hr", low: 80, high: 160 },
    "Concreting": { unit: "/m²", low: 50, high: 150 },
    "Tiling": { unit: "/m²", low: 45, high: 120 },
    "Plastering": { unit: "/hr", low: 45, high: 90 },
    "Fencing": { unit: "/m", low: 100, high: 180 },
    "Demolition": { unit: "/hr", low: 60, high: 120 },
    "Excavation": { unit: "/hr", low: 90, high: 180 },
    "Air Conditioning & Heating": { unit: " installed", low: 600, high: 2500 },
    "Solar & Energy": { unit: " installed", low: 3300, high: 8000 },
    "Pest Control": { unit: " per inspection", low: 250, high: 500 },
    "Tree Lopping & Removal": { unit: " per job", low: 350, high: 3000 },
    "Gardening & Lawn Care": { unit: "/hr", low: 50, high: 100 },
    "Mowing": { unit: "/hr", low: 40, high: 80 },
    "Pool & Spa": { unit: "/hr", low: 60, high: 120 },
    "Bathroom Renovation": { unit: " per project", low: 15000, high: 35000 },
    "Kitchen Renovation": { unit: " per project", low: 20000, high: 45000 },
    "Flooring": { unit: "/m²", low: 40, high: 150 },
    "Glazing & Windows": { unit: "/hr", low: 60, high: 130 },
    "Guttering": { unit: "/m", low: 30, high: 80 },
    "Handyman": { unit: "/hr", low: 60, high: 100 },
    "Insulation": { unit: "/m²", low: 10, high: 25 },
    "Locksmith": { unit: " per job", low: 80, high: 250 },
    "Paving": { unit: "/m²", low: 50, high: 150 },
    "Rendering": { unit: "/m²", low: 30, high: 80 },
    "Scaffolding": { unit: "/week", low: 200, high: 800 },
    "Security Systems": { unit: " installed", low: 800, high: 3000 },
    "Shopfitting": { unit: "/m²", low: 500, high: 2000 },
    "Signwriting": { unit: " per job", low: 200, high: 2000 },
    "Stonemasonry": { unit: "/m²", low: 100, high: 300 },
    "Waterproofing": { unit: "/m²", low: 30, high: 80 },
    "Welding & Fabrication": { unit: "/hr", low: 80, high: 150 },
    "Garage Doors": { unit: " installed", low: 800, high: 3000 },
    "Blinds & Curtains": { unit: " per window", low: 150, high: 600 },
    "Cabinet Making": { unit: " per project", low: 2000, high: 15000 },
    "Decking": { unit: "/m²", low: 200, high: 1000 },
    "Drainage": { unit: " per job", low: 300, high: 2000 },
    "Gas Fitting": { unit: " per job", low: 150, high: 600 },
    "Irrigation": { unit: " installed", low: 500, high: 3000 },
    "Rubbish Removal": { unit: " per load", low: 150, high: 600 },
    "Shed Building": { unit: " installed", low: 3000, high: 20000 },
    "Splashbacks": { unit: " installed", low: 400, high: 1500 },
    "Stump Removal": { unit: " per stump", low: 150, high: 600 },
    "Surveying": { unit: " per survey", low: 500, high: 2500 },
};

export const TRADE_CATEGORIES = [
    "Plumbing",
    "Electrical",
    "Carpentry",
    "Landscaping",
    "Roofing",
    "Painting",
    "Cleaning",
    "Building",
    "Concreting",
    "Tiling",
    "Plastering",
    "Fencing",
    "Demolition",
    "Excavation",
    "Air Conditioning & Heating",
    "Solar & Energy",
    "Pest Control",
    "Tree Lopping & Removal",
    "Gardening & Lawn Care",
    "Mowing",
    "Pool & Spa",
    "Bathroom Renovation",
    "Kitchen Renovation",
    "Flooring",
    "Glazing & Windows",
    "Guttering",
    "Handyman",
    "Insulation",
    "Locksmith",
    "Paving",
    "Rendering",
    "Scaffolding",
    "Security Systems",
    "Shopfitting",
    "Signwriting",
    "Stonemasonry",
    "Waterproofing",
    "Welding & Fabrication",
    "Garage Doors",
    "Blinds & Curtains",
    "Cabinet Making",
    "Decking",
    "Drainage",
    "Gas Fitting",
    "Irrigation",
    "Rubbish Removal",
    "Shed Building",
    "Splashbacks",
    "Stump Removal",
    "Surveying",
    "Other"
] as const;

export type LocationData = {
    [state: string]: {
        [city: string]: string[];
    };
};

export const AUSTRALIA_LOCATIONS: LocationData = {
    "VIC": {
        "Geelong": [
            "Anakie", "Armstrong Creek", "Barwon Heads", "Belmont", "Clifton Springs",
            "Corio", "Drysdale", "East Geelong", "Geelong", "Geelong West",
            "Grovedale", "Hamlyn Heights", "Highton", "Lara", "Leopold",
            "Moolap", "Newcomb", "Newtown", "Norlane", "North Geelong",
            "Ocean Grove", "Portarlington", "South Geelong", "Thomson", "Torquay",
            "Waurn Ponds", "Whittington"
        ],
        "Melbourne": [
            "Albert Park", "Armadale", "Ascot Vale", "Ashburton", "Bentleigh",
            "Box Hill", "Brighton", "Brunswick", "Bundoora", "Carlton",
            "Camberwell", "Cheltenham", "Clayton", "Coburg", "Collingwood",
            "Craigieburn", "Cranbourne", "Dandenong", "Doncaster", "Doncaster East",
            "Epping", "Essendon", "Fitzroy", "Footscray", "Frankston",
            "Glen Waverley", "Hawthorn", "Heidelberg", "Hoppers Crossing", "Keilor",
            "Knox", "Lalor", "Lilydale", "Melbourne CBD", "Mentone",
            "Moonee Ponds", "Moorabbin", "Mordialloc", "Mount Waverley", "Mulgrave",
            "Narre Warren", "Noble Park", "Northcote", "Nunawading", "Oakleigh",
            "Pakenham", "Point Cook", "Preston", "Richmond", "Ringwood",
            "Rowville", "South Yarra", "Springvale", "St Kilda", "Sunbury",
            "Sunshine", "Surrey Hills", "Tarneit", "Thomastown", "Tullamarine",
            "Wantirna", "Werribee", "Williamstown", "Windsor", "Yarraville"
        ],
        "Ballarat": [
            "Alfredton", "Ballarat Central", "Ballarat East", "Ballarat North",
            "Brown Hill", "Delacombe", "Epping", "Invermay Park", "Miners Rest",
            "Mount Clear", "Mount Helen", "Nerrina", "Sebastopol", "Wendouree"
        ],
        "Bendigo": [
            "Bendigo", "Epsom", "Flora Hill", "Golden Square", "Kangaroo Flat",
            "Kennington", "Maiden Gully", "Strathdale", "Strathfieldsaye"
        ],
    },
    "NSW": {
        "Sydney": [
            "Ashfield", "Auburn", "Bankstown", "Baulkham Hills", "Blacktown",
            "Bondi", "Bondi Junction", "Botany", "Burwood", "Campbelltown",
            "Castle Hill", "Chatswood", "Cronulla", "Dee Why", "Epping",
            "Fairfield", "Glebe", "Gordon", "Hornsby", "Hurstville",
            "Kogarah", "Lane Cove", "Liverpool", "Manly", "Marrickville",
            "Miranda", "Mosman", "Newtown", "North Sydney", "Parramatta",
            "Penrith", "Randwick", "Redfern", "Ryde", "St Ives",
            "St Leonards", "Strathfield", "Surry Hills", "Sydney CBD", "Ultimo",
            "Wahroonga", "Wentworthville", "Westmead", "Windsor", "Woollahra"
        ],
        "Newcastle": [
            "Adamstown", "Broadmeadow", "Charlestown", "Glendale", "Hamilton",
            "Jesmond", "Kotara", "Lambton", "Mayfield", "Merewether",
            "New Lambton", "Newcastle CBD", "Shortland", "Wallsend", "Waratah"
        ],
        "Wollongong": [
            "Albion Park", "Corrimal", "Dapto", "Figtree", "Fairy Meadow",
            "Helensburgh", "Kiama", "Nowra", "Port Kembla", "Shellharbour",
            "Thirroul", "Unanderra", "Wollongong CBD"
        ],
        "Central Coast": [
            "Avoca Beach", "Bateau Bay", "Gosford", "Kariong", "Killarney Vale",
            "Niagara Park", "Terrigal", "Tuggerah", "Umina Beach", "Wamberal",
            "Warnervale", "Wyong"
        ],
    },
    "QLD": {
        "Brisbane": [
            "Annerley", "Ashgrove", "Aspley", "Bowen Hills", "Brisbane CBD",
            "Brookside", "Bulimba", "Capalaba", "Carindale", "Chermside",
            "Cleveland", "Coorparoo", "Darra", "Eight Mile Plains", "Everton Park",
            "Fortitude Valley", "Greenslopes", "Hamilton", "Holland Park", "Indooroopilly",
            "Inala", "Ipswich", "Kedron", "Keperra", "Logan",
            "Lutwyche", "Moorooka", "Mount Gravatt", "Nundah", "Paddington",
            "Redcliffe", "Redlands", "Rochedale", "Rocklea", "Sandgate",
            "Springwood", "Stafford", "Sunnybank", "Taringa", "Toowong",
            "Upper Mount Gravatt", "Virginia", "Wavell Heights", "Willowbank", "Woolloongabba"
        ],
        "Gold Coast": [
            "Arundel", "Ashmore", "Benowa", "Biggera Waters", "Broadbeach",
            "Bundall", "Burleigh Heads", "Coomera", "Coolangatta", "Currumbin",
            "Helensvale", "Hope Island", "Labrador", "Main Beach", "Miami",
            "Mudgeeraba", "Nerang", "Oxenford", "Palm Beach", "Parkwood",
            "Robina", "Runaway Bay", "Southport", "Surfers Paradise", "Tugun",
            "Upper Coomera", "Varsity Lakes"
        ],
        "Sunshine Coast": [
            "Buderim", "Caloundra", "Coolum Beach", "Forest Glen", "Kawana Waters",
            "Maleny", "Maroochydore", "Mooloolaba", "Nambour", "Noosa Heads",
            "Noosaville", "Sippy Downs", "Tewantin", "Woombye"
        ],
        "Townsville": [
            "Aitkenvale", "Belgian Gardens", "Condon", "Cranbrook", "Douglas",
            "Garbutt", "Idalia", "Kirwan", "Mount Louisa", "Mundingburra",
            "North Ward", "Pimlico", "Rasmussen", "Rowes Bay", "Townsville CBD"
        ],
    },
    "WA": {
        "Perth": [
            "Armadale", "Baldivis", "Balga", "Bassendean", "Bayswater",
            "Belmont", "Bentley", "Burns Beach", "Butler", "Canning Vale",
            "Cannington", "Carlisle", "Clarkson", "Cloverdale", "Cockburn",
            "Como", "Cottesloe", "Ellenbrook", "Fremantle", "Girrawheen",
            "Gosnells", "Greenwood", "Hamilton Hill", "Innaloo", "Joondalup",
            "Joondanna", "Karrinyup", "Kelmscott", "Kenwick", "Kingsley",
            "Leederville", "Leeming", "Mandurah", "Marangaroo", "Melville",
            "Midland", "Mirrabooka", "Morley", "Mount Lawley", "Mount Pleasant",
            "Mundaring", "Nollamara", "North Perth", "Northbridge", "O'Connor",
            "Osborne Park", "Perth CBD", "Rockingham", "Scarborough", "South Perth",
            "Spearwood", "Stirling", "Subiaco", "Swan View", "Victoria Park",
            "Wanneroo", "Wembley", "Whitford", "Willeton", "Yokine"
        ],
    },
    "SA": {
        "Adelaide": [
            "Adelaide CBD", "Aldinga Beach", "Belair", "Blackwood", "Brighton",
            "Campbelltown", "Christie Downs", "Christies Beach", "Edwardstown", "Elizabeth",
            "Enfield", "Glenelg", "Glenside", "Golden Grove", "Hallett Cove",
            "Henley Beach", "Hillcrest", "Holden Hill", "Kensington", "Kilburn",
            "Lonsdale", "Magill", "Marion", "Mawson Lakes", "Mitcham",
            "Modbury", "Morphett Vale", "Mount Barker", "Mount Gambier", "Munno Para",
            "Noarlunga", "Norwood", "O'Halloran Hill", "Para Hills", "Parafield Gardens",
            "Port Adelaide", "Prospect", "Salisbury", "Semaphore", "St Marys",
            "Tea Tree Gully", "Torrensville", "Unley", "Victor Harbor", "Walkerville",
            "Woodville"
        ],
    },
    "ACT": {
        "Canberra": [
            "Belconnen", "Bruce", "Canberra CBD", "Casey", "Chifley",
            "Dickson", "Fadden", "Florey", "Gungahlin", "Kaleen",
            "Kingston", "Lyneham", "Macquarie", "Manuka", "Molonglo Valley",
            "Narrabundah", "Ngunnawal", "Palmerston", "Queanbeyan", "Reid",
            "Scullin", "Tuggeranong", "Weston Creek", "Woden", "Wright"
        ],
    },
    "TAS": {
        "Hobart": [
            "Battery Point", "Bellerive", "Claremont", "Glenorchy", "Hobart CBD",
            "Howrah", "Kingston", "Lindisfarne", "Moonah", "New Town",
            "Rosny", "Sandy Bay", "Sorell", "West Hobart"
        ],
        "Launceston": [
            "Devonport", "Kings Meadows", "Launceston CBD", "Newstead", "Newnham",
            "Prospect Vale", "Riverside", "Rocherlea", "South Launceston", "Youngtown"
        ],
    },
    "NT": {
        "Darwin": [
            "Bakewell", "Coconut Grove", "Darwin CBD", "Fannie Bay", "Humpty Doo",
            "Karama", "Leanyer", "Malak", "Millner", "Moil",
            "Nightcliff", "Palmerston", "Rapid Creek", "Stuart Park", "Tiwi",
            "Wanguri", "Woodroffe"
        ],
    },
};

export const STATE_LICENSING: Record<string, Record<string, string>> = {
    "Plumbing": {
        "VIC": "In Victoria, all plumbing work must be performed by a licensed plumber registered with the Victorian Building Authority (VBA). Work over $750 requires a Certificate of Compliance.",
        "NSW": "In NSW, plumbers must hold a Plumbing Contractor Licence from NSW Fair Trading. All work must comply with the Plumbing Code of Australia.",
        "QLD": "In Queensland, a QBCC Plumbing Licence is required for all plumbing work. Work over $3,300 requires a contract.",
        "WA": "In WA, plumbers must be licensed with the Building and Energy division. All gasfitting work also requires a separate gas licence.",
        "SA": "In SA, plumbers must be licensed through Consumer and Business Services (CBS). A Certificate of Compliance is required for prescribed plumbing work.",
        "TAS": "In Tasmania, plumbing work must be performed by a licensed plumber under the Building Act 2016.",
        "ACT": "In the ACT, plumbers require a licence from the ACT Planning and Land Authority. All work must meet the Plumbing Code of Australia.",
        "NT": "In the NT, plumbers must hold a licence from NT Build. Emergency plumbing work can proceed without a permit but must be reported within 24 hours.",
    },
    "Electrical": {
        "VIC": "In Victoria, all electrical work must be performed by a licensed electrician registered with Energy Safe Victoria (ESV). A Certificate of Electrical Safety (CES) is required for all prescribed electrical work.",
        "NSW": "In NSW, electricians must hold a contractor licence from NSW Fair Trading. An Electrical Safety Certificate must be issued for all work.",
        "QLD": "In Queensland, a QBCC Electrical Contractor Licence is required. All work must comply with the Wiring Rules (AS/NZS 3000).",
        "WA": "In WA, electricians must be licensed with Electrical Inspections, Department of Energy, Mines, Industry Regulation and Safety.",
        "SA": "In SA, all electrical work must be performed by a licensed electrician. A Certificate of Compliance must be issued and lodged with SAPN.",
        "TAS": "In Tasmania, electrical contractors must be licensed under the Electrical Safety Act. A Certificate of Compliance is required for all work.",
        "ACT": "In the ACT, electricians must be licensed and all work must meet ACTPLA requirements.",
        "NT": "In the NT, electrical work requires a licence from NT Build and must comply with Australian Standard AS/NZS 3000.",
    },
    "Building": {
        "VIC": "In Victoria, builders must be registered with the Victorian Building Authority (VBA). Work over $10,000 requires a Major Domestic Building Contract.",
        "NSW": "In NSW, builders must hold a contractor licence from NSW Fair Trading. Home building work over $20,000 requires home building compensation insurance.",
        "QLD": "In Queensland, builders must hold a QBCC licence. Contracts over $3,300 must be in writing with mandatory cooling-off periods.",
        "WA": "In WA, builders must be registered with the Building Services Board. A home indemnity insurance is required for work over $20,000.",
        "SA": "In SA, builders must be licensed through CBS. A written contract is required for work over $12,000.",
        "TAS": "In Tasmania, building practitioners must be registered under the Building Act 2016.",
        "ACT": "In the ACT, builders must hold an appropriate licence from the ACT Planning and Land Authority.",
        "NT": "In the NT, builders must be licensed with NT Build. Owner-builder permits are available for work under $12,000.",
    },
    "Roofing": {
        "VIC": "In Victoria, roof plumbing work requires a licensed roof plumber registered with the VBA. Structural roofing work requires a registered builder.",
        "NSW": "In NSW, roof plumbing requires a Plumbing Contractor Licence. Structural roofing work requires a building contractor licence.",
        "QLD": "In Queensland, roofers must hold a QBCC licence for roof tiling or roof plumbing as applicable.",
        "WA": "In WA, roof plumbing requires a plumbing licence. Roof tiling work requires a building services registration.",
        "SA": "In SA, roof plumbing requires a plumbing licence from CBS. General roofing contractors should be licensed builders.",
        "TAS": "In Tasmania, roofing contractors must be registered under the Building Act 2016 for any structural work.",
        "ACT": "In the ACT, roof plumbing requires a plumbing licence. Structural roof work requires a building licence.",
        "NT": "In the NT, roofing work requires appropriate licensing from NT Build depending on the nature of work.",
    },
    "Gas Fitting": {
        "VIC": "In Victoria, all gas fitting must be performed by a licensed gasfitter registered with Energy Safe Victoria (ESV). A Certificate of Compliance is required for all gas work.",
        "NSW": "In NSW, gasfitters must hold a gasfitting endorsement on their plumbing licence. All work must meet AS/NZS 5601.",
        "QLD": "In Queensland, gasfitters must hold a QBCC Gas Work Licence. A Certificate of Compliance is required for all gas installations.",
        "WA": "In WA, gas fitting requires a separate gas licence from Building and Energy.",
        "SA": "In SA, gas fitters must be licensed through CBS. A Gas Compliance Certificate must be issued for all work.",
        "TAS": "In Tasmania, gasfitters must be licensed under the Gas Act 2000.",
        "ACT": "In the ACT, gas fitting requires a gasfitting licence from ACTPLA.",
        "NT": "In the NT, gas fitting requires appropriate licensing from NT Build.",
    },
};

export const TRADE_FAQ_BANK: Record<string, Array<{ q: string; a: string }>> = {
    "Plumbing": [
        { q: "How much does a plumber cost per hour in Australia?", a: "Most plumbers charge between $80 and $200 per hour, depending on your state, the complexity of the job, and whether it's emergency work. Emergency callouts typically attract a higher rate of $150–$300/hr plus a callout fee." },
        { q: "Do I need a licensed plumber or can I do it myself?", a: "All plumbing work connected to water supply, drainage, or gas lines must be done by a licensed plumber in every Australian state and territory. DIY plumbing is illegal for these tasks and can void your home insurance." },
        { q: "How long does a blocked drain take to fix?", a: "A standard blocked drain is usually cleared within 1–2 hours. If the blockage is severe or requires drain camera inspection and pipe relining, it may take 4–8 hours or longer." },
        { q: "What should I look for in a plumbing quote?", a: "A good plumbing quote should itemize labour, materials, call-out fees, and GST separately. Ask if the quote is fixed-price or hourly. Always get 2–3 quotes for jobs over $500." },
        { q: "Can I claim plumbing repairs on my home insurance?", a: "Sudden water damage from a burst pipe is usually covered. Gradual leaks and general maintenance are typically not covered. Check your Product Disclosure Statement (PDS) for exact inclusions." },
        { q: "How do I know if my pipes need replacing?", a: "Warning signs include consistently low water pressure, discoloured water, frequent leaks, or pipes that are more than 40 years old. A plumber can inspect with CCTV to give you a definitive answer." },
        { q: "What's the difference between a plumber and a gasfitter?", a: "A plumber works on water supply and drainage systems. A gasfitter is licensed to work on gas lines and appliances. Some tradespeople hold both licences, but always confirm before they start gas work." },
        { q: "How do I turn off my water in an emergency?", a: "Locate your main stopcock, usually outside near the water meter or under the sink. Turn it clockwise to shut off supply. If you can't find it, call your water utility immediately." },
    ],
    "Electrical": [
        { q: "How much does an electrician charge per hour in Australia?", a: "Electricians typically charge $70–$130 per hour depending on the state and job type. After-hours and emergency callouts attract higher rates, often $150–$250/hr plus a callout fee of $80–$150." },
        { q: "Do I need a licensed electrician for all electrical work?", a: "Yes — in Australia, all electrical work including new power points, light fittings, safety switches, and switchboard upgrades must be performed by a licensed electrician. The only DIY exception is replacing light globes." },
        { q: "What is a safety switch and do I need one?", a: "A safety switch (RCD) shuts off power within milliseconds if it detects a fault, protecting against electric shock. Australian standards require safety switches on all power and lighting circuits. If your home doesn't have them, upgrading is a legal requirement when renovating." },
        { q: "How long does a switchboard upgrade take?", a: "A standard switchboard upgrade takes 4–8 hours. If your home needs new wiring runs or the switchboard is in a difficult location, allow a full day. Your electrician will also need to notify your distributor (e.g., Ausgrid, Jemena, Citipower)." },
        { q: "What should a Certificate of Electrical Safety include?", a: "A Certificate of Electrical Safety (CES) must describe the work performed, the licence number of the electrician, the address, and confirm the installation was tested and complies with AS/NZS 3000." },
        { q: "Can I add more power points to my home myself?", a: "No. Adding power points involves working with mains power, which is illegal for unlicensed persons in all Australian states. An electrician can typically add a power point in 1–2 hours for $100–$250 per point." },
        { q: "How do I know if my home's wiring needs replacing?", a: "Signs include frequent tripped circuit breakers, flickering lights, burning smells, discoloured outlet covers, or aluminium wiring (common in homes built in the 1960s–70s). Have a licensed electrician conduct an inspection." },
        { q: "What is the difference between single-phase and three-phase power?", a: "Most Australian homes have single-phase power (240V). Three-phase (415V) is used for high-demand appliances and is common in new homes and commercial premises. Your electrician can advise if an upgrade is needed for EV chargers or large machinery." },
    ],
    "Plastering": [
        { q: "How much does gyprock repair cost in Australia?", a: "Small hole repairs typically cost $80–$200. Repairing a large section of wall or ceiling ranges from $300–$800. Full room replastering can cost $1,500–$4,000+ depending on size and condition." },
        { q: "Do I need a licensed plasterer?", a: "In most Australian states, plastering work over a certain threshold (e.g., $10,000 in Victoria) requires a registered building practitioner. For smaller jobs, using a licensed plasterer is still strongly recommended for quality and warranty reasons." },
        { q: "How long does gyprock repair take to dry before painting?", a: "Plaster compound typically needs 24–48 hours to dry fully between coats, and a minimum 48–72 hours before painting. In humid conditions (common in coastal areas), allow extra drying time." },
        { q: "What's the difference between cornice cement and plaster?", a: "Cornice cement is a pre-mixed adhesive/filler specifically for attaching and patching cornice. Plaster is the base compound for walls and ceilings. Each product has different drying times and finishing properties — using the wrong one is a common DIY mistake." },
        { q: "Can I plaster over existing tiles?", a: "It's possible but not always recommended. A plasterer needs to ensure the tiles are soundly bonded, properly prepared with bonding agent, and the weight load is appropriate. Direct plastering over tiles is common for fire-rated walls." },
        { q: "How do I know if my ceiling needs replastering or just repainting?", a: "If you see cracks running along joins, sagging sections, or water damage, replastering is likely required. If it's just paint peel or minor discolouration, a clean and repaint may be sufficient. A plasterer can assess for free." },
        { q: "What causes cracks in plasterwork?", a: "The most common causes are house settlement (especially in clay soils), thermal expansion, water damage, and vibration from nearby construction. Hairline cracks are usually cosmetic; cracks wider than 5mm or that return after repair may indicate structural movement." },
        { q: "How long does it take to replaster a room?", a: "A standard bedroom takes 1–2 days to plaster, followed by 2–3 days drying time before sanding and painting can begin. Larger rooms or heavy texture coats may take longer." },
    ],
    "Painting": [
        { q: "How much does it cost to paint a house in Australia?", a: "Interior painting of a standard 3-bedroom home typically costs $3,500–$8,000. Exterior painting ranges from $4,000–$12,000 depending on size, storeys, and surface condition. Rates are $40–$70/hr for labour." },
        { q: "How many coats of paint are needed?", a: "Most surfaces need at least 2 coats for full coverage. Over dark colours or bare surfaces, a primer coat plus 2 topcoats is standard. Skipping coats to save money often results in patchy coverage and early failure." },
        { q: "What is the best time of year to paint the exterior of a house in Australia?", a: "Spring and autumn are ideal — avoid extreme heat (over 35°C) which causes paint to dry too fast and blister, and don't paint in the rain or direct frost. In tropical/coastal areas, avoid the wet season for exterior work." },
        { q: "Do painters clean up after themselves?", a: "Reputable painters will cover furniture, protect floors, remove outlet covers, and clean up all materials, drop sheets, and paint cans. Always confirm this is included in your quote." },
        { q: "What's the difference between acrylic and oil-based paint?", a: "Acrylic (water-based) paint dries faster, has less odour, and is the standard for most interior and exterior use. Oil-based paints are more durable and provide a harder finish, commonly used for trims, doors, and cabinetry." },
        { q: "How do I prepare walls before painting?", a: "Fill holes and cracks, sand smooth, clean with sugar soap, and apply primer on bare surfaces or stained areas. Professional painters include preparation in their quote — don't skip this step as paint adheres poorly to dirty or unprimed surfaces." },
        { q: "Do I need a licence to paint houses commercially in Australia?", a: "Domestic painting generally does not require a trade licence in most states (though QLD and some states have painter registration for larger jobs). Always check your state's requirements and ensure the painter carries public liability insurance." },
        { q: "How long does exterior paint last in Australian conditions?", a: "Quality exterior paint should last 7–10 years in temperate climates. Coastal and tropical locations expose paint to salt air, UV, and moisture which can reduce lifespan to 5–7 years without maintenance." },
    ],
    "Cleaning": [
        { q: "How much does end of lease cleaning cost in Australia?", a: "Bond cleaning for a standard 1-bedroom unit typically costs $250–$400. A 3-bedroom house ranges from $400–$800. Prices vary with carpet steam cleaning, oven cleaning, and window cleaning added as extras." },
        { q: "What's the difference between a regular clean and a deep clean?", a: "A regular clean maintains a tidy property with vacuuming, mopping, bathrooms, and kitchen surfaces. A deep clean includes inside appliances, window tracks, skirting boards, light fittings, and areas not covered in routine cleaning — typically taking 2–3x longer." },
        { q: "Will a professional clean guarantee my bond back?", a: "Reputable end-of-lease cleaners offer a bond-back guarantee — they'll return to fix anything the property manager flags within 72 hours at no extra cost. Always confirm this is included before booking." },
        { q: "How often should I get my carpets professionally cleaned?", a: "Landlords typically require steam cleaning at end of lease. For owner-occupiers, professional steam cleaning every 12–18 months is recommended, or every 6 months with pets." },
        { q: "What cleaning products do professional cleaners use?", a: "Professional cleaners use commercial-grade products not available in supermarkets. Reputable services use EPA-approved, low-toxicity products. Request eco-friendly products if you have allergies or young children." },
        { q: "Do I need to be home for a cleaning service?", a: "For most regular cleans, you can provide key access. For end-of-lease and first-time services, being present for the initial walk-through and final check is recommended." },
        { q: "What is NDIS cleaning and how does it work?", a: "NDIS cleaning is funded under the NDIS (National Disability Insurance Scheme) for participants with approved support needs. A registered NDIS cleaning provider invoices the NDIA directly — you don't pay out of pocket if it's in your plan." },
        { q: "Are commercial cleaning services insured?", a: "Any reputable commercial cleaning company should carry public liability insurance (minimum $5–10 million) and workers' compensation. Always ask for a copy of their insurance certificate before signing a contract." },
    ],
    "Roofing": [
        { q: "How much does a roof replacement cost in Australia?", a: "Replacing a standard tiled roof on a 3-bedroom home typically costs $8,000–$18,000. Metal (Colorbond) roofing runs $10,000–$25,000. Factors include roof area, pitch, removal of existing material, and accessibility." },
        { q: "How often should a roof be inspected?", a: "Australian roofing experts recommend an inspection every 2 years, and after any severe storm or hail event. Coastal and high-rainfall areas may need annual inspections due to accelerated wear from salt air and moisture." },
        { q: "Can I walk on my own roof?", a: "Unless you're a trained roofer with appropriate safety equipment, do not walk on your roof. Falls from roofs are one of the leading causes of serious injury in Australia. Even experienced trades use harness systems and edge protection." },
        { q: "What is roof repointing and do I need it?", a: "Repointing is the renewal of the bedding and pointing compound around ridge and hip cappings. Over time, cement-based pointing cracks and allows water ingress. Signs you need repointing include loose or shifted cappings, cracking mortar, and water stains on ceilings." },
        { q: "What's the difference between roof restoration and roof replacement?", a: "Restoration involves cleaning, repointing, resealing, and repainting an existing roof — typically $2,500–$6,000. Replacement means removing and installing new roofing — $8,000–$25,000+. A roofer can assess which is appropriate for your roof's condition." },
        { q: "Does roof work require council approval in Australia?", a: "Like-for-like roof replacement (same material and pitch) generally doesn't require council approval in most states. Changing roof material, pitch, or height typically requires a building permit. Always check with your local council." },
        { q: "How do I know if my roof is leaking or if it's condensation?", a: "Leaks typically cause water stains on the ceiling that correspond to rain events. Condensation appears as moisture on roof timbers or insulation and is worse in winter. A roofer can inspect with a thermal camera or during rain to pinpoint the cause." },
        { q: "How long does a Colorbond roof last compared to tiles?", a: "Colorbond steel roofs are warranted for 10–12 years for paint and much longer structurally, with many lasting 40+ years with maintenance. Concrete tiles last 50+ years but require more frequent repointing. Terracotta tiles can last 100+ years with proper care." },
    ],
    "Landscaping": [
        { q: "How much does landscaping cost in Australia?", a: "Basic landscaping (turf, garden beds, edging) starts around $2,000–$5,000 for a standard backyard. Full landscape design and construction including retaining walls, paving, and planting typically costs $15,000–$60,000+ depending on scope." },
        { q: "Do I need council approval for landscaping?", a: "Most residential landscaping doesn't require council approval. Exceptions include retaining walls over 600mm–1m (varies by council), structures like pergolas or sheds, and work near easements, drainage lines, or overlays. Check with your local council before starting." },
        { q: "What's the best time of year to lay turf in Australia?", a: "Spring and autumn are ideal in most of Australia — soil is warm enough for root establishment without the stress of summer heat. In tropical areas, laying turf at the start of the wet season promotes fast establishment with natural rainfall." },
        { q: "How do I maintain a new lawn after laying turf?", a: "Water twice daily for the first 2 weeks, once daily for weeks 3–4, then transition to deep weekly watering. Don't mow until turf is firmly rooted (lift a corner to check). First mow should take no more than one-third of the leaf height." },
        { q: "What is the difference between a landscape designer and a landscaper?", a: "A landscape designer creates the plans and specifications. A landscaper builds to those plans. Some tradies offer both. For larger projects over $20,000, using a qualified landscape designer ensures council compliance and optimal plant selection." },
        { q: "How deep should a retaining wall footprint be?", a: "A rule of thumb is one-third of the wall height below ground (e.g., a 900mm wall needs a 300mm footing). Walls over 600mm in most states require an engineer's report and building permit." },
        { q: "What native plants are best for low-maintenance Australian gardens?", a: "Popular choices include Grevillea, Westringia (coast rosemary), Lomandra, Callistemon (bottlebrush), and native grasses. These are drought-tolerant, support local wildlife, and require minimal watering once established." },
        { q: "Is artificial turf worth it in Australia?", a: "Artificial turf costs $50–$130/m² installed (vs $15–$40/m² for natural turf). Payback comes from water savings — particularly relevant in Perth and Adelaide where water restrictions apply. Quality artificial turf lasts 15–20 years." },
    ],
    "Carpentry": [
        { q: "How much does a carpenter charge per hour in Australia?", a: "Carpenters typically charge $80–$140 per hour. Specialised work like heritage restoration or custom joinery commands higher rates. Day rates range from $400–$700 for an experienced tradesperson." },
        { q: "Do I need council approval to build a deck in Australia?", a: "Decks under 600mm above ground generally don't require approval in most states, but thresholds vary. Check your local council — larger decks, those attached to a dwelling, or decks in bushfire zones almost always require a permit." },
        { q: "What timber is best for an outdoor deck in Australia?", a: "Hardwoods like Merbau, Spotted Gum, and Ironbark are durable and naturally resistant to insects. Treated pine is a cost-effective option but requires regular oiling. Composite decking (e.g., Trex) offers low maintenance with a higher upfront cost." },
        { q: "How long does it take to build a deck?", a: "A standard 30–40m² timber deck takes 3–5 days to frame and board. Allow additional days for stairs, balustrades, and finishing. Weather delays are common — factor in an extra day or two in your planning." },
        { q: "What's the difference between a carpenter and a cabinetmaker?", a: "A carpenter handles structural and site work — framing, floors, decks, doors, windows, and rough carpentry. A cabinetmaker specialises in furniture and fitted storage (kitchens, wardrobes, built-ins). Some tradespeople are qualified in both." },
        { q: "How do I find the right carpenter for renovation work?", a: "Look for a carpenter with a current builder's licence for any structural work. Check their portfolio, verify references, and get 3 quotes. Ensure they carry public liability and workers' compensation insurance." },
        { q: "What is the expected lifespan of a timber deck?", a: "Hardwood decks with proper installation and regular maintenance (oiling every 1–2 years) last 25–40 years. Treated pine decks last 15–25 years. Composite decking is warrantied for 25–50 years by most manufacturers." },
        { q: "Do carpenters supply their own tools and equipment?", a: "Yes — standard hand and power tools are included in a carpenter's rate. For specialised equipment (crane lifts, elevated work platforms), additional hire costs may apply and should be itemised in the quote." },
    ],
};

export type SuburbContext = {
    housing: string;
    climate: string;
    council: string;
    region: string;
    tradeNotes: Partial<Record<string, string>>;
};

export const SUBURB_CONTEXT: Record<string, SuburbContext> = {
    "belmont": {
        housing: "1960s–1980s brick veneer homes",
        climate: "Geelong's mild maritime climate with occasional strong southerly winds",
        council: "City of Greater Geelong",
        region: "Greater Geelong",
        tradeNotes: {
            "Plastering": "Salt air from nearby Corio Bay can accelerate render cracking in older brick veneer homes in Belmont.",
            "Roofing": "Storm events tracking through the Bass Strait make regular roof inspections particularly important for Belmont properties.",
            "Plumbing": "Many 1970s properties in Belmont still have original galvanised pipes, which are prone to low water pressure and rust.",
            "Painting": "Belmont's coastal proximity means exterior paint is exposed to salt air, requiring high-quality acrylic paints and more frequent repainting cycles.",
        },
    },
    "highton": {
        housing: "1980s–2000s brick homes on elevated blocks with established gardens",
        climate: "elevated position with cooler temperatures and higher rainfall than central Geelong",
        council: "City of Greater Geelong",
        region: "Greater Geelong",
        tradeNotes: {
            "Landscaping": "Highton's sloping blocks often require engineered retaining walls and careful drainage planning to manage the elevated terrain.",
            "Concreting": "The clay-heavy soil in parts of Highton can cause ground movement that affects driveways and paths, requiring reinforced slab designs.",
            "Roofing": "Older Highton homes built on ridgelines are exposed to higher wind speeds, making ridge capping maintenance especially important.",
        },
    },
    "newtown": {
        housing: "period homes from the 1880s–1930s including Victorian and Edwardian terraces",
        climate: "sheltered inner-city location with typical Geelong conditions",
        council: "City of Greater Geelong",
        region: "Greater Geelong",
        tradeNotes: {
            "Plastering": "Newtown's older homes frequently feature original horsehair lime plaster and ornamental cornices that require specialist restoration skills rather than standard gyprock repairs.",
            "Electrical": "Heritage homes in Newtown often have original knob-and-tube or early PVC wiring that needs full assessment before any renovation work begins.",
            "Carpentry": "Victorian-era timber features in Newtown homes including VJ boards, sash windows, and decorative fretwork require a carpenter experienced in heritage restoration.",
            "Painting": "Leadlight windows and original timber joinery in Newtown period homes require careful preparation and specialist paints to preserve heritage features.",
        },
    },
    "geelong-west": {
        housing: "mix of period homes and 1950s–1970s weatherboard and brick properties",
        climate: "inner-west Geelong with typical bay-influenced conditions",
        council: "City of Greater Geelong",
        region: "Greater Geelong",
        tradeNotes: {
            "Painting": "Geelong West's weatherboard homes require careful preparation including scraping, priming, and use of flexible exterior paints to accommodate seasonal timber movement.",
            "Carpentry": "Weatherboard properties in Geelong West commonly need fascia and soffit repairs, particularly on the south-facing elevations exposed to prevailing weather.",
        },
    },
    "grovedale": {
        housing: "1990s–2010s brick veneer homes in established family estates",
        climate: "southern Geelong with a slightly cooler climate and strong south-westerly exposure",
        council: "City of Greater Geelong",
        region: "Greater Geelong",
        tradeNotes: {
            "Air Conditioning & Heating": "Grovedale's south-westerly exposure makes proper insulation and efficient ducted heating systems especially valuable for reducing energy costs.",
            "Fencing": "New subdivisions in Grovedale commonly require boundary fencing coordination between neighbours under the Fences Act 1968.",
        },
    },
    "torquay": {
        housing: "coastal homes from 1980s through to new estate builds, with many holiday properties",
        climate: "exposed coastal location with strong south-westerly winds and salt air from Bass Strait",
        council: "Surf Coast Shire",
        region: "Surf Coast",
        tradeNotes: {
            "Roofing": "Torquay's exposed coastal position means roofing materials need to be rated for high-wind and salt-air environments, with more frequent maintenance required.",
            "Painting": "Salt air from Bass Strait in Torquay significantly accelerates paint degradation — only premium exterior paints with anti-corrosion properties should be used on coastal facades.",
            "Rendering": "Standard cement render is not recommended in Torquay's coastal conditions; acrylic or polymer render systems with salt-resistant additives are the appropriate choice.",
            "Fencing": "Colorbond fencing in Torquay requires marine-grade coatings or powder-coated aluminium to resist the accelerated corrosion from salt air.",
        },
    },
    "bondi": {
        housing: "mix of 1920s–1960s flats and terrace homes alongside modern apartment developments",
        climate: "Sydney's eastern beachside suburb with high UV exposure and salt-laden sea breezes",
        council: "Waverley Council",
        region: "Eastern Suburbs, Sydney",
        tradeNotes: {
            "Painting": "Bondi's strong UV and salt air mean exterior surfaces deteriorate 20–30% faster than inland Sydney properties — premium UV-resistant paints are essential.",
            "Roofing": "Salt air corrosion in Bondi requires roofing materials and fixings rated for marine environments, particularly for metal roofing systems.",
            "Plastering": "High humidity and condensation from ocean proximity in Bondi flats and terrace homes can cause paint blistering and plaster damp problems if moisture barriers aren't correctly installed.",
        },
    },
    "parramatta": {
        housing: "mixed urban area with older brick homes, 1970s–1990s units, and a growing number of high-rise apartments",
        climate: "western Sydney location with hotter summers and cooler winters than coastal areas",
        council: "City of Parramatta",
        region: "Western Sydney",
        tradeNotes: {
            "Air Conditioning & Heating": "Parramatta's western Sydney location experiences some of Sydney's most extreme summer temperatures, making ducted and split-system air conditioning essential rather than optional.",
            "Concreting": "The clay-reactive soils in parts of western Sydney including Parramatta require soil testing and engineered slab designs for any new concrete work.",
        },
    },
    "fitzroy": {
        housing: "Victorian-era terrace homes from the 1880s–1910s with some newer infill apartments",
        climate: "inner Melbourne with typical temperate conditions; frost-free but variable",
        council: "City of Yarra",
        region: "Inner Melbourne",
        tradeNotes: {
            "Plastering": "Heritage terrace homes in Fitzroy frequently have original 3-coat lime plaster on bluestone and brick walls — repairs require matching lime-based products, not modern gypsum plaster.",
            "Electrical": "Older terrace properties in Fitzroy may have early wiring systems including early PVC or even fabric-sheathed wiring that requires full assessment before renovation.",
            "Carpentry": "Fitzroy's Victorian terraces feature original hardwood floors, skirtings, and decorative archways that benefit from a carpenter experienced in heritage joinery restoration.",
        },
    },
    "southport": {
        housing: "mix of 1960s–1990s houses and modern high-rise and medium-density residential",
        climate: "Gold Coast subtropical climate with high humidity, heavy summer rainfall, and occasional severe storms",
        council: "City of Gold Coast",
        region: "Gold Coast",
        tradeNotes: {
            "Roofing": "Southport's subtropical climate and proximity to the Gold Coast's storm corridor means roofing should meet cyclone-rated fixing standards for added resilience.",
            "Waterproofing": "High rainfall and humidity on the Gold Coast make balcony and shower waterproofing particularly critical in Southport — membrane systems must be inspected regularly.",
            "Air Conditioning & Heating": "Southport's subtropical climate means air conditioning runs almost year-round — regular servicing every 12 months is essential for efficiency and to prevent mould in humid conditions.",
        },
    },
};

export function generateLocalizedIntro(
    tradeName: string,
    suburbName: string,
    cityName: string,
    stateName: string,
    businessCount: number,
    avgRating: string,
): string {
    const suburbKey = suburbName.toLowerCase().replace(/\s+/g, "-");
    const ctx = SUBURB_CONTEXT[suburbKey];
    const cost = TRADE_COST_GUIDE[tradeName];
    const year = new Date().getFullYear();

    const countText = businessCount > 0
        ? `TradeRefer currently lists ${businessCount} verified ${tradeName.toLowerCase()} in ${suburbName} with an average rating of ${avgRating} out of 5.`
        : `${tradeName} services are in high demand in ${suburbName} — be among the first to list your business and connect with local customers.`;

    let localDetail: string;
    if (ctx) {
        const tradeNote = ctx.tradeNotes[tradeName];
        if (tradeNote) {
            localDetail = tradeNote;
        } else {
            localDetail = `${suburbName}'s ${ctx.housing} and ${ctx.climate} mean local ${tradeName.toLowerCase()} contractors understand the specific requirements of properties in the ${ctx.region} area.`;
        }
    } else {
        localDetail = `Local ${tradeName.toLowerCase()} in ${suburbName} bring specialist knowledge of ${cityName}'s building regulations, soil conditions, and climate — delivering better results than tradies without local experience.`;
    }

    const licenceInfo = STATE_LICENSING[tradeName]?.[stateName.toUpperCase()];
    const licenceText = licenceInfo
        ? ` ${licenceInfo.split(".")[0]}.`
        : "";

    const priceText = cost
        ? ` ${tradeName} in ${suburbName} typically cost $${cost.low}–$${cost.high}${cost.unit}.`
        : "";

    return `Finding the right ${tradeName.toLowerCase()} in ${suburbName}, ${cityName} can make the difference between a job done right and an expensive fix-up.${priceText} ${localDetail} ${countText}${licenceText} All businesses listed on TradeRefer are ABN-verified and ranked by real community referrals — not paid placement.`;
}
