export const TRADE_CATEGORIES = [
    "Plumbing",
    "Electrical",
    "Carpentry",
    "Landscaping",
    "Roofing",
    "Painting",
    "Cleaning",
    "Building",
    "Concreting",
    "Tiling",
    "Plastering",
    "Fencing",
    "Demolition",
    "Excavation",
    "Air Conditioning & Heating",
    "Solar & Energy",
    "Pest Control",
    "Tree Lopping & Removal",
    "Gardening & Lawn Care",
    "Mowing",
    "Pool & Spa",
    "Bathroom Renovation",
    "Kitchen Renovation",
    "Flooring",
    "Glazing & Windows",
    "Guttering",
    "Handyman",
    "Insulation",
    "Locksmith",
    "Paving",
    "Rendering",
    "Scaffolding",
    "Security Systems",
    "Shopfitting",
    "Signwriting",
    "Stonemasonry",
    "Waterproofing",
    "Welding & Fabrication",
    "Garage Doors",
    "Blinds & Curtains",
    "Cabinet Making",
    "Decking",
    "Drainage",
    "Gas Fitting",
    "Irrigation",
    "Rubbish Removal",
    "Shed Building",
    "Splashbacks",
    "Stump Removal",
    "Surveying",
    "Other"
] as const;

export const GEELONG_SUBURBS = [
    "Anakie",
    "Armstrong Creek",
    "Avalon",
    "Balliang",
    "Bannockburn",
    "Barwon Heads",
    "Batesford",
    "Bell Park",
    "Bell Post Hill",
    "Bellarine",
    "Belmont",
    "Breakwater",
    "Breamlea",
    "Ceres",
    "Charlemont",
    "Clifton Springs",
    "Connewarre",
    "Corio",
    "Curlewis",
    "Drumcondra",
    "Drysdale",
    "East Geelong",
    "Fyansford",
    "Geelong",
    "Geelong West",
    "Grovedale",
    "Hamlyn Heights",
    "Herne Hill",
    "Highton",
    "Indented Head",
    "Lara",
    "Leopold",
    "Little River",
    "Lovely Banks",
    "Manifold Heights",
    "Mannerim",
    "Marcus Hill",
    "Marshall",
    "Moolap",
    "Mount Duneed",
    "Newcomb",
    "Newtown",
    "Norlane",
    "North Geelong",
    "North Shore",
    "Ocean Grove",
    "Point Lonsdale",
    "Point Wilson",
    "Portarlington",
    "Queenscliff",
    "Rippleside",
    "St Albans Park",
    "St Leonards",
    "South Geelong",
    "Staughton Vale",
    "Stonehaven",
    "Swan Bay",
    "Thomson",
    "Torquay",
    "Wallington",
    "Wandana Heights",
    "Waurn Ponds",
    "Whittington"
] as const;
