import { NextResponse } from 'next/server';

export const revalidate = 86400; // 24-hour edge cache

// Sitemaps are generated by the Railway API (no timeout / no response-size limits).
const API = 'https://traderefer-api-production.up.railway.app';

export async function GET() {
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap><loc>${API}/sitemaps/general</loc></sitemap>
  <sitemap><loc>${API}/sitemaps/profiles</loc></sitemap>
  <sitemap><loc>${API}/sitemaps/suburbs</loc></sitemap>
  <sitemap><loc>${API}/sitemaps/trades</loc></sitemap>
  <sitemap><loc>${API}/sitemaps/top</loc></sitemap>
</sitemapindex>`;

    return new NextResponse(xml, {
        headers: {
            'Content-Type': 'application/xml; charset=utf-8',
            'Cache-Control': 'public, s-maxage=86400, stale-while-revalidate',
        },
    });
}
