import type { Tour } from 'nextstepjs';

export const businessTours: Tour[] = [
  {
    tour: 'business-main',
    steps: [
      {
        icon: '👋',
        title: 'Welcome to Your Business Dashboard',
        content: "Let's walk through how to manage your leads, build a referrer network, track performance, and get the most out of TradeRefer. Press Next to begin.",
        selector: undefined,
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 0,
      },
      {
        icon: '⚡',
        title: 'Your Action Queue',
        content: "This is your daily priority list — partner applications from referrers wanting to promote your business, and fresh leads needing a response. Clear this every day for best results.",
        selector: '#tour-biz-action-queue',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '📢',
        title: 'Share Your Referral Network Link',
        content: 'This unique link is how referrers find and join your program. Share it on your website, socials, or with trusted contacts to grow your referrer network faster.',
        selector: '#tour-biz-share-link',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        nextRoute: '/dashboard/business/sales?tab=leads',
      },
      {
        icon: '📥',
        title: 'Manage Your Incoming Leads',
        content: 'Every referral sent by a referrer appears here. You can see the customer name, contact info, and the referrer who sent them. Contact them promptly — speed improves conversion.',
        selector: '#tour-biz-leads-table',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        prevRoute: '/dashboard/business',
      },
      {
        icon: '🔄',
        title: 'Update Lead Status',
        content: 'Update each lead as you work through it — New, Contacted, In Progress, Won, or Lost. Keeping statuses current helps your referrers stay motivated and shows you value their effort.',
        selector: '#tour-biz-leads-status',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        nextRoute: '/dashboard/business/force?tab=partners',
      },
      {
        icon: '🤝',
        title: 'Your Approved Referrer Partners',
        content: 'These referrers are actively promoting your business. A larger, more motivated partner network means more leads. Engage with your top referrers and acknowledge great performance.',
        selector: '#tour-biz-partners-list',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        prevRoute: '/dashboard/business/sales?tab=leads',
      },
      {
        icon: '✅',
        title: 'Approve or Decline Partner Applications',
        content: 'When a referrer applies to promote your business, they appear here. Review their profile and approve quality referrers quickly — the faster you respond, the more motivated they stay.',
        selector: '#tour-biz-partners-pending',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        nextRoute: '/dashboard/business/analytics',
      },
      {
        icon: '📊',
        title: 'Track Your Performance',
        content: 'See how many referrals you received, how many converted, and what revenue your partner network has generated. Use these numbers to decide where to invest more effort.',
        selector: '#tour-biz-analytics-stats',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        prevRoute: '/dashboard/business/force?tab=partners',
        nextRoute: '/dashboard/business/profile',
      },
      {
        icon: '🏢',
        title: 'Your Public Business Profile',
        content: 'This is what referrers see before deciding to promote you. A strong profile with a clear description, good photos, and your service area builds credibility and attracts better referrers.',
        selector: '#tour-biz-profile-preview',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        prevRoute: '/dashboard/business/analytics',
        nextRoute: '/dashboard/business/settings',
      },
      {
        icon: '💲',
        title: 'Set Your Referrer Commission Rate',
        content: 'This is the percentage of a job value you pay referrers for each successful lead. Higher commissions attract more active referrers. Review competitor rates and set competitively.',
        selector: '#tour-biz-settings-commission',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        prevRoute: '/dashboard/business/profile',
      },
      {
        icon: '⏱️',
        title: 'Set Your Response Time',
        content: 'Set a response time target so referrers know how fast you operate. Businesses that respond within an hour convert significantly more leads. ABN verification also builds trust.',
        selector: '#tour-biz-settings-notifications',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🚀',
        title: "You're Ready to Grow!",
        content: 'You now know how to manage leads, approve partners, read your analytics, and configure your settings. Go back to your Overview and start clearing that Action Queue!',
        selector: undefined,
        side: 'bottom',
        showControls: true,
        showSkip: false,
        pointerPadding: 0,
      },
    ],
  },
];
