import type { Tour } from 'nextstepjs';

export const referrerTours: Tour[] = [
  {
    tour: 'referrer-main',
    steps: [
      {
        icon: '👋',
        title: 'Welcome to Your Referrer Dashboard',
        content: 'This short tour will show you everything you need to start earning by referring businesses to people in your network. Press Next to continue, or skip at any time.',
        selector: undefined,
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 0,
      },
      {
        icon: '🏆',
        title: 'Your Partner Tier',
        content: 'This card shows your current earning tier. The higher your tier, the higher your commission — from Partner (80%) up to Ambassador (90%). Complete more referrals to level up.',
        selector: '#tour-overview-tier-card',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '💰',
        title: 'Your Earnings at a Glance',
        content: 'Track your This Week, This Month, Pending, and Lifetime earnings here. Pending earnings are released once the business confirms the lead has converted.',
        selector: '#tour-overview-earnings',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🎯',
        title: 'Your Monthly Referral Goal',
        content: 'Set a personal monthly goal to stay on track. The progress bar updates as your referrals convert. Hitting your goal consistently helps you level up your tier faster.',
        selector: '#tour-overview-monthly-goal',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        nextRoute: '/dashboard/referrer/businesses',
      },
      {
        icon: '🔍',
        title: 'Browse Businesses to Refer',
        content: 'This is where you find businesses to refer. Search by name or filter by trade category to quickly find the right business for your contact.',
        selector: '#tour-network-search',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        prevRoute: '/dashboard/referrer',
      },
      {
        icon: '🏷️',
        title: 'Filter by Trade Category',
        content: 'Tap any category pill to filter businesses by trade — plumbing, electrical, landscaping, and more. This helps you quickly match businesses with your referral contacts.',
        selector: '#tour-network-categories',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
      },
      {
        icon: '🔗',
        title: 'Apply to Refer a Business',
        content: 'Click "Apply to Refer" to view a business\'s referral opportunity and join their network. Once approved, you\'ll get a unique tracking link to share — when someone books through it, you earn a commission.',
        selector: '#tour-network-referral-link',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        nextRoute: '/dashboard/referrer/applications',
      },
      {
        icon: '📋',
        title: 'Track Your Referral Applications',
        content: 'Every referral you send appears here as an application. Check the status — Pending, Approved, or Completed — and follow up if needed. Approved applications earn you commission.',
        selector: '#tour-applications-list',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        prevRoute: '/dashboard/referrer/businesses',
        nextRoute: '/dashboard/referrer/withdraw',
      },
      {
        icon: '💳',
        title: 'Your Rewards Balance',
        content: 'Your available balance lives here. Once a business approves your referral and the job is completed, your commission appears in this balance ready to withdraw.',
        selector: '#tour-rewards-balance',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        prevRoute: '/dashboard/referrer/applications',
      },
      {
        icon: '🏦',
        title: 'Withdraw Your Earnings',
        content: 'When you have enough balance, tap Withdraw to receive a Prezzee Smart eGift Card. Choose from 300+ brands including Woolworths, Bunnings, Uber, and Netflix.',
        selector: '#tour-rewards-withdraw',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        nextRoute: '/dashboard/referrer/profile',
      },
      {
        icon: '👤',
        title: 'Complete Your Referrer Profile',
        content: 'Businesses check your profile before approving referrals. Add your photo, a short bio, and your areas of expertise to increase your approval rate and build trust.',
        selector: '#tour-profile-photo',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        prevRoute: '/dashboard/referrer/withdraw',
        nextRoute: '/dashboard/referrer/manage',
      },
      {
        icon: '👥',
        title: 'Grow Your Team of Referrers',
        content: 'Invite others to join TradeRefer under your team. When your team members earn commissions, you receive a bonus on top of their earnings — accelerating your passive income.',
        selector: '#tour-team-invite',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 8,
        prevRoute: '/dashboard/referrer/profile',
      },
      {
        icon: '🎉',
        title: "You're All Set!",
        content: 'You now know how to find businesses, share your referral link, track your applications, withdraw earnings, and grow your team. Start by browsing businesses to make your first referral!',
        selector: undefined,
        side: 'bottom',
        showControls: true,
        showSkip: false,
        pointerPadding: 0,
      },
    ],
  },
];
